// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: onchainpoker/dealer/module/v1/module.proto

package modulev1

import (
	bytes "bytes"
	_ "cosmossdk.io/depinject/appconfig/v1alpha1"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Module is the appmodule config object for x/dealer.
//
// It is intentionally empty for now; add fields as module-level params/wiring needs grow.
type Module struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Module) Reset()         { *m = Module{} }
func (m *Module) String() string { return proto.CompactTextString(m) }
func (*Module) ProtoMessage()    {}
func (*Module) Descriptor() ([]byte, []int) {
	return fileDescriptor_aece63d010ab9538, []int{0}
}
func (m *Module) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Module.Unmarshal(m, b)
}
func (m *Module) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Module.Marshal(b, m, deterministic)
}
func (m *Module) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Module.Merge(m, src)
}
func (m *Module) XXX_Size() int {
	return xxx_messageInfo_Module.Size(m)
}
func (m *Module) XXX_DiscardUnknown() {
	xxx_messageInfo_Module.DiscardUnknown(m)
}

var xxx_messageInfo_Module proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Module)(nil), "onchainpoker.dealer.module.v1.Module")
}

func init() {
	proto.RegisterFile("onchainpoker/dealer/module/v1/module.proto", fileDescriptor_aece63d010ab9538)
}

var fileDescriptor_aece63d010ab9538 = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0xca, 0xcf, 0x4b, 0xce,
	0x48, 0xcc, 0xcc, 0x2b, 0xc8, 0xcf, 0x4e, 0x2d, 0xd2, 0x4f, 0x49, 0x4d, 0xcc, 0x49, 0x2d, 0xd2,
	0xcf, 0xcd, 0x4f, 0x29, 0xcd, 0x49, 0xd5, 0x2f, 0x33, 0x84, 0xb2, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b,
	0xf2, 0x85, 0x64, 0x91, 0xd5, 0xea, 0x41, 0xd4, 0xea, 0x41, 0x55, 0x94, 0x19, 0x4a, 0x29, 0x24,
	0xe7, 0x17, 0xe7, 0xe6, 0x17, 0xeb, 0x27, 0x16, 0x14, 0xe8, 0x97, 0x19, 0x26, 0xe6, 0x14, 0x64,
	0x24, 0xa2, 0x1a, 0x20, 0x25, 0x92, 0x9e, 0x9f, 0x9e, 0x0f, 0x66, 0xea, 0x83, 0x58, 0x10, 0x51,
	0x25, 0x63, 0x2e, 0x36, 0x5f, 0xb0, 0x2a, 0x2b, 0xcd, 0x5d, 0x07, 0xa6, 0xdd, 0x62, 0x54, 0xe6,
	0x52, 0x44, 0x71, 0x54, 0x62, 0x41, 0x41, 0xb1, 0x3e, 0xd4, 0xec, 0x0a, 0xa8, 0x13, 0x9d, 0x14,
	0x57, 0x3c, 0x92, 0x63, 0x8c, 0x92, 0xae, 0xc0, 0x70, 0xb2, 0x35, 0x84, 0x55, 0x66, 0x98, 0xc4,
	0x06, 0x36, 0xde, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xc1, 0x81, 0x5b, 0xc3, 0xe3, 0x00, 0x00,
	0x00,
}

func (this *Module) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Module)
	if !ok {
		that2, ok := that.(Module)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
