// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: onchainpoker/poker/v1/poker.proto

package types

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type HandPhase int32

const (
	HandPhase_HAND_PHASE_UNSPECIFIED    HandPhase = 0
	HandPhase_HAND_PHASE_SHUFFLE        HandPhase = 1
	HandPhase_HAND_PHASE_BETTING        HandPhase = 2
	HandPhase_HAND_PHASE_AWAIT_FLOP     HandPhase = 3
	HandPhase_HAND_PHASE_AWAIT_TURN     HandPhase = 4
	HandPhase_HAND_PHASE_AWAIT_RIVER    HandPhase = 5
	HandPhase_HAND_PHASE_AWAIT_SHOWDOWN HandPhase = 6
	HandPhase_HAND_PHASE_SHOWDOWN       HandPhase = 7
)

var HandPhase_name = map[int32]string{
	0: "HAND_PHASE_UNSPECIFIED",
	1: "HAND_PHASE_SHUFFLE",
	2: "HAND_PHASE_BETTING",
	3: "HAND_PHASE_AWAIT_FLOP",
	4: "HAND_PHASE_AWAIT_TURN",
	5: "HAND_PHASE_AWAIT_RIVER",
	6: "HAND_PHASE_AWAIT_SHOWDOWN",
	7: "HAND_PHASE_SHOWDOWN",
}

var HandPhase_value = map[string]int32{
	"HAND_PHASE_UNSPECIFIED":    0,
	"HAND_PHASE_SHUFFLE":        1,
	"HAND_PHASE_BETTING":        2,
	"HAND_PHASE_AWAIT_FLOP":     3,
	"HAND_PHASE_AWAIT_TURN":     4,
	"HAND_PHASE_AWAIT_RIVER":    5,
	"HAND_PHASE_AWAIT_SHOWDOWN": 6,
	"HAND_PHASE_SHOWDOWN":       7,
}

func (x HandPhase) String() string {
	return proto.EnumName(HandPhase_name, int32(x))
}

func (HandPhase) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b562bf5e5877c9a5, []int{0}
}

type Street int32

const (
	Street_STREET_UNSPECIFIED Street = 0
	Street_STREET_PREFLOP     Street = 1
	Street_STREET_FLOP        Street = 2
	Street_STREET_TURN        Street = 3
	Street_STREET_RIVER       Street = 4
)

var Street_name = map[int32]string{
	0: "STREET_UNSPECIFIED",
	1: "STREET_PREFLOP",
	2: "STREET_FLOP",
	3: "STREET_TURN",
	4: "STREET_RIVER",
}

var Street_value = map[string]int32{
	"STREET_UNSPECIFIED": 0,
	"STREET_PREFLOP":     1,
	"STREET_FLOP":        2,
	"STREET_TURN":        3,
	"STREET_RIVER":       4,
}

func (x Street) String() string {
	return proto.EnumName(Street_name, int32(x))
}

func (Street) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b562bf5e5877c9a5, []int{1}
}

// GenesisState defines the x/poker module genesis state.
type GenesisState struct {
	NextTableId          uint64   `protobuf:"varint,1,opt,name=next_table_id,json=nextTableId,proto3" json:"next_table_id,omitempty"`
	Tables               []Table  `protobuf:"bytes,2,rep,name=tables,proto3" json:"tables"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_b562bf5e5877c9a5, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenesisState.Unmarshal(m, b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return xxx_messageInfo_GenesisState.Size(m)
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetNextTableId() uint64 {
	if m != nil {
		return m.NextTableId
	}
	return 0
}

func (m *GenesisState) GetTables() []Table {
	if m != nil {
		return m.Tables
	}
	return nil
}

type TableParams struct {
	MaxPlayers        uint32 `protobuf:"varint,1,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	SmallBlind        uint64 `protobuf:"varint,2,opt,name=small_blind,json=smallBlind,proto3" json:"small_blind,omitempty"`
	BigBlind          uint64 `protobuf:"varint,3,opt,name=big_blind,json=bigBlind,proto3" json:"big_blind,omitempty"`
	MinBuyIn          uint64 `protobuf:"varint,4,opt,name=min_buy_in,json=minBuyIn,proto3" json:"min_buy_in,omitempty"`
	MaxBuyIn          uint64 `protobuf:"varint,5,opt,name=max_buy_in,json=maxBuyIn,proto3" json:"max_buy_in,omitempty"`
	ActionTimeoutSecs uint64 `protobuf:"varint,6,opt,name=action_timeout_secs,json=actionTimeoutSecs,proto3" json:"action_timeout_secs,omitempty"`
	DealerTimeoutSecs uint64 `protobuf:"varint,7,opt,name=dealer_timeout_secs,json=dealerTimeoutSecs,proto3" json:"dealer_timeout_secs,omitempty"`
	PlayerBond        uint64 `protobuf:"varint,8,opt,name=player_bond,json=playerBond,proto3" json:"player_bond,omitempty"`
	RakeBps           uint32 `protobuf:"varint,9,opt,name=rake_bps,json=rakeBps,proto3" json:"rake_bps,omitempty"`
	// 32-byte SHA256(password_salt || password) commitment. Empty = no password.
	// Pre-v2 legacy tables store SHA256(password) here with password_salt empty;
	// the client computes the proof against whichever salt is on-chain.
	PasswordHash []byte `protobuf:"bytes,10,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	// 32 random bytes for tables created after the v2 password rollout; empty
	// for legacy tables. Public — clients read it to compute password_proof.
	PasswordSalt         []byte   `protobuf:"bytes,11,opt,name=password_salt,json=passwordSalt,proto3" json:"password_salt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TableParams) Reset()         { *m = TableParams{} }
func (m *TableParams) String() string { return proto.CompactTextString(m) }
func (*TableParams) ProtoMessage()    {}
func (*TableParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_b562bf5e5877c9a5, []int{1}
}
func (m *TableParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TableParams.Unmarshal(m, b)
}
func (m *TableParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TableParams.Marshal(b, m, deterministic)
}
func (m *TableParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TableParams.Merge(m, src)
}
func (m *TableParams) XXX_Size() int {
	return xxx_messageInfo_TableParams.Size(m)
}
func (m *TableParams) XXX_DiscardUnknown() {
	xxx_messageInfo_TableParams.DiscardUnknown(m)
}

var xxx_messageInfo_TableParams proto.InternalMessageInfo

func (m *TableParams) GetMaxPlayers() uint32 {
	if m != nil {
		return m.MaxPlayers
	}
	return 0
}

func (m *TableParams) GetSmallBlind() uint64 {
	if m != nil {
		return m.SmallBlind
	}
	return 0
}

func (m *TableParams) GetBigBlind() uint64 {
	if m != nil {
		return m.BigBlind
	}
	return 0
}

func (m *TableParams) GetMinBuyIn() uint64 {
	if m != nil {
		return m.MinBuyIn
	}
	return 0
}

func (m *TableParams) GetMaxBuyIn() uint64 {
	if m != nil {
		return m.MaxBuyIn
	}
	return 0
}

func (m *TableParams) GetActionTimeoutSecs() uint64 {
	if m != nil {
		return m.ActionTimeoutSecs
	}
	return 0
}

func (m *TableParams) GetDealerTimeoutSecs() uint64 {
	if m != nil {
		return m.DealerTimeoutSecs
	}
	return 0
}

func (m *TableParams) GetPlayerBond() uint64 {
	if m != nil {
		return m.PlayerBond
	}
	return 0
}

func (m *TableParams) GetRakeBps() uint32 {
	if m != nil {
		return m.RakeBps
	}
	return 0
}

func (m *TableParams) GetPasswordHash() []byte {
	if m != nil {
		return m.PasswordHash
	}
	return nil
}

func (m *TableParams) GetPasswordSalt() []byte {
	if m != nil {
		return m.PasswordSalt
	}
	return nil
}

type Seat struct {
	Player string `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	Pk     []byte `protobuf:"bytes,2,opt,name=pk,proto3" json:"pk,omitempty"`
	Stack  uint64 `protobuf:"varint,3,opt,name=stack,proto3" json:"stack,omitempty"`
	Bond   uint64 `protobuf:"varint,4,opt,name=bond,proto3" json:"bond,omitempty"`
	// Public hole cards (set during showdown reveal). Unknown cards are stored as 0.
	Hole                 []uint32 `protobuf:"varint,5,rep,packed,name=hole,proto3" json:"hole,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Seat) Reset()         { *m = Seat{} }
func (m *Seat) String() string { return proto.CompactTextString(m) }
func (*Seat) ProtoMessage()    {}
func (*Seat) Descriptor() ([]byte, []int) {
	return fileDescriptor_b562bf5e5877c9a5, []int{2}
}
func (m *Seat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Seat.Unmarshal(m, b)
}
func (m *Seat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Seat.Marshal(b, m, deterministic)
}
func (m *Seat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Seat.Merge(m, src)
}
func (m *Seat) XXX_Size() int {
	return xxx_messageInfo_Seat.Size(m)
}
func (m *Seat) XXX_DiscardUnknown() {
	xxx_messageInfo_Seat.DiscardUnknown(m)
}

var xxx_messageInfo_Seat proto.InternalMessageInfo

func (m *Seat) GetPlayer() string {
	if m != nil {
		return m.Player
	}
	return ""
}

func (m *Seat) GetPk() []byte {
	if m != nil {
		return m.Pk
	}
	return nil
}

func (m *Seat) GetStack() uint64 {
	if m != nil {
		return m.Stack
	}
	return 0
}

func (m *Seat) GetBond() uint64 {
	if m != nil {
		return m.Bond
	}
	return 0
}

func (m *Seat) GetHole() []uint32 {
	if m != nil {
		return m.Hole
	}
	return nil
}

// DealerMeta is the minimal dealer state needed by the poker state machine.
// Encrypted deck/shares are stored in x/dealer.
type DealerMeta struct {
	EpochId       uint64 `protobuf:"varint,1,opt,name=epoch_id,json=epochId,proto3" json:"epoch_id,omitempty"`
	DeckSize      uint32 `protobuf:"varint,2,opt,name=deck_size,json=deckSize,proto3" json:"deck_size,omitempty"`
	DeckFinalized bool   `protobuf:"varint,3,opt,name=deck_finalized,json=deckFinalized,proto3" json:"deck_finalized,omitempty"`
	// Hole card deck positions for seats, length 18: [seat0_card0, seat0_card1, seat1_card0, ...].
	// Value 255 means unset.
	HolePos []uint32 `protobuf:"varint,4,rep,packed,name=hole_pos,json=holePos,proto3" json:"hole_pos,omitempty"`
	// Cursor points to the next board card position in the dealer deck (after hole card assignment).
	Cursor uint32 `protobuf:"varint,5,opt,name=cursor,proto3" json:"cursor,omitempty"`
	// RevealPos is the currently expected reveal position (255 means "not awaiting").
	RevealPos            uint32   `protobuf:"varint,6,opt,name=reveal_pos,json=revealPos,proto3" json:"reveal_pos,omitempty"`
	RevealDeadline       int64    `protobuf:"varint,7,opt,name=reveal_deadline,json=revealDeadline,proto3" json:"reveal_deadline,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DealerMeta) Reset()         { *m = DealerMeta{} }
func (m *DealerMeta) String() string { return proto.CompactTextString(m) }
func (*DealerMeta) ProtoMessage()    {}
func (*DealerMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_b562bf5e5877c9a5, []int{3}
}
func (m *DealerMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealerMeta.Unmarshal(m, b)
}
func (m *DealerMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealerMeta.Marshal(b, m, deterministic)
}
func (m *DealerMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealerMeta.Merge(m, src)
}
func (m *DealerMeta) XXX_Size() int {
	return xxx_messageInfo_DealerMeta.Size(m)
}
func (m *DealerMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_DealerMeta.DiscardUnknown(m)
}

var xxx_messageInfo_DealerMeta proto.InternalMessageInfo

func (m *DealerMeta) GetEpochId() uint64 {
	if m != nil {
		return m.EpochId
	}
	return 0
}

func (m *DealerMeta) GetDeckSize() uint32 {
	if m != nil {
		return m.DeckSize
	}
	return 0
}

func (m *DealerMeta) GetDeckFinalized() bool {
	if m != nil {
		return m.DeckFinalized
	}
	return false
}

func (m *DealerMeta) GetHolePos() []uint32 {
	if m != nil {
		return m.HolePos
	}
	return nil
}

func (m *DealerMeta) GetCursor() uint32 {
	if m != nil {
		return m.Cursor
	}
	return 0
}

func (m *DealerMeta) GetRevealPos() uint32 {
	if m != nil {
		return m.RevealPos
	}
	return 0
}

func (m *DealerMeta) GetRevealDeadline() int64 {
	if m != nil {
		return m.RevealDeadline
	}
	return 0
}

type Hand struct {
	HandId         uint64    `protobuf:"varint,1,opt,name=hand_id,json=handId,proto3" json:"hand_id,omitempty"`
	Phase          HandPhase `protobuf:"varint,2,opt,name=phase,proto3,enum=onchainpoker.poker.v1.HandPhase" json:"phase,omitempty"`
	Street         Street    `protobuf:"varint,3,opt,name=street,proto3,enum=onchainpoker.poker.v1.Street" json:"street,omitempty"`
	ButtonSeat     int32     `protobuf:"varint,4,opt,name=button_seat,json=buttonSeat,proto3" json:"button_seat,omitempty"`
	SmallBlindSeat int32     `protobuf:"varint,5,opt,name=small_blind_seat,json=smallBlindSeat,proto3" json:"small_blind_seat,omitempty"`
	BigBlindSeat   int32     `protobuf:"varint,6,opt,name=big_blind_seat,json=bigBlindSeat,proto3" json:"big_blind_seat,omitempty"`
	// ActionOn is the seat index that must act next, or -1.
	ActionOn     int32  `protobuf:"varint,7,opt,name=action_on,json=actionOn,proto3" json:"action_on,omitempty"`
	BetTo        uint64 `protobuf:"varint,8,opt,name=bet_to,json=betTo,proto3" json:"bet_to,omitempty"`
	MinRaiseSize uint64 `protobuf:"varint,9,opt,name=min_raise_size,json=minRaiseSize,proto3" json:"min_raise_size,omitempty"`
	IntervalId   uint64 `protobuf:"varint,10,opt,name=interval_id,json=intervalId,proto3" json:"interval_id,omitempty"`
	// Per-seat arrays. Each must have length 9.
	InHand            []bool   `protobuf:"varint,11,rep,packed,name=in_hand,json=inHand,proto3" json:"in_hand,omitempty"`
	Folded            []bool   `protobuf:"varint,12,rep,packed,name=folded,proto3" json:"folded,omitempty"`
	AllIn             []bool   `protobuf:"varint,13,rep,packed,name=all_in,json=allIn,proto3" json:"all_in,omitempty"`
	StreetCommit      []uint64 `protobuf:"varint,14,rep,packed,name=street_commit,json=streetCommit,proto3" json:"street_commit,omitempty"`
	TotalCommit       []uint64 `protobuf:"varint,15,rep,packed,name=total_commit,json=totalCommit,proto3" json:"total_commit,omitempty"`
	LastIntervalActed []int32  `protobuf:"varint,16,rep,packed,name=last_interval_acted,json=lastIntervalActed,proto3" json:"last_interval_acted,omitempty"`
	// Public board cards (card ids 0..51).
	Board []uint32 `protobuf:"varint,17,rep,packed,name=board,proto3" json:"board,omitempty"`
	// Poker action timeout.
	ActionDeadline int64 `protobuf:"varint,18,opt,name=action_deadline,json=actionDeadline,proto3" json:"action_deadline,omitempty"`
	// Dealer integration.
	Dealer               *DealerMeta `protobuf:"bytes,19,opt,name=dealer,proto3" json:"dealer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Hand) Reset()         { *m = Hand{} }
func (m *Hand) String() string { return proto.CompactTextString(m) }
func (*Hand) ProtoMessage()    {}
func (*Hand) Descriptor() ([]byte, []int) {
	return fileDescriptor_b562bf5e5877c9a5, []int{4}
}
func (m *Hand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hand.Unmarshal(m, b)
}
func (m *Hand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hand.Marshal(b, m, deterministic)
}
func (m *Hand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hand.Merge(m, src)
}
func (m *Hand) XXX_Size() int {
	return xxx_messageInfo_Hand.Size(m)
}
func (m *Hand) XXX_DiscardUnknown() {
	xxx_messageInfo_Hand.DiscardUnknown(m)
}

var xxx_messageInfo_Hand proto.InternalMessageInfo

func (m *Hand) GetHandId() uint64 {
	if m != nil {
		return m.HandId
	}
	return 0
}

func (m *Hand) GetPhase() HandPhase {
	if m != nil {
		return m.Phase
	}
	return HandPhase_HAND_PHASE_UNSPECIFIED
}

func (m *Hand) GetStreet() Street {
	if m != nil {
		return m.Street
	}
	return Street_STREET_UNSPECIFIED
}

func (m *Hand) GetButtonSeat() int32 {
	if m != nil {
		return m.ButtonSeat
	}
	return 0
}

func (m *Hand) GetSmallBlindSeat() int32 {
	if m != nil {
		return m.SmallBlindSeat
	}
	return 0
}

func (m *Hand) GetBigBlindSeat() int32 {
	if m != nil {
		return m.BigBlindSeat
	}
	return 0
}

func (m *Hand) GetActionOn() int32 {
	if m != nil {
		return m.ActionOn
	}
	return 0
}

func (m *Hand) GetBetTo() uint64 {
	if m != nil {
		return m.BetTo
	}
	return 0
}

func (m *Hand) GetMinRaiseSize() uint64 {
	if m != nil {
		return m.MinRaiseSize
	}
	return 0
}

func (m *Hand) GetIntervalId() uint64 {
	if m != nil {
		return m.IntervalId
	}
	return 0
}

func (m *Hand) GetInHand() []bool {
	if m != nil {
		return m.InHand
	}
	return nil
}

func (m *Hand) GetFolded() []bool {
	if m != nil {
		return m.Folded
	}
	return nil
}

func (m *Hand) GetAllIn() []bool {
	if m != nil {
		return m.AllIn
	}
	return nil
}

func (m *Hand) GetStreetCommit() []uint64 {
	if m != nil {
		return m.StreetCommit
	}
	return nil
}

func (m *Hand) GetTotalCommit() []uint64 {
	if m != nil {
		return m.TotalCommit
	}
	return nil
}

func (m *Hand) GetLastIntervalActed() []int32 {
	if m != nil {
		return m.LastIntervalActed
	}
	return nil
}

func (m *Hand) GetBoard() []uint32 {
	if m != nil {
		return m.Board
	}
	return nil
}

func (m *Hand) GetActionDeadline() int64 {
	if m != nil {
		return m.ActionDeadline
	}
	return 0
}

func (m *Hand) GetDealer() *DealerMeta {
	if m != nil {
		return m.Dealer
	}
	return nil
}

type Table struct {
	Id      uint64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Creator string      `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
	Label   string      `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Params  TableParams `protobuf:"bytes,4,opt,name=params,proto3" json:"params"`
	// Fixed-size (9) seats. Empty seats have an empty `player` string.
	Seats                []*Seat  `protobuf:"bytes,5,rep,name=seats,proto3" json:"seats,omitempty"`
	NextHandId           uint64   `protobuf:"varint,6,opt,name=next_hand_id,json=nextHandId,proto3" json:"next_hand_id,omitempty"`
	ButtonSeat           int32    `protobuf:"varint,7,opt,name=button_seat,json=buttonSeat,proto3" json:"button_seat,omitempty"`
	Hand                 *Hand    `protobuf:"bytes,8,opt,name=hand,proto3" json:"hand,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Table) Reset()         { *m = Table{} }
func (m *Table) String() string { return proto.CompactTextString(m) }
func (*Table) ProtoMessage()    {}
func (*Table) Descriptor() ([]byte, []int) {
	return fileDescriptor_b562bf5e5877c9a5, []int{5}
}
func (m *Table) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Table.Unmarshal(m, b)
}
func (m *Table) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Table.Marshal(b, m, deterministic)
}
func (m *Table) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Table.Merge(m, src)
}
func (m *Table) XXX_Size() int {
	return xxx_messageInfo_Table.Size(m)
}
func (m *Table) XXX_DiscardUnknown() {
	xxx_messageInfo_Table.DiscardUnknown(m)
}

var xxx_messageInfo_Table proto.InternalMessageInfo

func (m *Table) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Table) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Table) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Table) GetParams() TableParams {
	if m != nil {
		return m.Params
	}
	return TableParams{}
}

func (m *Table) GetSeats() []*Seat {
	if m != nil {
		return m.Seats
	}
	return nil
}

func (m *Table) GetNextHandId() uint64 {
	if m != nil {
		return m.NextHandId
	}
	return 0
}

func (m *Table) GetButtonSeat() int32 {
	if m != nil {
		return m.ButtonSeat
	}
	return 0
}

func (m *Table) GetHand() *Hand {
	if m != nil {
		return m.Hand
	}
	return nil
}

func init() {
	proto.RegisterEnum("onchainpoker.poker.v1.HandPhase", HandPhase_name, HandPhase_value)
	proto.RegisterEnum("onchainpoker.poker.v1.Street", Street_name, Street_value)
	proto.RegisterType((*GenesisState)(nil), "onchainpoker.poker.v1.GenesisState")
	proto.RegisterType((*TableParams)(nil), "onchainpoker.poker.v1.TableParams")
	proto.RegisterType((*Seat)(nil), "onchainpoker.poker.v1.Seat")
	proto.RegisterType((*DealerMeta)(nil), "onchainpoker.poker.v1.DealerMeta")
	proto.RegisterType((*Hand)(nil), "onchainpoker.poker.v1.Hand")
	proto.RegisterType((*Table)(nil), "onchainpoker.poker.v1.Table")
}

func init() { proto.RegisterFile("onchainpoker/poker/v1/poker.proto", fileDescriptor_b562bf5e5877c9a5) }

var fileDescriptor_b562bf5e5877c9a5 = []byte{
	// 1170 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x56, 0xdd, 0x6e, 0x1b, 0x37,
	0x13, 0x8d, 0x7e, 0x76, 0x25, 0xcd, 0x4a, 0x8a, 0x42, 0x27, 0xce, 0x26, 0x4e, 0x3e, 0x2b, 0xfa,
	0x5a, 0x54, 0xc8, 0x85, 0x83, 0xb8, 0x48, 0x0b, 0xf4, 0xa6, 0xb5, 0x62, 0x39, 0x12, 0x90, 0xda,
	0x02, 0xa5, 0x34, 0x40, 0x6f, 0x16, 0x5c, 0x2d, 0x63, 0x11, 0x5e, 0x91, 0x8b, 0x25, 0xed, 0xda,
	0x7e, 0x88, 0x3e, 0x47, 0x9f, 0xa1, 0xe8, 0x03, 0xf4, 0x29, 0x0a, 0xb4, 0x17, 0x7d, 0x8e, 0x82,
	0xc3, 0x95, 0xff, 0x12, 0xe7, 0x46, 0xd8, 0x39, 0xe7, 0x70, 0x39, 0x33, 0x9c, 0xc3, 0x15, 0x3c,
	0x53, 0x72, 0xbe, 0x60, 0x42, 0x66, 0xea, 0x88, 0xe7, 0x2f, 0xdc, 0xef, 0xc9, 0x4b, 0xf7, 0xb0,
	0x95, 0xe5, 0xca, 0x28, 0xf2, 0xe0, 0xaa, 0x64, 0xcb, 0xfd, 0x9e, 0xbc, 0x7c, 0x7c, 0xff, 0x50,
	0x1d, 0x2a, 0x54, 0xbc, 0xb0, 0x4f, 0x4e, 0xdc, 0x93, 0xd0, 0x7c, 0xc3, 0x25, 0xd7, 0x42, 0x4f,
	0x0d, 0x33, 0x9c, 0xf4, 0xa0, 0x25, 0xf9, 0xa9, 0x89, 0x0c, 0x8b, 0x53, 0x1e, 0x89, 0x24, 0x2c,
	0x75, 0x4b, 0xfd, 0x2a, 0x0d, 0x2c, 0x38, 0xb3, 0xd8, 0x38, 0x21, 0xdf, 0x81, 0x8f, 0xb4, 0x0e,
	0xcb, 0xdd, 0x4a, 0x3f, 0xd8, 0x7e, 0xb2, 0xf5, 0xc9, 0x1d, 0xb7, 0x50, 0x3f, 0xa8, 0xfe, 0xf9,
	0xd7, 0xe6, 0x1d, 0x5a, 0xac, 0xe8, 0xfd, 0x5a, 0x81, 0x00, 0xf1, 0x09, 0xcb, 0xd9, 0x52, 0x93,
	0x4d, 0x08, 0x96, 0xec, 0x34, 0xca, 0x52, 0x76, 0xc6, 0x73, 0x8d, 0xbb, 0xb5, 0x28, 0x2c, 0xd9,
	0xe9, 0xc4, 0x21, 0x56, 0xa0, 0x97, 0x2c, 0x4d, 0xa3, 0x38, 0x15, 0x32, 0x09, 0xcb, 0x98, 0x0e,
	0x20, 0x34, 0xb0, 0x08, 0xd9, 0x80, 0x46, 0x2c, 0x0e, 0x0b, 0xba, 0x82, 0x74, 0x3d, 0x16, 0x87,
	0x8e, 0x7c, 0x02, 0xb0, 0x14, 0x32, 0x8a, 0x8f, 0xcf, 0x22, 0x21, 0xc3, 0xaa, 0x63, 0x97, 0x42,
	0x0e, 0x8e, 0xcf, 0xc6, 0x12, 0x59, 0x76, 0xba, 0x62, 0xbd, 0x82, 0x65, 0xa7, 0x8e, 0xdd, 0x82,
	0x35, 0x36, 0x37, 0x42, 0xc9, 0xc8, 0x88, 0x25, 0x57, 0xc7, 0x26, 0xd2, 0x7c, 0xae, 0x43, 0x1f,
	0x65, 0xf7, 0x1c, 0x35, 0x73, 0xcc, 0x94, 0xcf, 0xb5, 0xd5, 0x27, 0x9c, 0xa5, 0x3c, 0xbf, 0xae,
	0xaf, 0x39, 0xbd, 0xa3, 0xae, 0xea, 0x37, 0x21, 0x70, 0x65, 0x47, 0xb1, 0x92, 0x49, 0x58, 0x77,
	0x95, 0x39, 0x68, 0xa0, 0x64, 0x42, 0x1e, 0x41, 0x3d, 0x67, 0x47, 0x3c, 0x8a, 0x33, 0x1d, 0x36,
	0xb0, 0x31, 0x35, 0x1b, 0x0f, 0x32, 0x4d, 0xfe, 0x0f, 0xad, 0x8c, 0x69, 0xfd, 0x8b, 0xca, 0x93,
	0x68, 0xc1, 0xf4, 0x22, 0x84, 0x6e, 0xa9, 0xdf, 0xa4, 0xcd, 0x15, 0x38, 0x62, 0x7a, 0x71, 0x4d,
	0xa4, 0x59, 0x6a, 0xc2, 0xe0, 0xba, 0x68, 0xca, 0x52, 0xd3, 0x4b, 0xa1, 0x3a, 0xe5, 0xcc, 0x90,
	0x75, 0xf0, 0xdd, 0xd6, 0x78, 0x06, 0x0d, 0x5a, 0x44, 0xa4, 0x0d, 0xe5, 0xec, 0x08, 0xdb, 0xde,
	0xa4, 0xe5, 0xec, 0x88, 0xdc, 0x07, 0x4f, 0x1b, 0x36, 0x3f, 0x2a, 0x5a, 0xed, 0x02, 0x42, 0xa0,
	0x8a, 0x45, 0xb8, 0x0e, 0xe3, 0xb3, 0xc5, 0x16, 0x2a, 0xe5, 0xa1, 0xd7, 0xad, 0xf4, 0x5b, 0x14,
	0x9f, 0x7b, 0xff, 0x96, 0x00, 0x76, 0xb1, 0x13, 0x3f, 0x72, 0xc3, 0x6c, 0x85, 0x3c, 0x53, 0xf3,
	0xc5, 0xe5, 0xa0, 0xd5, 0x30, 0x1e, 0xe3, 0xb1, 0x26, 0x7c, 0x7e, 0x14, 0x69, 0x71, 0xce, 0x71,
	0xfb, 0x16, 0xad, 0x5b, 0x60, 0x2a, 0xce, 0x39, 0xf9, 0x12, 0xda, 0x48, 0x7e, 0x10, 0x92, 0xa5,
	0xe2, 0x9c, 0xbb, 0x83, 0xaf, 0xd3, 0x96, 0x45, 0xf7, 0x56, 0xa0, 0x7d, 0xbd, 0xdd, 0x35, 0xca,
	0x94, 0x0e, 0xab, 0x98, 0x45, 0xcd, 0xc6, 0x13, 0xa5, 0x6d, 0xb9, 0xf3, 0xe3, 0x5c, 0xab, 0x1c,
	0x8f, 0xbd, 0x45, 0x8b, 0x88, 0x3c, 0x05, 0xc8, 0xf9, 0x09, 0x67, 0x29, 0x2e, 0xf2, 0x91, 0x6b,
	0x38, 0xc4, 0x2e, 0xfb, 0x0a, 0xee, 0x16, 0x74, 0xc2, 0x59, 0x92, 0x0a, 0xc9, 0xf1, 0x7c, 0x2b,
	0xb4, 0xed, 0xe0, 0xdd, 0x02, 0xed, 0xfd, 0xee, 0x41, 0x75, 0xc4, 0x64, 0x42, 0x1e, 0x42, 0x6d,
	0xc1, 0x64, 0x72, 0x59, 0xa1, 0x6f, 0xc3, 0x71, 0x42, 0xbe, 0x01, 0x2f, 0x5b, 0x30, 0xed, 0x8a,
	0x6b, 0x6f, 0x77, 0x6f, 0x31, 0x91, 0x7d, 0xc9, 0xc4, 0xea, 0xa8, 0x93, 0x93, 0x57, 0xe0, 0x6b,
	0x93, 0x73, 0x6e, 0xb0, 0xe6, 0xf6, 0xf6, 0xd3, 0x5b, 0x16, 0x4e, 0x51, 0x44, 0x0b, 0xb1, 0x9d,
	0xb6, 0xf8, 0xd8, 0x18, 0x25, 0x23, 0xcd, 0x99, 0xc1, 0x83, 0xf2, 0x28, 0x38, 0x08, 0x07, 0xa0,
	0x0f, 0x9d, 0x2b, 0x46, 0x73, 0x2a, 0x0f, 0x55, 0xed, 0x4b, 0xb7, 0xa1, 0xf2, 0x0b, 0x68, 0x5f,
	0x38, 0xce, 0xe9, 0x7c, 0xd4, 0x35, 0x57, 0xb6, 0x43, 0xd5, 0x06, 0x34, 0x0a, 0xfb, 0x28, 0x89,
	0x4d, 0xf2, 0x68, 0xdd, 0x01, 0x07, 0x92, 0x3c, 0x00, 0x3f, 0xe6, 0x26, 0x32, 0xaa, 0x18, 0x7b,
	0x2f, 0xe6, 0x66, 0xa6, 0xec, 0x9b, 0xad, 0x5d, 0x73, 0x26, 0x34, 0x77, 0x27, 0xdf, 0x40, 0xba,
	0xb9, 0x14, 0x92, 0x5a, 0x10, 0x4f, 0x7f, 0x13, 0x02, 0x21, 0x0d, 0xcf, 0x4f, 0x58, 0x6a, 0xdb,
	0x0a, 0xce, 0x38, 0x2b, 0x68, 0x8c, 0x3d, 0x17, 0x32, 0xb2, 0x7d, 0x0e, 0x83, 0x6e, 0xa5, 0x5f,
	0xa7, 0xbe, 0x90, 0x78, 0x18, 0xeb, 0xe0, 0x7f, 0x50, 0x69, 0xc2, 0x93, 0xb0, 0xe9, 0x70, 0x17,
	0xd9, 0x74, 0x6c, 0xe5, 0x42, 0x86, 0x2d, 0xc4, 0x3d, 0x96, 0xa6, 0x63, 0x69, 0x0d, 0xe4, 0xba,
	0x17, 0xcd, 0xd5, 0x72, 0x29, 0x4c, 0xd8, 0xee, 0x56, 0x6c, 0x36, 0x0e, 0x7c, 0x8d, 0x18, 0x79,
	0x06, 0x4d, 0xa3, 0x0c, 0x4b, 0x57, 0x9a, 0xbb, 0xa8, 0x09, 0x10, 0x2b, 0x24, 0x5b, 0xb0, 0x96,
	0x32, 0x6d, 0xa2, 0x8b, 0xac, 0xd9, 0xdc, 0xf0, 0x24, 0xec, 0x74, 0x2b, 0x7d, 0x8f, 0xde, 0xb3,
	0xd4, 0xb8, 0x60, 0x76, 0x2c, 0x61, 0x3d, 0x16, 0x2b, 0x96, 0x27, 0xe1, 0x3d, 0x1c, 0x5a, 0x17,
	0xd8, 0xd9, 0x2b, 0x1a, 0x7a, 0x31, 0x7b, 0xc4, 0xcd, 0x9e, 0x83, 0x57, 0xb3, 0x47, 0xbe, 0x07,
	0xdf, 0xdd, 0x36, 0xe1, 0x5a, 0xb7, 0xd4, 0x0f, 0xb6, 0x9f, 0xdd, 0x32, 0x21, 0x97, 0x46, 0xc4,
	0x4b, 0xba, 0x44, 0x8b, 0x65, 0xbd, 0x3f, 0xca, 0xe0, 0xe1, 0x25, 0x6d, 0xdd, 0x7f, 0x31, 0xb8,
	0x65, 0x91, 0x90, 0x10, 0x6a, 0xf3, 0x9c, 0x33, 0xa3, 0x72, 0x1c, 0xdb, 0x06, 0x5d, 0x85, 0x36,
	0xe7, 0x94, 0xc5, 0x3c, 0xc5, 0xa9, 0x6c, 0x50, 0x17, 0x90, 0x1f, 0xc0, 0xcf, 0xf0, 0xa2, 0xc7,
	0x81, 0x0b, 0xb6, 0x7b, 0x9f, 0xfb, 0x54, 0xb8, 0x4f, 0xc2, 0xea, 0x83, 0xe1, 0xd6, 0x91, 0x6f,
	0xc1, 0xb3, 0x23, 0xa6, 0xf1, 0x1a, 0x09, 0xb6, 0x37, 0x6e, 0x9b, 0x76, 0xce, 0x4c, 0x51, 0x85,
	0xd3, 0x93, 0x2e, 0x34, 0xf1, 0x4b, 0xb6, 0x72, 0x9f, 0xbb, 0xb7, 0xc1, 0x62, 0x23, 0xe7, 0xc0,
	0x1b, 0x96, 0xa8, 0x7d, 0x64, 0x89, 0x57, 0x50, 0xc5, 0x21, 0xaa, 0x63, 0xee, 0x1b, 0x9f, 0x71,
	0x68, 0xb1, 0x35, 0xca, 0x9f, 0xff, 0x5d, 0x82, 0xc6, 0x85, 0x6d, 0xc9, 0x63, 0x58, 0x1f, 0xed,
	0xec, 0xef, 0x46, 0x93, 0xd1, 0xce, 0x74, 0x18, 0xbd, 0xdb, 0x9f, 0x4e, 0x86, 0xaf, 0xc7, 0x7b,
	0xe3, 0xe1, 0x6e, 0xe7, 0x0e, 0x59, 0x07, 0x72, 0x85, 0x9b, 0x8e, 0xde, 0xed, 0xed, 0xbd, 0x1d,
	0x76, 0x4a, 0x37, 0xf0, 0xc1, 0x70, 0x36, 0x1b, 0xef, 0xbf, 0xe9, 0x94, 0xc9, 0x23, 0x78, 0x70,
	0x05, 0xdf, 0x79, 0xbf, 0x33, 0x9e, 0x45, 0x7b, 0x6f, 0x0f, 0x26, 0x9d, 0xca, 0x27, 0xa9, 0xd9,
	0x3b, 0xba, 0xdf, 0xa9, 0xde, 0xc8, 0xc0, 0x51, 0x74, 0xfc, 0xd3, 0x90, 0x76, 0x3c, 0xf2, 0x14,
	0x1e, 0x7d, 0xc4, 0x4d, 0x47, 0x07, 0xef, 0x77, 0x0f, 0xde, 0xef, 0x77, 0x7c, 0xf2, 0x10, 0xd6,
	0xae, 0x25, 0x58, 0x10, 0xb5, 0xe7, 0x0b, 0xf0, 0xdd, 0x05, 0x63, 0x73, 0x9d, 0xce, 0xe8, 0x70,
	0x38, 0xbb, 0x51, 0x1b, 0x81, 0x76, 0x81, 0x4f, 0xe8, 0x10, 0x93, 0x2c, 0x91, 0xbb, 0x10, 0x14,
	0x18, 0x02, 0xe5, 0x2b, 0x00, 0xe6, 0x5a, 0x21, 0x1d, 0x68, 0x16, 0x80, 0xcb, 0xb0, 0x3a, 0x58,
	0xfb, 0xed, 0x9f, 0xff, 0x95, 0x7e, 0x6e, 0x9d, 0x16, 0x7f, 0x76, 0xcc, 0x59, 0xc6, 0x75, 0xec,
	0xe3, 0xbf, 0x97, 0xaf, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xe5, 0x40, 0x7e, 0xb7, 0x0f, 0x09,
	0x00, 0x00,
}

func (this *GenesisState) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GenesisState)
	if !ok {
		that2, ok := that.(GenesisState)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.NextTableId != that1.NextTableId {
		return false
	}
	if len(this.Tables) != len(that1.Tables) {
		return false
	}
	for i := range this.Tables {
		if !this.Tables[i].Equal(&that1.Tables[i]) {
			return false
		}
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *TableParams) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TableParams)
	if !ok {
		that2, ok := that.(TableParams)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.MaxPlayers != that1.MaxPlayers {
		return false
	}
	if this.SmallBlind != that1.SmallBlind {
		return false
	}
	if this.BigBlind != that1.BigBlind {
		return false
	}
	if this.MinBuyIn != that1.MinBuyIn {
		return false
	}
	if this.MaxBuyIn != that1.MaxBuyIn {
		return false
	}
	if this.ActionTimeoutSecs != that1.ActionTimeoutSecs {
		return false
	}
	if this.DealerTimeoutSecs != that1.DealerTimeoutSecs {
		return false
	}
	if this.PlayerBond != that1.PlayerBond {
		return false
	}
	if this.RakeBps != that1.RakeBps {
		return false
	}
	if !bytes.Equal(this.PasswordHash, that1.PasswordHash) {
		return false
	}
	if !bytes.Equal(this.PasswordSalt, that1.PasswordSalt) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *Seat) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Seat)
	if !ok {
		that2, ok := that.(Seat)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Player != that1.Player {
		return false
	}
	if !bytes.Equal(this.Pk, that1.Pk) {
		return false
	}
	if this.Stack != that1.Stack {
		return false
	}
	if this.Bond != that1.Bond {
		return false
	}
	if len(this.Hole) != len(that1.Hole) {
		return false
	}
	for i := range this.Hole {
		if this.Hole[i] != that1.Hole[i] {
			return false
		}
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *DealerMeta) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DealerMeta)
	if !ok {
		that2, ok := that.(DealerMeta)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.EpochId != that1.EpochId {
		return false
	}
	if this.DeckSize != that1.DeckSize {
		return false
	}
	if this.DeckFinalized != that1.DeckFinalized {
		return false
	}
	if len(this.HolePos) != len(that1.HolePos) {
		return false
	}
	for i := range this.HolePos {
		if this.HolePos[i] != that1.HolePos[i] {
			return false
		}
	}
	if this.Cursor != that1.Cursor {
		return false
	}
	if this.RevealPos != that1.RevealPos {
		return false
	}
	if this.RevealDeadline != that1.RevealDeadline {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *Hand) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Hand)
	if !ok {
		that2, ok := that.(Hand)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.HandId != that1.HandId {
		return false
	}
	if this.Phase != that1.Phase {
		return false
	}
	if this.Street != that1.Street {
		return false
	}
	if this.ButtonSeat != that1.ButtonSeat {
		return false
	}
	if this.SmallBlindSeat != that1.SmallBlindSeat {
		return false
	}
	if this.BigBlindSeat != that1.BigBlindSeat {
		return false
	}
	if this.ActionOn != that1.ActionOn {
		return false
	}
	if this.BetTo != that1.BetTo {
		return false
	}
	if this.MinRaiseSize != that1.MinRaiseSize {
		return false
	}
	if this.IntervalId != that1.IntervalId {
		return false
	}
	if len(this.InHand) != len(that1.InHand) {
		return false
	}
	for i := range this.InHand {
		if this.InHand[i] != that1.InHand[i] {
			return false
		}
	}
	if len(this.Folded) != len(that1.Folded) {
		return false
	}
	for i := range this.Folded {
		if this.Folded[i] != that1.Folded[i] {
			return false
		}
	}
	if len(this.AllIn) != len(that1.AllIn) {
		return false
	}
	for i := range this.AllIn {
		if this.AllIn[i] != that1.AllIn[i] {
			return false
		}
	}
	if len(this.StreetCommit) != len(that1.StreetCommit) {
		return false
	}
	for i := range this.StreetCommit {
		if this.StreetCommit[i] != that1.StreetCommit[i] {
			return false
		}
	}
	if len(this.TotalCommit) != len(that1.TotalCommit) {
		return false
	}
	for i := range this.TotalCommit {
		if this.TotalCommit[i] != that1.TotalCommit[i] {
			return false
		}
	}
	if len(this.LastIntervalActed) != len(that1.LastIntervalActed) {
		return false
	}
	for i := range this.LastIntervalActed {
		if this.LastIntervalActed[i] != that1.LastIntervalActed[i] {
			return false
		}
	}
	if len(this.Board) != len(that1.Board) {
		return false
	}
	for i := range this.Board {
		if this.Board[i] != that1.Board[i] {
			return false
		}
	}
	if this.ActionDeadline != that1.ActionDeadline {
		return false
	}
	if !this.Dealer.Equal(that1.Dealer) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *Table) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Table)
	if !ok {
		that2, ok := that.(Table)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Id != that1.Id {
		return false
	}
	if this.Creator != that1.Creator {
		return false
	}
	if this.Label != that1.Label {
		return false
	}
	if !this.Params.Equal(&that1.Params) {
		return false
	}
	if len(this.Seats) != len(that1.Seats) {
		return false
	}
	for i := range this.Seats {
		if !this.Seats[i].Equal(that1.Seats[i]) {
			return false
		}
	}
	if this.NextHandId != that1.NextHandId {
		return false
	}
	if this.ButtonSeat != that1.ButtonSeat {
		return false
	}
	if !this.Hand.Equal(that1.Hand) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
