// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: onchainpoker/poker/v1/query.proto

package types

import (
	bytes "bytes"
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryTableRequest struct {
	TableId              uint64   `protobuf:"varint,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryTableRequest) Reset()         { *m = QueryTableRequest{} }
func (m *QueryTableRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTableRequest) ProtoMessage()    {}
func (*QueryTableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_44ea09907992f8ca, []int{0}
}
func (m *QueryTableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryTableRequest.Unmarshal(m, b)
}
func (m *QueryTableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryTableRequest.Marshal(b, m, deterministic)
}
func (m *QueryTableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTableRequest.Merge(m, src)
}
func (m *QueryTableRequest) XXX_Size() int {
	return xxx_messageInfo_QueryTableRequest.Size(m)
}
func (m *QueryTableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTableRequest proto.InternalMessageInfo

func (m *QueryTableRequest) GetTableId() uint64 {
	if m != nil {
		return m.TableId
	}
	return 0
}

type QueryTableResponse struct {
	Table                Table    `protobuf:"bytes,1,opt,name=table,proto3" json:"table"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryTableResponse) Reset()         { *m = QueryTableResponse{} }
func (m *QueryTableResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTableResponse) ProtoMessage()    {}
func (*QueryTableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_44ea09907992f8ca, []int{1}
}
func (m *QueryTableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryTableResponse.Unmarshal(m, b)
}
func (m *QueryTableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryTableResponse.Marshal(b, m, deterministic)
}
func (m *QueryTableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTableResponse.Merge(m, src)
}
func (m *QueryTableResponse) XXX_Size() int {
	return xxx_messageInfo_QueryTableResponse.Size(m)
}
func (m *QueryTableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTableResponse proto.InternalMessageInfo

func (m *QueryTableResponse) GetTable() Table {
	if m != nil {
		return m.Table
	}
	return Table{}
}

type QueryTablesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryTablesRequest) Reset()         { *m = QueryTablesRequest{} }
func (m *QueryTablesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTablesRequest) ProtoMessage()    {}
func (*QueryTablesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_44ea09907992f8ca, []int{2}
}
func (m *QueryTablesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryTablesRequest.Unmarshal(m, b)
}
func (m *QueryTablesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryTablesRequest.Marshal(b, m, deterministic)
}
func (m *QueryTablesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTablesRequest.Merge(m, src)
}
func (m *QueryTablesRequest) XXX_Size() int {
	return xxx_messageInfo_QueryTablesRequest.Size(m)
}
func (m *QueryTablesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTablesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTablesRequest proto.InternalMessageInfo

type QueryTablesResponse struct {
	TableIds             []uint64 `protobuf:"varint,1,rep,packed,name=table_ids,json=tableIds,proto3" json:"table_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryTablesResponse) Reset()         { *m = QueryTablesResponse{} }
func (m *QueryTablesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTablesResponse) ProtoMessage()    {}
func (*QueryTablesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_44ea09907992f8ca, []int{3}
}
func (m *QueryTablesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryTablesResponse.Unmarshal(m, b)
}
func (m *QueryTablesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryTablesResponse.Marshal(b, m, deterministic)
}
func (m *QueryTablesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTablesResponse.Merge(m, src)
}
func (m *QueryTablesResponse) XXX_Size() int {
	return xxx_messageInfo_QueryTablesResponse.Size(m)
}
func (m *QueryTablesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTablesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTablesResponse proto.InternalMessageInfo

func (m *QueryTablesResponse) GetTableIds() []uint64 {
	if m != nil {
		return m.TableIds
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryTableRequest)(nil), "onchainpoker.poker.v1.QueryTableRequest")
	proto.RegisterType((*QueryTableResponse)(nil), "onchainpoker.poker.v1.QueryTableResponse")
	proto.RegisterType((*QueryTablesRequest)(nil), "onchainpoker.poker.v1.QueryTablesRequest")
	proto.RegisterType((*QueryTablesResponse)(nil), "onchainpoker.poker.v1.QueryTablesResponse")
}

func init() { proto.RegisterFile("onchainpoker/poker/v1/query.proto", fileDescriptor_44ea09907992f8ca) }

var fileDescriptor_44ea09907992f8ca = []byte{
	// 334 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0xcc, 0xcf, 0x4b, 0xce,
	0x48, 0xcc, 0xcc, 0x2b, 0xc8, 0xcf, 0x4e, 0x2d, 0xd2, 0x87, 0x90, 0x65, 0x86, 0xfa, 0x85, 0xa5,
	0xa9, 0x45, 0x95, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xa2, 0xc8, 0x4a, 0xf4, 0x20, 0x64,
	0x99, 0xa1, 0x94, 0x48, 0x7a, 0x7e, 0x7a, 0x3e, 0x58, 0x85, 0x3e, 0x88, 0x05, 0x51, 0x2c, 0x25,
	0x9d, 0x9c, 0x5f, 0x9c, 0x9b, 0x5f, 0x0c, 0x31, 0x00, 0xcd, 0x24, 0x29, 0x99, 0xf4, 0xfc, 0xfc,
	0xf4, 0x9c, 0x54, 0xfd, 0xc4, 0x82, 0x4c, 0xfd, 0xc4, 0xbc, 0xbc, 0xfc, 0x92, 0xc4, 0x92, 0xcc,
	0xfc, 0xbc, 0x62, 0xa8, 0x2c, 0x0e, 0xa7, 0x40, 0xad, 0x05, 0x29, 0x51, 0xd2, 0xe3, 0x12, 0x0c,
	0x04, 0x99, 0x17, 0x92, 0x98, 0x94, 0x93, 0x1a, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x22, 0x24,
	0xc9, 0xc5, 0x51, 0x02, 0xe2, 0xc7, 0x67, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x04, 0xb1,
	0x83, 0xf9, 0x9e, 0x29, 0x4a, 0x7e, 0x5c, 0x42, 0xc8, 0xea, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53,
	0x85, 0x2c, 0xb8, 0x58, 0xc1, 0x0a, 0xc0, 0xaa, 0xb9, 0x8d, 0x64, 0xf4, 0xb0, 0x7a, 0x50, 0x0f,
	0xac, 0xc9, 0x89, 0xe5, 0xc4, 0x3d, 0x79, 0x86, 0x20, 0x88, 0x06, 0x25, 0x11, 0x64, 0xf3, 0x8a,
	0xa1, 0x0e, 0x50, 0x32, 0xe2, 0x12, 0x46, 0x11, 0x85, 0x5a, 0x23, 0xcd, 0xc5, 0x09, 0x73, 0x57,
	0xb1, 0x04, 0xa3, 0x02, 0xb3, 0x06, 0x4b, 0x10, 0x07, 0xd4, 0x61, 0xc5, 0x46, 0x0b, 0x99, 0xb8,
	0x58, 0xc1, 0x9a, 0x84, 0xfa, 0x18, 0xb9, 0x58, 0xc1, 0x3a, 0x85, 0x34, 0x70, 0x38, 0x04, 0xc3,
	0xcb, 0x52, 0x9a, 0x44, 0xa8, 0x84, 0xb8, 0x42, 0xc9, 0xa0, 0xe9, 0xf2, 0x93, 0xc9, 0x4c, 0x5a,
	0x42, 0x1a, 0xfa, 0xd8, 0x83, 0x17, 0xec, 0xa2, 0x62, 0xfd, 0x6a, 0x98, 0x53, 0x6b, 0x85, 0xda,
	0x18, 0xb9, 0xd8, 0x20, 0x5e, 0x11, 0x22, 0x6c, 0x0f, 0x2c, 0x10, 0xa4, 0xb4, 0x88, 0x51, 0x0a,
	0x75, 0x93, 0x2a, 0xd8, 0x4d, 0xf2, 0x42, 0xb2, 0x78, 0xdd, 0xe4, 0x24, 0xbc, 0xe2, 0x91, 0x1c,
	0x63, 0x14, 0x6f, 0x05, 0x54, 0xa2, 0xa4, 0xb2, 0x20, 0xb5, 0x38, 0x89, 0x0d, 0x9c, 0x12, 0x8c,
	0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd2, 0xee, 0x7a, 0x5c, 0xb9, 0x02, 0x00, 0x00,
}

func (this *QueryTableRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*QueryTableRequest)
	if !ok {
		that2, ok := that.(QueryTableRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.TableId != that1.TableId {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *QueryTableResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*QueryTableResponse)
	if !ok {
		that2, ok := that.(QueryTableResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Table.Equal(&that1.Table) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *QueryTablesRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*QueryTablesRequest)
	if !ok {
		that2, ok := that.(QueryTablesRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *QueryTablesResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*QueryTablesResponse)
	if !ok {
		that2, ok := that.(QueryTablesResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.TableIds) != len(that1.TableIds) {
		return false
	}
	for i := range this.TableIds {
		if this.TableIds[i] != that1.TableIds[i] {
			return false
		}
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	Table(ctx context.Context, in *QueryTableRequest, opts ...grpc.CallOption) (*QueryTableResponse, error)
	Tables(ctx context.Context, in *QueryTablesRequest, opts ...grpc.CallOption) (*QueryTablesResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Table(ctx context.Context, in *QueryTableRequest, opts ...grpc.CallOption) (*QueryTableResponse, error) {
	out := new(QueryTableResponse)
	err := c.cc.Invoke(ctx, "/onchainpoker.poker.v1.Query/Table", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Tables(ctx context.Context, in *QueryTablesRequest, opts ...grpc.CallOption) (*QueryTablesResponse, error) {
	out := new(QueryTablesResponse)
	err := c.cc.Invoke(ctx, "/onchainpoker.poker.v1.Query/Tables", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	Table(context.Context, *QueryTableRequest) (*QueryTableResponse, error)
	Tables(context.Context, *QueryTablesRequest) (*QueryTablesResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Table(ctx context.Context, req *QueryTableRequest) (*QueryTableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Table not implemented")
}
func (*UnimplementedQueryServer) Tables(ctx context.Context, req *QueryTablesRequest) (*QueryTablesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Tables not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Table_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Table(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onchainpoker.poker.v1.Query/Table",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Table(ctx, req.(*QueryTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Tables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Tables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onchainpoker.poker.v1.Query/Tables",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Tables(ctx, req.(*QueryTablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "onchainpoker.poker.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Table",
			Handler:    _Query_Table_Handler,
		},
		{
			MethodName: "Tables",
			Handler:    _Query_Tables_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "onchainpoker/poker/v1/query.proto",
}
