// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: onchainpoker/poker/v1/tx.proto

package types

import (
	bytes "bytes"
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreateTable struct {
	Creator              string   `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	SmallBlind           uint64   `protobuf:"varint,2,opt,name=small_blind,json=smallBlind,proto3" json:"small_blind,omitempty"`
	BigBlind             uint64   `protobuf:"varint,3,opt,name=big_blind,json=bigBlind,proto3" json:"big_blind,omitempty"`
	MinBuyIn             uint64   `protobuf:"varint,4,opt,name=min_buy_in,json=minBuyIn,proto3" json:"min_buy_in,omitempty"`
	MaxBuyIn             uint64   `protobuf:"varint,5,opt,name=max_buy_in,json=maxBuyIn,proto3" json:"max_buy_in,omitempty"`
	ActionTimeoutSecs    uint64   `protobuf:"varint,6,opt,name=action_timeout_secs,json=actionTimeoutSecs,proto3" json:"action_timeout_secs,omitempty"`
	DealerTimeoutSecs    uint64   `protobuf:"varint,7,opt,name=dealer_timeout_secs,json=dealerTimeoutSecs,proto3" json:"dealer_timeout_secs,omitempty"`
	PlayerBond           uint64   `protobuf:"varint,8,opt,name=player_bond,json=playerBond,proto3" json:"player_bond,omitempty"`
	RakeBps              uint32   `protobuf:"varint,9,opt,name=rake_bps,json=rakeBps,proto3" json:"rake_bps,omitempty"`
	MaxPlayers           uint32   `protobuf:"varint,10,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	Label                string   `protobuf:"bytes,11,opt,name=label,proto3" json:"label,omitempty"`
	Password             string   `protobuf:"bytes,12,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgCreateTable) Reset()         { *m = MsgCreateTable{} }
func (m *MsgCreateTable) String() string { return proto.CompactTextString(m) }
func (*MsgCreateTable) ProtoMessage()    {}
func (*MsgCreateTable) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f98834a333fcdff, []int{0}
}
func (m *MsgCreateTable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCreateTable.Unmarshal(m, b)
}
func (m *MsgCreateTable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCreateTable.Marshal(b, m, deterministic)
}
func (m *MsgCreateTable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateTable.Merge(m, src)
}
func (m *MsgCreateTable) XXX_Size() int {
	return xxx_messageInfo_MsgCreateTable.Size(m)
}
func (m *MsgCreateTable) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateTable.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateTable proto.InternalMessageInfo

type MsgCreateTableResponse struct {
	TableId              uint64   `protobuf:"varint,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgCreateTableResponse) Reset()         { *m = MsgCreateTableResponse{} }
func (m *MsgCreateTableResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateTableResponse) ProtoMessage()    {}
func (*MsgCreateTableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f98834a333fcdff, []int{1}
}
func (m *MsgCreateTableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCreateTableResponse.Unmarshal(m, b)
}
func (m *MsgCreateTableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCreateTableResponse.Marshal(b, m, deterministic)
}
func (m *MsgCreateTableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateTableResponse.Merge(m, src)
}
func (m *MsgCreateTableResponse) XXX_Size() int {
	return xxx_messageInfo_MsgCreateTableResponse.Size(m)
}
func (m *MsgCreateTableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateTableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateTableResponse proto.InternalMessageInfo

func (m *MsgCreateTableResponse) GetTableId() uint64 {
	if m != nil {
		return m.TableId
	}
	return 0
}

type MsgSit struct {
	Player  string `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	TableId uint64 `protobuf:"varint,2,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	// field 3 removed (was seat, now auto-assigned)
	BuyIn                uint64   `protobuf:"varint,4,opt,name=buy_in,json=buyIn,proto3" json:"buy_in,omitempty"`
	PkPlayer             []byte   `protobuf:"bytes,5,opt,name=pk_player,json=pkPlayer,proto3" json:"pk_player,omitempty"`
	Password             string   `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgSit) Reset()         { *m = MsgSit{} }
func (m *MsgSit) String() string { return proto.CompactTextString(m) }
func (*MsgSit) ProtoMessage()    {}
func (*MsgSit) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f98834a333fcdff, []int{2}
}
func (m *MsgSit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgSit.Unmarshal(m, b)
}
func (m *MsgSit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgSit.Marshal(b, m, deterministic)
}
func (m *MsgSit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSit.Merge(m, src)
}
func (m *MsgSit) XXX_Size() int {
	return xxx_messageInfo_MsgSit.Size(m)
}
func (m *MsgSit) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSit.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSit proto.InternalMessageInfo

type MsgSitResponse struct {
	Seat                 uint32   `protobuf:"varint,1,opt,name=seat,proto3" json:"seat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgSitResponse) Reset()         { *m = MsgSitResponse{} }
func (m *MsgSitResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSitResponse) ProtoMessage()    {}
func (*MsgSitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f98834a333fcdff, []int{3}
}
func (m *MsgSitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgSitResponse.Unmarshal(m, b)
}
func (m *MsgSitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgSitResponse.Marshal(b, m, deterministic)
}
func (m *MsgSitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSitResponse.Merge(m, src)
}
func (m *MsgSitResponse) XXX_Size() int {
	return xxx_messageInfo_MsgSitResponse.Size(m)
}
func (m *MsgSitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSitResponse proto.InternalMessageInfo

func (m *MsgSitResponse) GetSeat() uint32 {
	if m != nil {
		return m.Seat
	}
	return 0
}

type MsgStartHand struct {
	Caller               string   `protobuf:"bytes,1,opt,name=caller,proto3" json:"caller,omitempty"`
	TableId              uint64   `protobuf:"varint,2,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgStartHand) Reset()         { *m = MsgStartHand{} }
func (m *MsgStartHand) String() string { return proto.CompactTextString(m) }
func (*MsgStartHand) ProtoMessage()    {}
func (*MsgStartHand) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f98834a333fcdff, []int{4}
}
func (m *MsgStartHand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgStartHand.Unmarshal(m, b)
}
func (m *MsgStartHand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgStartHand.Marshal(b, m, deterministic)
}
func (m *MsgStartHand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgStartHand.Merge(m, src)
}
func (m *MsgStartHand) XXX_Size() int {
	return xxx_messageInfo_MsgStartHand.Size(m)
}
func (m *MsgStartHand) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgStartHand.DiscardUnknown(m)
}

var xxx_messageInfo_MsgStartHand proto.InternalMessageInfo

type MsgStartHandResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgStartHandResponse) Reset()         { *m = MsgStartHandResponse{} }
func (m *MsgStartHandResponse) String() string { return proto.CompactTextString(m) }
func (*MsgStartHandResponse) ProtoMessage()    {}
func (*MsgStartHandResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f98834a333fcdff, []int{5}
}
func (m *MsgStartHandResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgStartHandResponse.Unmarshal(m, b)
}
func (m *MsgStartHandResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgStartHandResponse.Marshal(b, m, deterministic)
}
func (m *MsgStartHandResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgStartHandResponse.Merge(m, src)
}
func (m *MsgStartHandResponse) XXX_Size() int {
	return xxx_messageInfo_MsgStartHandResponse.Size(m)
}
func (m *MsgStartHandResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgStartHandResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgStartHandResponse proto.InternalMessageInfo

type MsgAct struct {
	Player  string `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	TableId uint64 `protobuf:"varint,2,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	// fold|check|call|bet|raise
	Action string `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	// For bet/raise: desired total street commitment ("BetTo").
	Amount               uint64   `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgAct) Reset()         { *m = MsgAct{} }
func (m *MsgAct) String() string { return proto.CompactTextString(m) }
func (*MsgAct) ProtoMessage()    {}
func (*MsgAct) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f98834a333fcdff, []int{6}
}
func (m *MsgAct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgAct.Unmarshal(m, b)
}
func (m *MsgAct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgAct.Marshal(b, m, deterministic)
}
func (m *MsgAct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAct.Merge(m, src)
}
func (m *MsgAct) XXX_Size() int {
	return xxx_messageInfo_MsgAct.Size(m)
}
func (m *MsgAct) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAct.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAct proto.InternalMessageInfo

type MsgActResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgActResponse) Reset()         { *m = MsgActResponse{} }
func (m *MsgActResponse) String() string { return proto.CompactTextString(m) }
func (*MsgActResponse) ProtoMessage()    {}
func (*MsgActResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f98834a333fcdff, []int{7}
}
func (m *MsgActResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgActResponse.Unmarshal(m, b)
}
func (m *MsgActResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgActResponse.Marshal(b, m, deterministic)
}
func (m *MsgActResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgActResponse.Merge(m, src)
}
func (m *MsgActResponse) XXX_Size() int {
	return xxx_messageInfo_MsgActResponse.Size(m)
}
func (m *MsgActResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgActResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgActResponse proto.InternalMessageInfo

type MsgTick struct {
	Caller               string   `protobuf:"bytes,1,opt,name=caller,proto3" json:"caller,omitempty"`
	TableId              uint64   `protobuf:"varint,2,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgTick) Reset()         { *m = MsgTick{} }
func (m *MsgTick) String() string { return proto.CompactTextString(m) }
func (*MsgTick) ProtoMessage()    {}
func (*MsgTick) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f98834a333fcdff, []int{8}
}
func (m *MsgTick) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgTick.Unmarshal(m, b)
}
func (m *MsgTick) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgTick.Marshal(b, m, deterministic)
}
func (m *MsgTick) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTick.Merge(m, src)
}
func (m *MsgTick) XXX_Size() int {
	return xxx_messageInfo_MsgTick.Size(m)
}
func (m *MsgTick) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTick.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTick proto.InternalMessageInfo

type MsgTickResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgTickResponse) Reset()         { *m = MsgTickResponse{} }
func (m *MsgTickResponse) String() string { return proto.CompactTextString(m) }
func (*MsgTickResponse) ProtoMessage()    {}
func (*MsgTickResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f98834a333fcdff, []int{9}
}
func (m *MsgTickResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgTickResponse.Unmarshal(m, b)
}
func (m *MsgTickResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgTickResponse.Marshal(b, m, deterministic)
}
func (m *MsgTickResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTickResponse.Merge(m, src)
}
func (m *MsgTickResponse) XXX_Size() int {
	return xxx_messageInfo_MsgTickResponse.Size(m)
}
func (m *MsgTickResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTickResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTickResponse proto.InternalMessageInfo

type MsgLeave struct {
	Player               string   `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	TableId              uint64   `protobuf:"varint,2,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgLeave) Reset()         { *m = MsgLeave{} }
func (m *MsgLeave) String() string { return proto.CompactTextString(m) }
func (*MsgLeave) ProtoMessage()    {}
func (*MsgLeave) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f98834a333fcdff, []int{10}
}
func (m *MsgLeave) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgLeave.Unmarshal(m, b)
}
func (m *MsgLeave) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgLeave.Marshal(b, m, deterministic)
}
func (m *MsgLeave) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLeave.Merge(m, src)
}
func (m *MsgLeave) XXX_Size() int {
	return xxx_messageInfo_MsgLeave.Size(m)
}
func (m *MsgLeave) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLeave.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLeave proto.InternalMessageInfo

type MsgLeaveResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgLeaveResponse) Reset()         { *m = MsgLeaveResponse{} }
func (m *MsgLeaveResponse) String() string { return proto.CompactTextString(m) }
func (*MsgLeaveResponse) ProtoMessage()    {}
func (*MsgLeaveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f98834a333fcdff, []int{11}
}
func (m *MsgLeaveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgLeaveResponse.Unmarshal(m, b)
}
func (m *MsgLeaveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgLeaveResponse.Marshal(b, m, deterministic)
}
func (m *MsgLeaveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLeaveResponse.Merge(m, src)
}
func (m *MsgLeaveResponse) XXX_Size() int {
	return xxx_messageInfo_MsgLeaveResponse.Size(m)
}
func (m *MsgLeaveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLeaveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLeaveResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateTable)(nil), "onchainpoker.poker.v1.MsgCreateTable")
	proto.RegisterType((*MsgCreateTableResponse)(nil), "onchainpoker.poker.v1.MsgCreateTableResponse")
	proto.RegisterType((*MsgSit)(nil), "onchainpoker.poker.v1.MsgSit")
	proto.RegisterType((*MsgSitResponse)(nil), "onchainpoker.poker.v1.MsgSitResponse")
	proto.RegisterType((*MsgStartHand)(nil), "onchainpoker.poker.v1.MsgStartHand")
	proto.RegisterType((*MsgStartHandResponse)(nil), "onchainpoker.poker.v1.MsgStartHandResponse")
	proto.RegisterType((*MsgAct)(nil), "onchainpoker.poker.v1.MsgAct")
	proto.RegisterType((*MsgActResponse)(nil), "onchainpoker.poker.v1.MsgActResponse")
	proto.RegisterType((*MsgTick)(nil), "onchainpoker.poker.v1.MsgTick")
	proto.RegisterType((*MsgTickResponse)(nil), "onchainpoker.poker.v1.MsgTickResponse")
	proto.RegisterType((*MsgLeave)(nil), "onchainpoker.poker.v1.MsgLeave")
	proto.RegisterType((*MsgLeaveResponse)(nil), "onchainpoker.poker.v1.MsgLeaveResponse")
}

func init() { proto.RegisterFile("onchainpoker/poker/v1/tx.proto", fileDescriptor_6f98834a333fcdff) }

var fileDescriptor_6f98834a333fcdff = []byte{
	// 738 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0x3f, 0x6f, 0xd3, 0x4e,
	0x18, 0xfe, 0xa5, 0xf9, 0xff, 0xa6, 0xfd, 0xb5, 0x75, 0xd3, 0xe2, 0xba, 0xd0, 0x54, 0x86, 0x42,
	0x55, 0xd4, 0x84, 0xb6, 0x1b, 0x5b, 0xc2, 0x42, 0x05, 0x41, 0xe0, 0x74, 0x42, 0x42, 0xd6, 0xd9,
	0x3e, 0xb9, 0xa7, 0xd8, 0x3e, 0xcb, 0x77, 0x29, 0xc9, 0x86, 0x98, 0x58, 0x58, 0x99, 0x19, 0x19,
	0x3b, 0x20, 0x56, 0xbe, 0x03, 0x1f, 0x81, 0xa5, 0x5f, 0x03, 0xdd, 0x9d, 0x1d, 0x12, 0x4a, 0xd3,
	0x0e, 0x65, 0xb1, 0xfc, 0xde, 0xf3, 0xbc, 0xff, 0x9e, 0xf7, 0x3d, 0x1b, 0x36, 0x69, 0xe4, 0x9e,
	0x20, 0x12, 0xc5, 0xb4, 0x8f, 0x93, 0x96, 0x7a, 0x9e, 0xee, 0xb7, 0xf8, 0xb0, 0x19, 0x27, 0x94,
	0x53, 0x6d, 0x75, 0x12, 0x6f, 0xaa, 0xe7, 0xe9, 0xbe, 0x51, 0xf7, 0xa9, 0x4f, 0x25, 0xa3, 0x25,
	0xde, 0x14, 0xd9, 0xb8, 0xe5, 0x52, 0x16, 0x52, 0xd6, 0x0a, 0x99, 0x2f, 0x82, 0x84, 0xcc, 0x4f,
	0x81, 0x75, 0x05, 0xd8, 0xca, 0x43, 0x19, 0x0a, 0x32, 0xbf, 0xe7, 0xe1, 0xff, 0x2e, 0xf3, 0x9f,
	0x24, 0x18, 0x71, 0x7c, 0x8c, 0x9c, 0x00, 0x6b, 0x07, 0x50, 0x76, 0x85, 0x49, 0x13, 0x3d, 0xb7,
	0x95, 0xdb, 0xa9, 0x76, 0xf4, 0x1f, 0x5f, 0xf7, 0xea, 0xa9, 0x57, 0xdb, 0xf3, 0x12, 0xcc, 0x58,
	0x8f, 0x27, 0x24, 0xf2, 0xad, 0x8c, 0xa8, 0x35, 0xa0, 0xc6, 0x42, 0x14, 0x04, 0xb6, 0x13, 0x90,
	0xc8, 0xd3, 0xe7, 0xb6, 0x72, 0x3b, 0x05, 0x0b, 0xe4, 0x51, 0x47, 0x9c, 0x68, 0x1b, 0x50, 0x75,
	0x88, 0x9f, 0xc2, 0x79, 0x09, 0x57, 0x1c, 0xe2, 0x2b, 0xf0, 0x36, 0x40, 0x48, 0x22, 0xdb, 0x19,
	0x8c, 0x6c, 0x12, 0xe9, 0x05, 0x85, 0x86, 0x24, 0xea, 0x0c, 0x46, 0x47, 0x91, 0x44, 0xd1, 0x30,
	0x43, 0x8b, 0x29, 0x8a, 0x86, 0x0a, 0x6d, 0xc2, 0x0a, 0x72, 0x39, 0xa1, 0x91, 0xcd, 0x49, 0x88,
	0xe9, 0x80, 0xdb, 0x0c, 0xbb, 0x4c, 0x2f, 0x49, 0xda, 0xb2, 0x82, 0x8e, 0x15, 0xd2, 0xc3, 0x2e,
	0x13, 0x7c, 0x0f, 0xa3, 0x00, 0x27, 0xd3, 0xfc, 0xb2, 0xe2, 0x2b, 0x68, 0x92, 0xdf, 0x80, 0x5a,
	0x1c, 0xa0, 0x11, 0x4e, 0x6c, 0x87, 0x46, 0x9e, 0x5e, 0x51, 0x9d, 0xa9, 0xa3, 0x0e, 0x8d, 0x3c,
	0x6d, 0x1d, 0x2a, 0x09, 0xea, 0x63, 0xdb, 0x89, 0x99, 0x5e, 0xdd, 0xca, 0xed, 0x2c, 0x58, 0x65,
	0x61, 0x77, 0x62, 0xe9, 0x2b, 0x2a, 0x57, 0x64, 0xa6, 0x83, 0x44, 0x45, 0x33, 0x2f, 0xd5, 0x89,
	0x56, 0x87, 0x62, 0x80, 0x1c, 0x1c, 0xe8, 0x35, 0x21, 0xb4, 0xa5, 0x0c, 0xcd, 0x80, 0x4a, 0x8c,
	0x18, 0x7b, 0x4b, 0x13, 0x4f, 0x9f, 0x97, 0xc0, 0xd8, 0x7e, 0xbc, 0xf4, 0xe1, 0x73, 0xe3, 0xbf,
	0xf7, 0xe7, 0x67, 0xbb, 0x99, 0xf4, 0xe6, 0x21, 0xac, 0x4d, 0x0f, 0xd0, 0xc2, 0x2c, 0xa6, 0x11,
	0xc3, 0xa2, 0x32, 0x2e, 0x0e, 0x6c, 0xe2, 0xc9, 0x49, 0x16, 0xac, 0xb2, 0xb4, 0x8f, 0x3c, 0xf3,
	0x5b, 0x0e, 0x4a, 0x5d, 0xe6, 0xf7, 0x08, 0xd7, 0x1e, 0x41, 0x49, 0x15, 0x78, 0xe5, 0xb4, 0x53,
	0xde, 0x54, 0xdc, 0xb9, 0xa9, 0xb8, 0xda, 0x2a, 0x94, 0xa6, 0xa6, 0x58, 0x74, 0xe4, 0x90, 0x36,
	0xa0, 0x1a, 0xf7, 0x53, 0x1d, 0xe4, 0x04, 0xe7, 0xad, 0x4a, 0xdc, 0x57, 0x2a, 0x4c, 0xb5, 0x5b,
	0xfa, 0xa3, 0xdd, 0xc5, 0xac, 0xdd, 0x34, 0xb7, 0x79, 0x4f, 0xae, 0x6b, 0x8f, 0xf0, 0x71, 0x97,
	0x1a, 0x14, 0x18, 0x46, 0x5c, 0x56, 0xbf, 0x60, 0xc9, 0x77, 0x33, 0x80, 0x79, 0xc1, 0xe2, 0x28,
	0xe1, 0x4f, 0x51, 0xe4, 0x89, 0x1e, 0x5d, 0x14, 0x04, 0xd7, 0xe9, 0x51, 0xf1, 0x66, 0xf4, 0x38,
	0x51, 0x93, 0xe2, 0x9a, 0x6b, 0x50, 0x9f, 0xcc, 0x96, 0x55, 0x66, 0x7e, 0x52, 0x22, 0xb7, 0xdd,
	0x1b, 0x16, 0x79, 0x0d, 0x4a, 0x6a, 0xaf, 0xe5, 0x45, 0xaa, 0x5a, 0xa9, 0x25, 0xcf, 0x43, 0x3a,
	0x88, 0x78, 0x2a, 0x7e, 0x6a, 0x5d, 0x14, 0x71, 0x49, 0x8a, 0xd8, 0x76, 0xc7, 0x22, 0x9a, 0x3e,
	0x94, 0xbb, 0xcc, 0x3f, 0x26, 0x6e, 0xff, 0x1f, 0x6b, 0xb5, 0x0c, 0x8b, 0x69, 0xa2, 0x71, 0xee,
	0x13, 0xa8, 0x74, 0x99, 0xff, 0x1c, 0xa3, 0x53, 0x7c, 0xa3, 0x3a, 0x5d, 0xec, 0x5b, 0x83, 0xa5,
	0x2c, 0x53, 0x96, 0xfd, 0xe0, 0x63, 0x01, 0xf2, 0x5d, 0xe6, 0x6b, 0x2e, 0xd4, 0x26, 0x3f, 0x82,
	0xdb, 0xcd, 0xbf, 0x7e, 0x79, 0x9b, 0xd3, 0x57, 0xcd, 0xd8, 0xbb, 0x16, 0x6d, 0xbc, 0xab, 0xcf,
	0x20, 0x2f, 0xae, 0xdc, 0x9d, 0xcb, 0xbd, 0x7a, 0x84, 0x1b, 0xdb, 0x33, 0xe1, 0x71, 0xb0, 0x37,
	0x50, 0xfd, 0xbd, 0xe1, 0x77, 0x67, 0xf8, 0x64, 0x24, 0xe3, 0xe1, 0x35, 0x48, 0x93, 0xb5, 0x8a,
	0xcd, 0x9d, 0x51, 0x6b, 0xdb, 0x9d, 0x59, 0xeb, 0xc4, 0x7e, 0x69, 0x2f, 0xa0, 0x20, 0x97, 0x6b,
	0xf3, 0x72, 0xba, 0xc0, 0x8d, 0xfb, 0xb3, 0xf1, 0x71, 0xbc, 0x57, 0x50, 0x54, 0x0b, 0xd3, 0xb8,
	0xdc, 0x41, 0x12, 0x8c, 0x07, 0x57, 0x10, 0xb2, 0x90, 0x46, 0xf1, 0xdd, 0xf9, 0xd9, 0x6e, 0xae,
	0xb3, 0xf2, 0xe5, 0xe7, 0x66, 0xee, 0xf5, 0xc2, 0x30, 0xfd, 0x19, 0xf3, 0x51, 0x8c, 0x99, 0x53,
	0x92, 0x3f, 0xcb, 0xc3, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xea, 0xac, 0x3f, 0xb6, 0xaf, 0x07,
	0x00, 0x00,
}

func (this *MsgCreateTable) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MsgCreateTable)
	if !ok {
		that2, ok := that.(MsgCreateTable)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Creator != that1.Creator {
		return false
	}
	if this.SmallBlind != that1.SmallBlind {
		return false
	}
	if this.BigBlind != that1.BigBlind {
		return false
	}
	if this.MinBuyIn != that1.MinBuyIn {
		return false
	}
	if this.MaxBuyIn != that1.MaxBuyIn {
		return false
	}
	if this.ActionTimeoutSecs != that1.ActionTimeoutSecs {
		return false
	}
	if this.DealerTimeoutSecs != that1.DealerTimeoutSecs {
		return false
	}
	if this.PlayerBond != that1.PlayerBond {
		return false
	}
	if this.RakeBps != that1.RakeBps {
		return false
	}
	if this.MaxPlayers != that1.MaxPlayers {
		return false
	}
	if this.Label != that1.Label {
		return false
	}
	if this.Password != that1.Password {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *MsgCreateTableResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MsgCreateTableResponse)
	if !ok {
		that2, ok := that.(MsgCreateTableResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.TableId != that1.TableId {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *MsgSit) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MsgSit)
	if !ok {
		that2, ok := that.(MsgSit)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Player != that1.Player {
		return false
	}
	if this.TableId != that1.TableId {
		return false
	}
	if this.BuyIn != that1.BuyIn {
		return false
	}
	if !bytes.Equal(this.PkPlayer, that1.PkPlayer) {
		return false
	}
	if this.Password != that1.Password {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *MsgSitResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MsgSitResponse)
	if !ok {
		that2, ok := that.(MsgSitResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Seat != that1.Seat {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *MsgStartHand) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MsgStartHand)
	if !ok {
		that2, ok := that.(MsgStartHand)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Caller != that1.Caller {
		return false
	}
	if this.TableId != that1.TableId {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *MsgStartHandResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MsgStartHandResponse)
	if !ok {
		that2, ok := that.(MsgStartHandResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *MsgAct) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MsgAct)
	if !ok {
		that2, ok := that.(MsgAct)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Player != that1.Player {
		return false
	}
	if this.TableId != that1.TableId {
		return false
	}
	if this.Action != that1.Action {
		return false
	}
	if this.Amount != that1.Amount {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *MsgActResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MsgActResponse)
	if !ok {
		that2, ok := that.(MsgActResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *MsgTick) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MsgTick)
	if !ok {
		that2, ok := that.(MsgTick)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Caller != that1.Caller {
		return false
	}
	if this.TableId != that1.TableId {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *MsgTickResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MsgTickResponse)
	if !ok {
		that2, ok := that.(MsgTickResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *MsgLeave) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MsgLeave)
	if !ok {
		that2, ok := that.(MsgLeave)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Player != that1.Player {
		return false
	}
	if this.TableId != that1.TableId {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *MsgLeaveResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MsgLeaveResponse)
	if !ok {
		that2, ok := that.(MsgLeaveResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	CreateTable(ctx context.Context, in *MsgCreateTable, opts ...grpc.CallOption) (*MsgCreateTableResponse, error)
	Sit(ctx context.Context, in *MsgSit, opts ...grpc.CallOption) (*MsgSitResponse, error)
	StartHand(ctx context.Context, in *MsgStartHand, opts ...grpc.CallOption) (*MsgStartHandResponse, error)
	Act(ctx context.Context, in *MsgAct, opts ...grpc.CallOption) (*MsgActResponse, error)
	Tick(ctx context.Context, in *MsgTick, opts ...grpc.CallOption) (*MsgTickResponse, error)
	Leave(ctx context.Context, in *MsgLeave, opts ...grpc.CallOption) (*MsgLeaveResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateTable(ctx context.Context, in *MsgCreateTable, opts ...grpc.CallOption) (*MsgCreateTableResponse, error) {
	out := new(MsgCreateTableResponse)
	err := c.cc.Invoke(ctx, "/onchainpoker.poker.v1.Msg/CreateTable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) Sit(ctx context.Context, in *MsgSit, opts ...grpc.CallOption) (*MsgSitResponse, error) {
	out := new(MsgSitResponse)
	err := c.cc.Invoke(ctx, "/onchainpoker.poker.v1.Msg/Sit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) StartHand(ctx context.Context, in *MsgStartHand, opts ...grpc.CallOption) (*MsgStartHandResponse, error) {
	out := new(MsgStartHandResponse)
	err := c.cc.Invoke(ctx, "/onchainpoker.poker.v1.Msg/StartHand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) Act(ctx context.Context, in *MsgAct, opts ...grpc.CallOption) (*MsgActResponse, error) {
	out := new(MsgActResponse)
	err := c.cc.Invoke(ctx, "/onchainpoker.poker.v1.Msg/Act", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) Tick(ctx context.Context, in *MsgTick, opts ...grpc.CallOption) (*MsgTickResponse, error) {
	out := new(MsgTickResponse)
	err := c.cc.Invoke(ctx, "/onchainpoker.poker.v1.Msg/Tick", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) Leave(ctx context.Context, in *MsgLeave, opts ...grpc.CallOption) (*MsgLeaveResponse, error) {
	out := new(MsgLeaveResponse)
	err := c.cc.Invoke(ctx, "/onchainpoker.poker.v1.Msg/Leave", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	CreateTable(context.Context, *MsgCreateTable) (*MsgCreateTableResponse, error)
	Sit(context.Context, *MsgSit) (*MsgSitResponse, error)
	StartHand(context.Context, *MsgStartHand) (*MsgStartHandResponse, error)
	Act(context.Context, *MsgAct) (*MsgActResponse, error)
	Tick(context.Context, *MsgTick) (*MsgTickResponse, error)
	Leave(context.Context, *MsgLeave) (*MsgLeaveResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateTable(ctx context.Context, req *MsgCreateTable) (*MsgCreateTableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTable not implemented")
}
func (*UnimplementedMsgServer) Sit(ctx context.Context, req *MsgSit) (*MsgSitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sit not implemented")
}
func (*UnimplementedMsgServer) StartHand(ctx context.Context, req *MsgStartHand) (*MsgStartHandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartHand not implemented")
}
func (*UnimplementedMsgServer) Act(ctx context.Context, req *MsgAct) (*MsgActResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Act not implemented")
}
func (*UnimplementedMsgServer) Tick(ctx context.Context, req *MsgTick) (*MsgTickResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Tick not implemented")
}
func (*UnimplementedMsgServer) Leave(ctx context.Context, req *MsgLeave) (*MsgLeaveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Leave not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateTable)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onchainpoker.poker.v1.Msg/CreateTable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateTable(ctx, req.(*MsgCreateTable))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_Sit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Sit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onchainpoker.poker.v1.Msg/Sit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Sit(ctx, req.(*MsgSit))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_StartHand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgStartHand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).StartHand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onchainpoker.poker.v1.Msg/StartHand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).StartHand(ctx, req.(*MsgStartHand))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_Act_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Act(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onchainpoker.poker.v1.Msg/Act",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Act(ctx, req.(*MsgAct))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_Tick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgTick)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Tick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onchainpoker.poker.v1.Msg/Tick",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Tick(ctx, req.(*MsgTick))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_Leave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgLeave)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Leave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onchainpoker.poker.v1.Msg/Leave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Leave(ctx, req.(*MsgLeave))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "onchainpoker.poker.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTable",
			Handler:    _Msg_CreateTable_Handler,
		},
		{
			MethodName: "Sit",
			Handler:    _Msg_Sit_Handler,
		},
		{
			MethodName: "StartHand",
			Handler:    _Msg_StartHand_Handler,
		},
		{
			MethodName: "Act",
			Handler:    _Msg_Act_Handler,
		},
		{
			MethodName: "Tick",
			Handler:    _Msg_Tick_Handler,
		},
		{
			MethodName: "Leave",
			Handler:    _Msg_Leave_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "onchainpoker/poker/v1/tx.proto",
}
