// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: onchainpoker/dealer/v1/dealer.proto

package types

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GenesisState struct {
	NextEpochId uint64       `protobuf:"varint,1,opt,name=next_epoch_id,json=nextEpochId,proto3" json:"next_epoch_id,omitempty"`
	Epoch       *DealerEpoch `protobuf:"bytes,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Dkg         *DealerDKG   `protobuf:"bytes,3,opt,name=dkg,proto3" json:"dkg,omitempty"`
	Params      Params       `protobuf:"bytes,4,opt,name=params,proto3" json:"params"`
	// Randomness-beacon commit-reveal state for the upcoming epoch (if any).
	// NOTE: after editing this file, regenerate generated Go code with:
	//
	//	cd apps/cosmos/proto && buf generate
	Beacon               *BeaconState `protobuf:"bytes,5,opt,name=beacon,proto3" json:"beacon,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_34672eba2f8d03b5, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenesisState.Unmarshal(m, b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return xxx_messageInfo_GenesisState.Size(m)
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetNextEpochId() uint64 {
	if m != nil {
		return m.NextEpochId
	}
	return 0
}

func (m *GenesisState) GetEpoch() *DealerEpoch {
	if m != nil {
		return m.Epoch
	}
	return nil
}

func (m *GenesisState) GetDkg() *DealerDKG {
	if m != nil {
		return m.Dkg
	}
	return nil
}

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetBeacon() *BeaconState {
	if m != nil {
		return m.Beacon
	}
	return nil
}

// Params defines the x/dealer module parameters.
//
// NOTE: Dealer faults are intended to map to real PoS stake risk:
// slashing and (optional) jailing of the underlying validator.
type Params struct {
	// Slash fraction (in basis points, 1 bps = 0.01%) for objective DKG faults.
	SlashBpsDkg uint32 `protobuf:"varint,1,opt,name=slash_bps_dkg,json=slashBpsDkg,proto3" json:"slash_bps_dkg,omitempty"`
	// Slash fraction (in basis points, 1 bps = 0.01%) for objective per-hand dealer faults.
	SlashBpsHandDealer uint32 `protobuf:"varint,2,opt,name=slash_bps_hand_dealer,json=slashBpsHandDealer,proto3" json:"slash_bps_hand_dealer,omitempty"`
	// Jail duration (in seconds) for objective DKG faults.
	JailSecondsDkg uint64 `protobuf:"varint,3,opt,name=jail_seconds_dkg,json=jailSecondsDkg,proto3" json:"jail_seconds_dkg,omitempty"`
	// Jail duration (in seconds) for objective per-hand dealer faults.
	JailSecondsHandDealer uint64 `protobuf:"varint,4,opt,name=jail_seconds_hand_dealer,json=jailSecondsHandDealer,proto3" json:"jail_seconds_hand_dealer,omitempty"`
	// DkgVersion gates the plaintext MsgDkgShareReveal path:
	//
	//	1 (default): accept both MsgDkgShareReveal (plaintext) and
	//	    MsgDkgEncryptedShare (DKG v2). Daemons may migrate opportunistically.
	//	2: reject MsgDkgShareReveal at the chain boundary; only encrypted-share
	//	    delivery is accepted. Governance should flip to v2 only after
	//	    confirming all dealers have upgraded to the v2 daemon (observable
	//	    via DealerMember.ephemeral_pubkey being populated for all members).
	//
	// See docs/DKG-V2.md §6 for the migration plan. Any value other than 1 or
	// 2 is rejected by Params.Validate.
	DkgVersion           uint32   `protobuf:"varint,5,opt,name=dkg_version,json=dkgVersion,proto3" json:"dkg_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_34672eba2f8d03b5, []int{1}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Params.Unmarshal(m, b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Params.Marshal(b, m, deterministic)
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return xxx_messageInfo_Params.Size(m)
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetSlashBpsDkg() uint32 {
	if m != nil {
		return m.SlashBpsDkg
	}
	return 0
}

func (m *Params) GetSlashBpsHandDealer() uint32 {
	if m != nil {
		return m.SlashBpsHandDealer
	}
	return 0
}

func (m *Params) GetJailSecondsDkg() uint64 {
	if m != nil {
		return m.JailSecondsDkg
	}
	return 0
}

func (m *Params) GetJailSecondsHandDealer() uint64 {
	if m != nil {
		return m.JailSecondsHandDealer
	}
	return 0
}

func (m *Params) GetDkgVersion() uint32 {
	if m != nil {
		return m.DkgVersion
	}
	return 0
}

type DealerMember struct {
	// Validator operator address (valoper).
	Validator string `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	// Shamir x-coordinate (non-zero).
	Index uint32 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	// 32-byte ristretto point (Y_i), set at epoch finalize.
	PubShare []byte `protobuf:"bytes,3,opt,name=pub_share,json=pubShare,proto3" json:"pub_share,omitempty"`
	// 32-byte ed25519 consensus pubkey snapshot (for DKG share-msg signatures).
	ConsPubkey []byte `protobuf:"bytes,4,opt,name=cons_pubkey,json=consPubkey,proto3" json:"cons_pubkey,omitempty"`
	// Consensus power at committee selection time (used for slashing distribution height/power).
	Power int64 `protobuf:"varint,5,opt,name=power,proto3" json:"power,omitempty"`
	// Per-epoch ephemeral ElGamal/Ristretto255 public key pkR_j = skR_j * G
	// used by DKG v2 encrypted-share delivery (see docs/DKG-V2.md). The dealer
	// daemon generates skR_j freshly at epoch begin and stores it locally;
	// pkR_j is posted with MsgDkgCommit and consumed by other dealers when
	// they submit MsgDkgEncryptedShare(...). 32 bytes (canonical ristretto
	// encoding) or empty on pre-v2 chains.
	EphemeralPubkey      []byte   `protobuf:"bytes,6,opt,name=ephemeral_pubkey,json=ephemeralPubkey,proto3" json:"ephemeral_pubkey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DealerMember) Reset()         { *m = DealerMember{} }
func (m *DealerMember) String() string { return proto.CompactTextString(m) }
func (*DealerMember) ProtoMessage()    {}
func (*DealerMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_34672eba2f8d03b5, []int{2}
}
func (m *DealerMember) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealerMember.Unmarshal(m, b)
}
func (m *DealerMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealerMember.Marshal(b, m, deterministic)
}
func (m *DealerMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealerMember.Merge(m, src)
}
func (m *DealerMember) XXX_Size() int {
	return xxx_messageInfo_DealerMember.Size(m)
}
func (m *DealerMember) XXX_DiscardUnknown() {
	xxx_messageInfo_DealerMember.DiscardUnknown(m)
}

var xxx_messageInfo_DealerMember proto.InternalMessageInfo

func (m *DealerMember) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

func (m *DealerMember) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *DealerMember) GetPubShare() []byte {
	if m != nil {
		return m.PubShare
	}
	return nil
}

func (m *DealerMember) GetConsPubkey() []byte {
	if m != nil {
		return m.ConsPubkey
	}
	return nil
}

func (m *DealerMember) GetPower() int64 {
	if m != nil {
		return m.Power
	}
	return 0
}

func (m *DealerMember) GetEphemeralPubkey() []byte {
	if m != nil {
		return m.EphemeralPubkey
	}
	return nil
}

type DealerEpoch struct {
	EpochId   uint64 `protobuf:"varint,1,opt,name=epoch_id,json=epochId,proto3" json:"epoch_id,omitempty"`
	Threshold uint32 `protobuf:"varint,2,opt,name=threshold,proto3" json:"threshold,omitempty"`
	// 32-byte ristretto point.
	PkEpoch []byte `protobuf:"bytes,3,opt,name=pk_epoch,json=pkEpoch,proto3" json:"pk_epoch,omitempty"`
	// sha256 (v0 placeholder) over the accepted transcript view.
	TranscriptRoot []byte `protobuf:"bytes,4,opt,name=transcript_root,json=transcriptRoot,proto3" json:"transcript_root,omitempty"`
	// Distribution/obligation height captured at committee selection time (typically the DKG start height).
	// Used for slashing so validators cannot evade by unbonding immediately after being selected.
	StartHeight int64 `protobuf:"varint,7,opt,name=start_height,json=startHeight,proto3" json:"start_height,omitempty"`
	// Canonical ordering: lexicographically ascending by validator.
	Slashed              []string       `protobuf:"bytes,5,rep,name=slashed,proto3" json:"slashed,omitempty"`
	Members              []DealerMember `protobuf:"bytes,6,rep,name=members,proto3" json:"members"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DealerEpoch) Reset()         { *m = DealerEpoch{} }
func (m *DealerEpoch) String() string { return proto.CompactTextString(m) }
func (*DealerEpoch) ProtoMessage()    {}
func (*DealerEpoch) Descriptor() ([]byte, []int) {
	return fileDescriptor_34672eba2f8d03b5, []int{3}
}
func (m *DealerEpoch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealerEpoch.Unmarshal(m, b)
}
func (m *DealerEpoch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealerEpoch.Marshal(b, m, deterministic)
}
func (m *DealerEpoch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealerEpoch.Merge(m, src)
}
func (m *DealerEpoch) XXX_Size() int {
	return xxx_messageInfo_DealerEpoch.Size(m)
}
func (m *DealerEpoch) XXX_DiscardUnknown() {
	xxx_messageInfo_DealerEpoch.DiscardUnknown(m)
}

var xxx_messageInfo_DealerEpoch proto.InternalMessageInfo

func (m *DealerEpoch) GetEpochId() uint64 {
	if m != nil {
		return m.EpochId
	}
	return 0
}

func (m *DealerEpoch) GetThreshold() uint32 {
	if m != nil {
		return m.Threshold
	}
	return 0
}

func (m *DealerEpoch) GetPkEpoch() []byte {
	if m != nil {
		return m.PkEpoch
	}
	return nil
}

func (m *DealerEpoch) GetTranscriptRoot() []byte {
	if m != nil {
		return m.TranscriptRoot
	}
	return nil
}

func (m *DealerEpoch) GetStartHeight() int64 {
	if m != nil {
		return m.StartHeight
	}
	return 0
}

func (m *DealerEpoch) GetSlashed() []string {
	if m != nil {
		return m.Slashed
	}
	return nil
}

func (m *DealerEpoch) GetMembers() []DealerMember {
	if m != nil {
		return m.Members
	}
	return nil
}

type DealerDKGCommit struct {
	Dealer               string   `protobuf:"bytes,1,opt,name=dealer,proto3" json:"dealer,omitempty"`
	Commitments          [][]byte `protobuf:"bytes,2,rep,name=commitments,proto3" json:"commitments,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DealerDKGCommit) Reset()         { *m = DealerDKGCommit{} }
func (m *DealerDKGCommit) String() string { return proto.CompactTextString(m) }
func (*DealerDKGCommit) ProtoMessage()    {}
func (*DealerDKGCommit) Descriptor() ([]byte, []int) {
	return fileDescriptor_34672eba2f8d03b5, []int{4}
}
func (m *DealerDKGCommit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealerDKGCommit.Unmarshal(m, b)
}
func (m *DealerDKGCommit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealerDKGCommit.Marshal(b, m, deterministic)
}
func (m *DealerDKGCommit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealerDKGCommit.Merge(m, src)
}
func (m *DealerDKGCommit) XXX_Size() int {
	return xxx_messageInfo_DealerDKGCommit.Size(m)
}
func (m *DealerDKGCommit) XXX_DiscardUnknown() {
	xxx_messageInfo_DealerDKGCommit.DiscardUnknown(m)
}

var xxx_messageInfo_DealerDKGCommit proto.InternalMessageInfo

func (m *DealerDKGCommit) GetDealer() string {
	if m != nil {
		return m.Dealer
	}
	return ""
}

func (m *DealerDKGCommit) GetCommitments() [][]byte {
	if m != nil {
		return m.Commitments
	}
	return nil
}

// DealerDKGEncryptedShare is an on-chain record of a single (dealer,
// recipient) share delivery for DKG v2. Replaces the plaintext
// DealerDKGShareReveal flow. See docs/DKG-V2.md and
// apps/cosmos/internal/ocpcrypto/dkg_encshare.go for the NIZK and the
// scalar-AEAD primitives.
type DealerDKGEncryptedShare struct {
	Dealer               string   `protobuf:"bytes,1,opt,name=dealer,proto3" json:"dealer,omitempty"`
	RecipientIndex       uint32   `protobuf:"varint,2,opt,name=recipient_index,json=recipientIndex,proto3" json:"recipient_index,omitempty"`
	U                    []byte   `protobuf:"bytes,3,opt,name=u,proto3" json:"u,omitempty"`
	V                    []byte   `protobuf:"bytes,4,opt,name=v,proto3" json:"v,omitempty"`
	Proof                []byte   `protobuf:"bytes,5,opt,name=proof,proto3" json:"proof,omitempty"`
	ScalarCt             []byte   `protobuf:"bytes,6,opt,name=scalar_ct,json=scalarCt,proto3" json:"scalar_ct,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DealerDKGEncryptedShare) Reset()         { *m = DealerDKGEncryptedShare{} }
func (m *DealerDKGEncryptedShare) String() string { return proto.CompactTextString(m) }
func (*DealerDKGEncryptedShare) ProtoMessage()    {}
func (*DealerDKGEncryptedShare) Descriptor() ([]byte, []int) {
	return fileDescriptor_34672eba2f8d03b5, []int{5}
}
func (m *DealerDKGEncryptedShare) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealerDKGEncryptedShare.Unmarshal(m, b)
}
func (m *DealerDKGEncryptedShare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealerDKGEncryptedShare.Marshal(b, m, deterministic)
}
func (m *DealerDKGEncryptedShare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealerDKGEncryptedShare.Merge(m, src)
}
func (m *DealerDKGEncryptedShare) XXX_Size() int {
	return xxx_messageInfo_DealerDKGEncryptedShare.Size(m)
}
func (m *DealerDKGEncryptedShare) XXX_DiscardUnknown() {
	xxx_messageInfo_DealerDKGEncryptedShare.DiscardUnknown(m)
}

var xxx_messageInfo_DealerDKGEncryptedShare proto.InternalMessageInfo

func (m *DealerDKGEncryptedShare) GetDealer() string {
	if m != nil {
		return m.Dealer
	}
	return ""
}

func (m *DealerDKGEncryptedShare) GetRecipientIndex() uint32 {
	if m != nil {
		return m.RecipientIndex
	}
	return 0
}

func (m *DealerDKGEncryptedShare) GetU() []byte {
	if m != nil {
		return m.U
	}
	return nil
}

func (m *DealerDKGEncryptedShare) GetV() []byte {
	if m != nil {
		return m.V
	}
	return nil
}

func (m *DealerDKGEncryptedShare) GetProof() []byte {
	if m != nil {
		return m.Proof
	}
	return nil
}

func (m *DealerDKGEncryptedShare) GetScalarCt() []byte {
	if m != nil {
		return m.ScalarCt
	}
	return nil
}

type DealerDKGComplaint struct {
	EpochId              uint64   `protobuf:"varint,1,opt,name=epoch_id,json=epochId,proto3" json:"epoch_id,omitempty"`
	Complainer           string   `protobuf:"bytes,2,opt,name=complainer,proto3" json:"complainer,omitempty"`
	Dealer               string   `protobuf:"bytes,3,opt,name=dealer,proto3" json:"dealer,omitempty"`
	Kind                 string   `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	ShareMsg             []byte   `protobuf:"bytes,5,opt,name=share_msg,json=shareMsg,proto3" json:"share_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DealerDKGComplaint) Reset()         { *m = DealerDKGComplaint{} }
func (m *DealerDKGComplaint) String() string { return proto.CompactTextString(m) }
func (*DealerDKGComplaint) ProtoMessage()    {}
func (*DealerDKGComplaint) Descriptor() ([]byte, []int) {
	return fileDescriptor_34672eba2f8d03b5, []int{6}
}
func (m *DealerDKGComplaint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealerDKGComplaint.Unmarshal(m, b)
}
func (m *DealerDKGComplaint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealerDKGComplaint.Marshal(b, m, deterministic)
}
func (m *DealerDKGComplaint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealerDKGComplaint.Merge(m, src)
}
func (m *DealerDKGComplaint) XXX_Size() int {
	return xxx_messageInfo_DealerDKGComplaint.Size(m)
}
func (m *DealerDKGComplaint) XXX_DiscardUnknown() {
	xxx_messageInfo_DealerDKGComplaint.DiscardUnknown(m)
}

var xxx_messageInfo_DealerDKGComplaint proto.InternalMessageInfo

func (m *DealerDKGComplaint) GetEpochId() uint64 {
	if m != nil {
		return m.EpochId
	}
	return 0
}

func (m *DealerDKGComplaint) GetComplainer() string {
	if m != nil {
		return m.Complainer
	}
	return ""
}

func (m *DealerDKGComplaint) GetDealer() string {
	if m != nil {
		return m.Dealer
	}
	return ""
}

func (m *DealerDKGComplaint) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *DealerDKGComplaint) GetShareMsg() []byte {
	if m != nil {
		return m.ShareMsg
	}
	return nil
}

type DealerDKGShareReveal struct {
	EpochId              uint64   `protobuf:"varint,1,opt,name=epoch_id,json=epochId,proto3" json:"epoch_id,omitempty"`
	Dealer               string   `protobuf:"bytes,2,opt,name=dealer,proto3" json:"dealer,omitempty"`
	To                   string   `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Share                []byte   `protobuf:"bytes,4,opt,name=share,proto3" json:"share,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DealerDKGShareReveal) Reset()         { *m = DealerDKGShareReveal{} }
func (m *DealerDKGShareReveal) String() string { return proto.CompactTextString(m) }
func (*DealerDKGShareReveal) ProtoMessage()    {}
func (*DealerDKGShareReveal) Descriptor() ([]byte, []int) {
	return fileDescriptor_34672eba2f8d03b5, []int{7}
}
func (m *DealerDKGShareReveal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealerDKGShareReveal.Unmarshal(m, b)
}
func (m *DealerDKGShareReveal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealerDKGShareReveal.Marshal(b, m, deterministic)
}
func (m *DealerDKGShareReveal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealerDKGShareReveal.Merge(m, src)
}
func (m *DealerDKGShareReveal) XXX_Size() int {
	return xxx_messageInfo_DealerDKGShareReveal.Size(m)
}
func (m *DealerDKGShareReveal) XXX_DiscardUnknown() {
	xxx_messageInfo_DealerDKGShareReveal.DiscardUnknown(m)
}

var xxx_messageInfo_DealerDKGShareReveal proto.InternalMessageInfo

func (m *DealerDKGShareReveal) GetEpochId() uint64 {
	if m != nil {
		return m.EpochId
	}
	return 0
}

func (m *DealerDKGShareReveal) GetDealer() string {
	if m != nil {
		return m.Dealer
	}
	return ""
}

func (m *DealerDKGShareReveal) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *DealerDKGShareReveal) GetShare() []byte {
	if m != nil {
		return m.Share
	}
	return nil
}

type DealerDKG struct {
	EpochId           uint64                 `protobuf:"varint,1,opt,name=epoch_id,json=epochId,proto3" json:"epoch_id,omitempty"`
	Threshold         uint32                 `protobuf:"varint,2,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Members           []DealerMember         `protobuf:"bytes,3,rep,name=members,proto3" json:"members"`
	StartHeight       int64                  `protobuf:"varint,4,opt,name=start_height,json=startHeight,proto3" json:"start_height,omitempty"`
	CommitDeadline    int64                  `protobuf:"varint,5,opt,name=commit_deadline,json=commitDeadline,proto3" json:"commit_deadline,omitempty"`
	ComplaintDeadline int64                  `protobuf:"varint,6,opt,name=complaint_deadline,json=complaintDeadline,proto3" json:"complaint_deadline,omitempty"`
	RevealDeadline    int64                  `protobuf:"varint,7,opt,name=reveal_deadline,json=revealDeadline,proto3" json:"reveal_deadline,omitempty"`
	FinalizeDeadline  int64                  `protobuf:"varint,8,opt,name=finalize_deadline,json=finalizeDeadline,proto3" json:"finalize_deadline,omitempty"`
	RandEpoch         []byte                 `protobuf:"bytes,9,opt,name=rand_epoch,json=randEpoch,proto3" json:"rand_epoch,omitempty"`
	Commits           []DealerDKGCommit      `protobuf:"bytes,10,rep,name=commits,proto3" json:"commits"`
	Complaints        []DealerDKGComplaint   `protobuf:"bytes,11,rep,name=complaints,proto3" json:"complaints"`
	Reveals           []DealerDKGShareReveal `protobuf:"bytes,12,rep,name=reveals,proto3" json:"reveals"`
	Slashed           []string               `protobuf:"bytes,13,rep,name=slashed,proto3" json:"slashed,omitempty"`
	// DKG v2 encrypted shares, sorted by (dealer, recipient_index). Populated
	// by MsgDkgEncryptedShare. On v2 chains this replaces the plaintext reveal
	// flow; on v1 chains it stays empty. See docs/DKG-V2.md.
	EncryptedShares      []DealerDKGEncryptedShare `protobuf:"bytes,14,rep,name=encrypted_shares,json=encryptedShares,proto3" json:"encrypted_shares"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *DealerDKG) Reset()         { *m = DealerDKG{} }
func (m *DealerDKG) String() string { return proto.CompactTextString(m) }
func (*DealerDKG) ProtoMessage()    {}
func (*DealerDKG) Descriptor() ([]byte, []int) {
	return fileDescriptor_34672eba2f8d03b5, []int{8}
}
func (m *DealerDKG) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealerDKG.Unmarshal(m, b)
}
func (m *DealerDKG) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealerDKG.Marshal(b, m, deterministic)
}
func (m *DealerDKG) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealerDKG.Merge(m, src)
}
func (m *DealerDKG) XXX_Size() int {
	return xxx_messageInfo_DealerDKG.Size(m)
}
func (m *DealerDKG) XXX_DiscardUnknown() {
	xxx_messageInfo_DealerDKG.DiscardUnknown(m)
}

var xxx_messageInfo_DealerDKG proto.InternalMessageInfo

func (m *DealerDKG) GetEpochId() uint64 {
	if m != nil {
		return m.EpochId
	}
	return 0
}

func (m *DealerDKG) GetThreshold() uint32 {
	if m != nil {
		return m.Threshold
	}
	return 0
}

func (m *DealerDKG) GetMembers() []DealerMember {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *DealerDKG) GetStartHeight() int64 {
	if m != nil {
		return m.StartHeight
	}
	return 0
}

func (m *DealerDKG) GetCommitDeadline() int64 {
	if m != nil {
		return m.CommitDeadline
	}
	return 0
}

func (m *DealerDKG) GetComplaintDeadline() int64 {
	if m != nil {
		return m.ComplaintDeadline
	}
	return 0
}

func (m *DealerDKG) GetRevealDeadline() int64 {
	if m != nil {
		return m.RevealDeadline
	}
	return 0
}

func (m *DealerDKG) GetFinalizeDeadline() int64 {
	if m != nil {
		return m.FinalizeDeadline
	}
	return 0
}

func (m *DealerDKG) GetRandEpoch() []byte {
	if m != nil {
		return m.RandEpoch
	}
	return nil
}

func (m *DealerDKG) GetCommits() []DealerDKGCommit {
	if m != nil {
		return m.Commits
	}
	return nil
}

func (m *DealerDKG) GetComplaints() []DealerDKGComplaint {
	if m != nil {
		return m.Complaints
	}
	return nil
}

func (m *DealerDKG) GetReveals() []DealerDKGShareReveal {
	if m != nil {
		return m.Reveals
	}
	return nil
}

func (m *DealerDKG) GetSlashed() []string {
	if m != nil {
		return m.Slashed
	}
	return nil
}

func (m *DealerDKG) GetEncryptedShares() []DealerDKGEncryptedShare {
	if m != nil {
		return m.EncryptedShares
	}
	return nil
}

type DealerCiphertext struct {
	C1                   []byte   `protobuf:"bytes,1,opt,name=c1,proto3" json:"c1,omitempty"`
	C2                   []byte   `protobuf:"bytes,2,opt,name=c2,proto3" json:"c2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DealerCiphertext) Reset()         { *m = DealerCiphertext{} }
func (m *DealerCiphertext) String() string { return proto.CompactTextString(m) }
func (*DealerCiphertext) ProtoMessage()    {}
func (*DealerCiphertext) Descriptor() ([]byte, []int) {
	return fileDescriptor_34672eba2f8d03b5, []int{9}
}
func (m *DealerCiphertext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealerCiphertext.Unmarshal(m, b)
}
func (m *DealerCiphertext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealerCiphertext.Marshal(b, m, deterministic)
}
func (m *DealerCiphertext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealerCiphertext.Merge(m, src)
}
func (m *DealerCiphertext) XXX_Size() int {
	return xxx_messageInfo_DealerCiphertext.Size(m)
}
func (m *DealerCiphertext) XXX_DiscardUnknown() {
	xxx_messageInfo_DealerCiphertext.DiscardUnknown(m)
}

var xxx_messageInfo_DealerCiphertext proto.InternalMessageInfo

func (m *DealerCiphertext) GetC1() []byte {
	if m != nil {
		return m.C1
	}
	return nil
}

func (m *DealerCiphertext) GetC2() []byte {
	if m != nil {
		return m.C2
	}
	return nil
}

type DealerPubShare struct {
	Pos                  uint32   `protobuf:"varint,1,opt,name=pos,proto3" json:"pos,omitempty"`
	Validator            string   `protobuf:"bytes,2,opt,name=validator,proto3" json:"validator,omitempty"`
	Index                uint32   `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	Share                []byte   `protobuf:"bytes,4,opt,name=share,proto3" json:"share,omitempty"`
	Proof                []byte   `protobuf:"bytes,5,opt,name=proof,proto3" json:"proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DealerPubShare) Reset()         { *m = DealerPubShare{} }
func (m *DealerPubShare) String() string { return proto.CompactTextString(m) }
func (*DealerPubShare) ProtoMessage()    {}
func (*DealerPubShare) Descriptor() ([]byte, []int) {
	return fileDescriptor_34672eba2f8d03b5, []int{10}
}
func (m *DealerPubShare) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealerPubShare.Unmarshal(m, b)
}
func (m *DealerPubShare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealerPubShare.Marshal(b, m, deterministic)
}
func (m *DealerPubShare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealerPubShare.Merge(m, src)
}
func (m *DealerPubShare) XXX_Size() int {
	return xxx_messageInfo_DealerPubShare.Size(m)
}
func (m *DealerPubShare) XXX_DiscardUnknown() {
	xxx_messageInfo_DealerPubShare.DiscardUnknown(m)
}

var xxx_messageInfo_DealerPubShare proto.InternalMessageInfo

func (m *DealerPubShare) GetPos() uint32 {
	if m != nil {
		return m.Pos
	}
	return 0
}

func (m *DealerPubShare) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

func (m *DealerPubShare) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *DealerPubShare) GetShare() []byte {
	if m != nil {
		return m.Share
	}
	return nil
}

func (m *DealerPubShare) GetProof() []byte {
	if m != nil {
		return m.Proof
	}
	return nil
}

type DealerEncShare struct {
	Pos                  uint32   `protobuf:"varint,1,opt,name=pos,proto3" json:"pos,omitempty"`
	Validator            string   `protobuf:"bytes,2,opt,name=validator,proto3" json:"validator,omitempty"`
	Index                uint32   `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	PkPlayer             []byte   `protobuf:"bytes,4,opt,name=pk_player,json=pkPlayer,proto3" json:"pk_player,omitempty"`
	EncShare             []byte   `protobuf:"bytes,5,opt,name=enc_share,json=encShare,proto3" json:"enc_share,omitempty"`
	Proof                []byte   `protobuf:"bytes,6,opt,name=proof,proto3" json:"proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DealerEncShare) Reset()         { *m = DealerEncShare{} }
func (m *DealerEncShare) String() string { return proto.CompactTextString(m) }
func (*DealerEncShare) ProtoMessage()    {}
func (*DealerEncShare) Descriptor() ([]byte, []int) {
	return fileDescriptor_34672eba2f8d03b5, []int{11}
}
func (m *DealerEncShare) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealerEncShare.Unmarshal(m, b)
}
func (m *DealerEncShare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealerEncShare.Marshal(b, m, deterministic)
}
func (m *DealerEncShare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealerEncShare.Merge(m, src)
}
func (m *DealerEncShare) XXX_Size() int {
	return xxx_messageInfo_DealerEncShare.Size(m)
}
func (m *DealerEncShare) XXX_DiscardUnknown() {
	xxx_messageInfo_DealerEncShare.DiscardUnknown(m)
}

var xxx_messageInfo_DealerEncShare proto.InternalMessageInfo

func (m *DealerEncShare) GetPos() uint32 {
	if m != nil {
		return m.Pos
	}
	return 0
}

func (m *DealerEncShare) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

func (m *DealerEncShare) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *DealerEncShare) GetPkPlayer() []byte {
	if m != nil {
		return m.PkPlayer
	}
	return nil
}

func (m *DealerEncShare) GetEncShare() []byte {
	if m != nil {
		return m.EncShare
	}
	return nil
}

func (m *DealerEncShare) GetProof() []byte {
	if m != nil {
		return m.Proof
	}
	return nil
}

type DealerReveal struct {
	Pos                  uint32   `protobuf:"varint,1,opt,name=pos,proto3" json:"pos,omitempty"`
	CardId               uint32   `protobuf:"varint,2,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DealerReveal) Reset()         { *m = DealerReveal{} }
func (m *DealerReveal) String() string { return proto.CompactTextString(m) }
func (*DealerReveal) ProtoMessage()    {}
func (*DealerReveal) Descriptor() ([]byte, []int) {
	return fileDescriptor_34672eba2f8d03b5, []int{12}
}
func (m *DealerReveal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealerReveal.Unmarshal(m, b)
}
func (m *DealerReveal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealerReveal.Marshal(b, m, deterministic)
}
func (m *DealerReveal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealerReveal.Merge(m, src)
}
func (m *DealerReveal) XXX_Size() int {
	return xxx_messageInfo_DealerReveal.Size(m)
}
func (m *DealerReveal) XXX_DiscardUnknown() {
	xxx_messageInfo_DealerReveal.DiscardUnknown(m)
}

var xxx_messageInfo_DealerReveal proto.InternalMessageInfo

func (m *DealerReveal) GetPos() uint32 {
	if m != nil {
		return m.Pos
	}
	return 0
}

func (m *DealerReveal) GetCardId() uint32 {
	if m != nil {
		return m.CardId
	}
	return 0
}

// BeaconState tracks the commit-reveal randomness beacon for an upcoming
// epoch. It is written when the dealer module opens a beacon window and is
// consumed when that epoch is begun.
//
// Security: unlike DevnetRandEpoch (proposer-influenceable block hash mix),
// the beacon output is fixed by an adversary-agnostic mechanism: all commits
// must be posted before any salt is revealed.
type BeaconState struct {
	// Epoch id this beacon will seed once the reveal window closes.
	EpochId uint64 `protobuf:"varint,1,opt,name=epoch_id,json=epochId,proto3" json:"epoch_id,omitempty"`
	// Block height at which the commit window opens / closes.
	CommitOpenHeight  int64 `protobuf:"varint,2,opt,name=commit_open_height,json=commitOpenHeight,proto3" json:"commit_open_height,omitempty"`
	CommitCloseHeight int64 `protobuf:"varint,3,opt,name=commit_close_height,json=commitCloseHeight,proto3" json:"commit_close_height,omitempty"`
	// Block height at which the reveal window closes.
	RevealCloseHeight int64 `protobuf:"varint,4,opt,name=reveal_close_height,json=revealCloseHeight,proto3" json:"reveal_close_height,omitempty"`
	// Minimum number of revealed salts required to produce a non-fallback
	// beacon. If fewer reveals are received, the epoch falls back to devnet
	// randomness (allowed only on devnet/local chain ids) and emits an event.
	Threshold uint32 `protobuf:"varint,5,opt,name=threshold,proto3" json:"threshold,omitempty"`
	// Validator commits (sorted lexicographically by validator).
	Commits []BeaconCommitEntry `protobuf:"bytes,6,rep,name=commits,proto3" json:"commits"`
	// Validator reveals (sorted lexicographically by validator). Only validators
	// that committed may appear here.
	Reveals []BeaconRevealEntry `protobuf:"bytes,7,rep,name=reveals,proto3" json:"reveals"`
	// Finalized beacon output (32 bytes). Empty until the reveal window closes
	// and the chain consumes the state to compute the final value.
	Final []byte `protobuf:"bytes,8,opt,name=final,proto3" json:"final,omitempty"`
	// True if finalization used the fallback (insufficient reveals or non-prod
	// chain id). Auditable via FinalizeBeacon event.
	Fallback             bool     `protobuf:"varint,9,opt,name=fallback,proto3" json:"fallback,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BeaconState) Reset()         { *m = BeaconState{} }
func (m *BeaconState) String() string { return proto.CompactTextString(m) }
func (*BeaconState) ProtoMessage()    {}
func (*BeaconState) Descriptor() ([]byte, []int) {
	return fileDescriptor_34672eba2f8d03b5, []int{13}
}
func (m *BeaconState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeaconState.Unmarshal(m, b)
}
func (m *BeaconState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeaconState.Marshal(b, m, deterministic)
}
func (m *BeaconState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeaconState.Merge(m, src)
}
func (m *BeaconState) XXX_Size() int {
	return xxx_messageInfo_BeaconState.Size(m)
}
func (m *BeaconState) XXX_DiscardUnknown() {
	xxx_messageInfo_BeaconState.DiscardUnknown(m)
}

var xxx_messageInfo_BeaconState proto.InternalMessageInfo

func (m *BeaconState) GetEpochId() uint64 {
	if m != nil {
		return m.EpochId
	}
	return 0
}

func (m *BeaconState) GetCommitOpenHeight() int64 {
	if m != nil {
		return m.CommitOpenHeight
	}
	return 0
}

func (m *BeaconState) GetCommitCloseHeight() int64 {
	if m != nil {
		return m.CommitCloseHeight
	}
	return 0
}

func (m *BeaconState) GetRevealCloseHeight() int64 {
	if m != nil {
		return m.RevealCloseHeight
	}
	return 0
}

func (m *BeaconState) GetThreshold() uint32 {
	if m != nil {
		return m.Threshold
	}
	return 0
}

func (m *BeaconState) GetCommits() []BeaconCommitEntry {
	if m != nil {
		return m.Commits
	}
	return nil
}

func (m *BeaconState) GetReveals() []BeaconRevealEntry {
	if m != nil {
		return m.Reveals
	}
	return nil
}

func (m *BeaconState) GetFinal() []byte {
	if m != nil {
		return m.Final
	}
	return nil
}

func (m *BeaconState) GetFallback() bool {
	if m != nil {
		return m.Fallback
	}
	return false
}

type BeaconCommitEntry struct {
	Validator string `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	// 32-byte sha256 commit.
	Commit               []byte   `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BeaconCommitEntry) Reset()         { *m = BeaconCommitEntry{} }
func (m *BeaconCommitEntry) String() string { return proto.CompactTextString(m) }
func (*BeaconCommitEntry) ProtoMessage()    {}
func (*BeaconCommitEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_34672eba2f8d03b5, []int{14}
}
func (m *BeaconCommitEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeaconCommitEntry.Unmarshal(m, b)
}
func (m *BeaconCommitEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeaconCommitEntry.Marshal(b, m, deterministic)
}
func (m *BeaconCommitEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeaconCommitEntry.Merge(m, src)
}
func (m *BeaconCommitEntry) XXX_Size() int {
	return xxx_messageInfo_BeaconCommitEntry.Size(m)
}
func (m *BeaconCommitEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_BeaconCommitEntry.DiscardUnknown(m)
}

var xxx_messageInfo_BeaconCommitEntry proto.InternalMessageInfo

func (m *BeaconCommitEntry) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

func (m *BeaconCommitEntry) GetCommit() []byte {
	if m != nil {
		return m.Commit
	}
	return nil
}

type BeaconRevealEntry struct {
	Validator string `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	// 32-byte salt whose H() matched the stored commit.
	Salt                 []byte   `protobuf:"bytes,2,opt,name=salt,proto3" json:"salt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BeaconRevealEntry) Reset()         { *m = BeaconRevealEntry{} }
func (m *BeaconRevealEntry) String() string { return proto.CompactTextString(m) }
func (*BeaconRevealEntry) ProtoMessage()    {}
func (*BeaconRevealEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_34672eba2f8d03b5, []int{15}
}
func (m *BeaconRevealEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeaconRevealEntry.Unmarshal(m, b)
}
func (m *BeaconRevealEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeaconRevealEntry.Marshal(b, m, deterministic)
}
func (m *BeaconRevealEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeaconRevealEntry.Merge(m, src)
}
func (m *BeaconRevealEntry) XXX_Size() int {
	return xxx_messageInfo_BeaconRevealEntry.Size(m)
}
func (m *BeaconRevealEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_BeaconRevealEntry.DiscardUnknown(m)
}

var xxx_messageInfo_BeaconRevealEntry proto.InternalMessageInfo

func (m *BeaconRevealEntry) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

func (m *BeaconRevealEntry) GetSalt() []byte {
	if m != nil {
		return m.Salt
	}
	return nil
}

type DealerHand struct {
	EpochId            uint64             `protobuf:"varint,1,opt,name=epoch_id,json=epochId,proto3" json:"epoch_id,omitempty"`
	PkHand             []byte             `protobuf:"bytes,2,opt,name=pk_hand,json=pkHand,proto3" json:"pk_hand,omitempty"`
	DeckSize           uint32             `protobuf:"varint,3,opt,name=deck_size,json=deckSize,proto3" json:"deck_size,omitempty"`
	Deck               []DealerCiphertext `protobuf:"bytes,4,rep,name=deck,proto3" json:"deck"`
	ShuffleStep        uint32             `protobuf:"varint,5,opt,name=shuffle_step,json=shuffleStep,proto3" json:"shuffle_step,omitempty"`
	Finalized          bool               `protobuf:"varint,6,opt,name=finalized,proto3" json:"finalized,omitempty"`
	ShuffleDeadline    int64              `protobuf:"varint,7,opt,name=shuffle_deadline,json=shuffleDeadline,proto3" json:"shuffle_deadline,omitempty"`
	HoleSharesDeadline int64              `protobuf:"varint,8,opt,name=hole_shares_deadline,json=holeSharesDeadline,proto3" json:"hole_shares_deadline,omitempty"`
	PubShares          []DealerPubShare   `protobuf:"bytes,9,rep,name=pub_shares,json=pubShares,proto3" json:"pub_shares"`
	EncShares          []DealerEncShare   `protobuf:"bytes,10,rep,name=enc_shares,json=encShares,proto3" json:"enc_shares"`
	Reveals            []DealerReveal     `protobuf:"bytes,11,rep,name=reveals,proto3" json:"reveals"`
	// Per-hand init-time block entropy mixed into k_hand (v2 hand-derive).
	// Captured at InitHand from sdkCtx.BlockHeight() and sdkCtx.BlockHeader().LastBlockId.Hash.
	// Purpose: bound the retroactive-decryption window if the epoch secret later leaks —
	// without these, k_hand is publicly recomputable from (epochId, tableId, handId) alone,
	// so leaking the epoch secret decrypts every past hand in the epoch. Binding to
	// per-hand block entropy that the attacker cannot grind after the fact raises the bar.
	InitHeight           int64    `protobuf:"varint,20,opt,name=init_height,json=initHeight,proto3" json:"init_height,omitempty"`
	InitHashSalt         []byte   `protobuf:"bytes,21,opt,name=init_hash_salt,json=initHashSalt,proto3" json:"init_hash_salt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DealerHand) Reset()         { *m = DealerHand{} }
func (m *DealerHand) String() string { return proto.CompactTextString(m) }
func (*DealerHand) ProtoMessage()    {}
func (*DealerHand) Descriptor() ([]byte, []int) {
	return fileDescriptor_34672eba2f8d03b5, []int{16}
}
func (m *DealerHand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealerHand.Unmarshal(m, b)
}
func (m *DealerHand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealerHand.Marshal(b, m, deterministic)
}
func (m *DealerHand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealerHand.Merge(m, src)
}
func (m *DealerHand) XXX_Size() int {
	return xxx_messageInfo_DealerHand.Size(m)
}
func (m *DealerHand) XXX_DiscardUnknown() {
	xxx_messageInfo_DealerHand.DiscardUnknown(m)
}

var xxx_messageInfo_DealerHand proto.InternalMessageInfo

func (m *DealerHand) GetEpochId() uint64 {
	if m != nil {
		return m.EpochId
	}
	return 0
}

func (m *DealerHand) GetPkHand() []byte {
	if m != nil {
		return m.PkHand
	}
	return nil
}

func (m *DealerHand) GetDeckSize() uint32 {
	if m != nil {
		return m.DeckSize
	}
	return 0
}

func (m *DealerHand) GetDeck() []DealerCiphertext {
	if m != nil {
		return m.Deck
	}
	return nil
}

func (m *DealerHand) GetShuffleStep() uint32 {
	if m != nil {
		return m.ShuffleStep
	}
	return 0
}

func (m *DealerHand) GetFinalized() bool {
	if m != nil {
		return m.Finalized
	}
	return false
}

func (m *DealerHand) GetShuffleDeadline() int64 {
	if m != nil {
		return m.ShuffleDeadline
	}
	return 0
}

func (m *DealerHand) GetHoleSharesDeadline() int64 {
	if m != nil {
		return m.HoleSharesDeadline
	}
	return 0
}

func (m *DealerHand) GetPubShares() []DealerPubShare {
	if m != nil {
		return m.PubShares
	}
	return nil
}

func (m *DealerHand) GetEncShares() []DealerEncShare {
	if m != nil {
		return m.EncShares
	}
	return nil
}

func (m *DealerHand) GetReveals() []DealerReveal {
	if m != nil {
		return m.Reveals
	}
	return nil
}

func (m *DealerHand) GetInitHeight() int64 {
	if m != nil {
		return m.InitHeight
	}
	return 0
}

func (m *DealerHand) GetInitHashSalt() []byte {
	if m != nil {
		return m.InitHashSalt
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "onchainpoker.dealer.v1.GenesisState")
	proto.RegisterType((*Params)(nil), "onchainpoker.dealer.v1.Params")
	proto.RegisterType((*DealerMember)(nil), "onchainpoker.dealer.v1.DealerMember")
	proto.RegisterType((*DealerEpoch)(nil), "onchainpoker.dealer.v1.DealerEpoch")
	proto.RegisterType((*DealerDKGCommit)(nil), "onchainpoker.dealer.v1.DealerDKGCommit")
	proto.RegisterType((*DealerDKGEncryptedShare)(nil), "onchainpoker.dealer.v1.DealerDKGEncryptedShare")
	proto.RegisterType((*DealerDKGComplaint)(nil), "onchainpoker.dealer.v1.DealerDKGComplaint")
	proto.RegisterType((*DealerDKGShareReveal)(nil), "onchainpoker.dealer.v1.DealerDKGShareReveal")
	proto.RegisterType((*DealerDKG)(nil), "onchainpoker.dealer.v1.DealerDKG")
	proto.RegisterType((*DealerCiphertext)(nil), "onchainpoker.dealer.v1.DealerCiphertext")
	proto.RegisterType((*DealerPubShare)(nil), "onchainpoker.dealer.v1.DealerPubShare")
	proto.RegisterType((*DealerEncShare)(nil), "onchainpoker.dealer.v1.DealerEncShare")
	proto.RegisterType((*DealerReveal)(nil), "onchainpoker.dealer.v1.DealerReveal")
	proto.RegisterType((*BeaconState)(nil), "onchainpoker.dealer.v1.BeaconState")
	proto.RegisterType((*BeaconCommitEntry)(nil), "onchainpoker.dealer.v1.BeaconCommitEntry")
	proto.RegisterType((*BeaconRevealEntry)(nil), "onchainpoker.dealer.v1.BeaconRevealEntry")
	proto.RegisterType((*DealerHand)(nil), "onchainpoker.dealer.v1.DealerHand")
}

func init() {
	proto.RegisterFile("onchainpoker/dealer/v1/dealer.proto", fileDescriptor_34672eba2f8d03b5)
}

var fileDescriptor_34672eba2f8d03b5 = []byte{
	// 1521 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x4b, 0x6f, 0x1c, 0xc5,
	0x13, 0xff, 0xef, 0xc3, 0xfb, 0xa8, 0x5d, 0xaf, 0xed, 0xfe, 0x3b, 0xc9, 0xe4, 0xed, 0x4c, 0x22,
	0xec, 0x40, 0x62, 0x63, 0x73, 0x40, 0x91, 0x90, 0xa2, 0xf8, 0xa1, 0xc4, 0x0a, 0x11, 0xd6, 0xac,
	0x94, 0x03, 0x97, 0x61, 0x76, 0xa6, 0xbd, 0x33, 0xcc, 0xec, 0xf4, 0x68, 0xba, 0xbd, 0xd8, 0x39,
	0x72, 0xe7, 0xce, 0x81, 0x33, 0xe2, 0xc6, 0x85, 0x2f, 0xc0, 0x8d, 0x03, 0x27, 0x3e, 0x00, 0x48,
	0x20, 0xf1, 0x39, 0x50, 0x57, 0x77, 0xcf, 0xce, 0xda, 0xce, 0xda, 0x0a, 0xdc, 0xa6, 0xaa, 0xeb,
	0xdd, 0x55, 0xbf, 0xea, 0x81, 0xfb, 0x2c, 0xf5, 0x43, 0x2f, 0x4a, 0x33, 0x16, 0xd3, 0x7c, 0x23,
	0xa0, 0x5e, 0x42, 0xf3, 0x8d, 0xf1, 0xa6, 0xfe, 0x5a, 0xcf, 0x72, 0x26, 0x18, 0xb9, 0x5a, 0x16,
	0x5a, 0xd7, 0x47, 0xe3, 0xcd, 0x1b, 0xcb, 0x43, 0x36, 0x64, 0x28, 0xb2, 0x21, 0xbf, 0x94, 0xf4,
	0x8d, 0xeb, 0x3e, 0xe3, 0x23, 0xc6, 0x5d, 0x75, 0xa0, 0x08, 0x75, 0x64, 0xff, 0x58, 0x85, 0xee,
	0x73, 0x9a, 0x52, 0x1e, 0xf1, 0xbe, 0xf0, 0x04, 0x25, 0x36, 0xcc, 0xa7, 0xf4, 0x58, 0xb8, 0x34,
	0x63, 0x7e, 0xe8, 0x46, 0x81, 0x55, 0x59, 0xa9, 0xac, 0xd5, 0x9d, 0x8e, 0x64, 0xee, 0x49, 0xde,
	0x7e, 0x40, 0x9e, 0xc2, 0x1c, 0x1e, 0x5b, 0xd5, 0x95, 0xca, 0x5a, 0x67, 0xeb, 0xfe, 0xfa, 0xf9,
	0xd1, 0xac, 0xef, 0xe2, 0x17, 0x6a, 0x6d, 0xd7, 0x7f, 0xf9, 0xfd, 0x6e, 0xc5, 0x51, 0x7a, 0xe4,
	0x09, 0xd4, 0x82, 0x78, 0x68, 0xd5, 0x50, 0xfd, 0xde, 0x6c, 0xf5, 0xdd, 0x97, 0xcf, 0xb5, 0xb2,
	0xd4, 0x21, 0x9f, 0x40, 0x23, 0xf3, 0x72, 0x6f, 0xc4, 0xad, 0x3a, 0x6a, 0xdf, 0x79, 0x9b, 0xf6,
	0x01, 0x4a, 0xa1, 0xea, 0xff, 0x1c, 0xad, 0x43, 0x9e, 0x41, 0x63, 0x40, 0x3d, 0x9f, 0xa5, 0xd6,
	0xdc, 0xec, 0xd0, 0xb7, 0x51, 0x0a, 0x4b, 0xa2, 0xbd, 0x6b, 0x45, 0xfb, 0xaf, 0x0a, 0x34, 0x94,
	0x6d, 0x59, 0x2b, 0x9e, 0x78, 0x3c, 0x74, 0x07, 0x19, 0x77, 0x65, 0x42, 0xb2, 0x56, 0xf3, 0x4e,
	0x07, 0x99, 0xdb, 0x19, 0xdf, 0x8d, 0x87, 0x64, 0x13, 0xae, 0x4c, 0x64, 0x42, 0x2f, 0x0d, 0x5c,
	0xe5, 0x04, 0x6b, 0x37, 0xef, 0x10, 0x23, 0xfb, 0xc2, 0x4b, 0x03, 0x95, 0x30, 0x59, 0x83, 0xc5,
	0x2f, 0xbd, 0x28, 0x71, 0x39, 0xf5, 0x59, 0x1a, 0x28, 0xcb, 0x35, 0xbc, 0x85, 0x9e, 0xe4, 0xf7,
	0x15, 0x5b, 0x1a, 0xff, 0x18, 0xac, 0x29, 0xc9, 0xb2, 0xfd, 0x3a, 0x6a, 0x5c, 0x29, 0x69, 0x94,
	0x5c, 0xdc, 0x85, 0x4e, 0x10, 0x0f, 0xdd, 0x31, 0xcd, 0x79, 0xa4, 0x8b, 0x31, 0xef, 0x40, 0x10,
	0x0f, 0x5f, 0x2b, 0x8e, 0xfd, 0x73, 0x05, 0xba, 0x4a, 0xf6, 0x15, 0x1d, 0x0d, 0x68, 0x4e, 0x6e,
	0x41, 0x7b, 0xec, 0x25, 0x51, 0xe0, 0x09, 0x96, 0x63, 0x9e, 0x6d, 0x67, 0xc2, 0x20, 0xcb, 0x30,
	0x17, 0xa5, 0x01, 0x3d, 0xd6, 0x59, 0x29, 0x82, 0xdc, 0x84, 0x76, 0x76, 0x34, 0x70, 0x79, 0xe8,
	0xe5, 0x14, 0x33, 0xe8, 0x3a, 0xad, 0xec, 0x68, 0xd0, 0x97, 0xb4, 0x0c, 0xc1, 0x67, 0x29, 0x77,
	0xb3, 0xa3, 0x41, 0x4c, 0x4f, 0x30, 0xdc, 0xae, 0x03, 0x92, 0x75, 0x80, 0x1c, 0x69, 0x33, 0x63,
	0x5f, 0xd1, 0x1c, 0xa3, 0xab, 0x39, 0x8a, 0x20, 0x0f, 0x61, 0x91, 0x66, 0x21, 0x1d, 0xd1, 0xdc,
	0x4b, 0x8c, 0x6e, 0x03, 0x75, 0x17, 0x0a, 0xbe, 0x32, 0x60, 0x7f, 0x53, 0x85, 0x4e, 0xa9, 0x05,
	0xc9, 0x75, 0x68, 0x9d, 0xea, 0xea, 0x26, 0xd5, 0x1d, 0x7d, 0x0b, 0xda, 0x22, 0xcc, 0x29, 0x0f,
	0x59, 0x12, 0xe8, 0x1c, 0x26, 0x0c, 0xa9, 0x98, 0xc5, 0x6a, 0x22, 0x74, 0x1a, 0xcd, 0x2c, 0x56,
	0x36, 0x57, 0x61, 0x41, 0xe4, 0x5e, 0xca, 0xfd, 0x3c, 0xca, 0x84, 0x9b, 0x33, 0x26, 0x74, 0x26,
	0xbd, 0x09, 0xdb, 0x61, 0x4c, 0x90, 0x7b, 0xd0, 0xe5, 0xc2, 0xcb, 0x85, 0x1b, 0xd2, 0x68, 0x18,
	0x0a, 0xab, 0x89, 0x49, 0x75, 0x90, 0xf7, 0x02, 0x59, 0xc4, 0x82, 0x26, 0x76, 0x03, 0x0d, 0xac,
	0xb9, 0x95, 0xda, 0x5a, 0xdb, 0x31, 0x24, 0xd9, 0x85, 0xe6, 0x08, 0xaf, 0x81, 0x5b, 0x8d, 0x95,
	0xda, 0x5a, 0x67, 0xeb, 0xc1, 0xec, 0x99, 0x51, 0x77, 0xa6, 0x7b, 0xdf, 0xa8, 0xda, 0x2f, 0x61,
	0xa1, 0x18, 0xa9, 0x1d, 0x36, 0x1a, 0x45, 0x82, 0x5c, 0x85, 0x86, 0x6e, 0x17, 0x75, 0xa5, 0x9a,
	0x22, 0x2b, 0xf2, 0x72, 0xa4, 0xc4, 0x88, 0xa6, 0x82, 0x5b, 0xd5, 0x95, 0xda, 0x5a, 0xd7, 0x29,
	0xb3, 0xec, 0x5f, 0x2b, 0x70, 0xad, 0xb0, 0xb6, 0x97, 0xfa, 0xf9, 0x49, 0x26, 0x68, 0xa0, 0xae,
	0xf6, 0xc9, 0xb4, 0xd5, 0xed, 0x7b, 0xbf, 0xfd, 0xf4, 0xf8, 0xb6, 0x86, 0x9d, 0xd7, 0xa6, 0x67,
	0x9e, 0x05, 0x41, 0x4e, 0x39, 0xef, 0x8b, 0x3c, 0x4a, 0x87, 0x85, 0xe3, 0x55, 0x58, 0xc8, 0xa9,
	0x1f, 0x65, 0x11, 0x4d, 0x85, 0x5b, 0x6e, 0xa9, 0x5e, 0xc1, 0xde, 0xc7, 0xde, 0xea, 0x42, 0xe5,
	0x48, 0x5f, 0x46, 0xe5, 0x48, 0x52, 0x63, 0x5d, 0xf8, 0xca, 0x18, 0x3b, 0x27, 0x67, 0xec, 0x10,
	0x3b, 0xa7, 0xeb, 0x28, 0x42, 0x76, 0x23, 0xf7, 0xbd, 0xc4, 0xcb, 0x5d, 0x5f, 0xe8, 0x96, 0x69,
	0x29, 0xc6, 0x8e, 0xb0, 0xbf, 0xad, 0x00, 0x29, 0x17, 0x27, 0x4b, 0xbc, 0x28, 0x15, 0xb3, 0x5a,
	0xe6, 0x0e, 0x80, 0xaf, 0xe5, 0xf4, 0x34, 0xb7, 0x9d, 0x12, 0xa7, 0x54, 0xda, 0xda, 0x54, 0x69,
	0x09, 0xd4, 0xe3, 0x28, 0x0d, 0x30, 0xda, 0xb6, 0x83, 0xdf, 0x18, 0x9a, 0xac, 0x9c, 0x3b, 0xe2,
	0x43, 0x1d, 0x74, 0x0b, 0x19, 0xaf, 0xf8, 0xd0, 0x66, 0xb0, 0x5c, 0x44, 0x86, 0xf5, 0x75, 0xe8,
	0x98, 0x7a, 0xc9, 0xac, 0xd8, 0x26, 0xbe, 0xab, 0x53, 0xbe, 0x7b, 0x50, 0x15, 0x4c, 0xc7, 0x53,
	0x15, 0x4c, 0x16, 0x4a, 0x0d, 0xa7, 0x2a, 0x9d, 0x22, 0xec, 0x3f, 0xe6, 0xa0, 0x5d, 0x78, 0x7c,
	0xf7, 0xa9, 0x29, 0x35, 0x6d, 0xed, 0x9d, 0x9b, 0xf6, 0xcc, 0xdc, 0xd4, 0xcf, 0xce, 0xcd, 0x2a,
	0x2c, 0xa8, 0xce, 0x94, 0xd0, 0x17, 0x24, 0x51, 0x4a, 0x35, 0x64, 0xf4, 0x14, 0x7b, 0x57, 0x73,
	0xc9, 0x63, 0x20, 0xe6, 0x82, 0x4a, 0xb2, 0x0d, 0x94, 0x5d, 0x2a, 0x4e, 0x0a, 0x71, 0xec, 0x45,
	0x59, 0xea, 0x89, 0xac, 0x9a, 0xda, 0x9e, 0x62, 0x17, 0x82, 0x1f, 0xc0, 0xd2, 0x61, 0x94, 0x7a,
	0x49, 0xf4, 0x86, 0x4e, 0x44, 0x5b, 0x28, 0xba, 0x68, 0x0e, 0x0a, 0xe1, 0xdb, 0x00, 0xb9, 0x84,
	0x69, 0x05, 0x27, 0x6d, 0x2c, 0x7c, 0x5b, 0x72, 0x14, 0xa0, 0x3c, 0x87, 0xa6, 0x8a, 0x9a, 0x5b,
	0x80, 0x55, 0x5b, 0xbd, 0x70, 0x3d, 0xaa, 0x59, 0x36, 0x85, 0xd3, 0xda, 0xe4, 0x60, 0xd2, 0x9f,
	0x82, 0x5b, 0x1d, 0xb4, 0xf5, 0xfe, 0x65, 0x6c, 0x29, 0x15, 0x6d, 0xae, 0x64, 0x83, 0x7c, 0x0a,
	0x4d, 0x95, 0x38, 0xb7, 0xba, 0x68, 0xee, 0xd1, 0x85, 0xe6, 0x4a, 0xfd, 0x6a, 0xe2, 0xd3, 0x26,
	0xca, 0x68, 0x37, 0x3f, 0x8d, 0x76, 0x5f, 0xc0, 0x22, 0x35, 0x80, 0xa2, 0x96, 0x07, 0xb7, 0x7a,
	0xe8, 0x70, 0xe3, 0x42, 0x87, 0xd3, 0x48, 0xa4, 0x7d, 0x2e, 0xd0, 0x29, 0x2e, 0xb7, 0xb7, 0x60,
	0x51, 0x69, 0xec, 0x44, 0x59, 0x48, 0x73, 0x41, 0x8f, 0x85, 0x9c, 0x0d, 0x7f, 0x13, 0x3b, 0xbc,
	0xeb, 0x54, 0xfd, 0x4d, 0xa4, 0xb7, 0xb0, 0xab, 0x25, 0xbd, 0x65, 0x7f, 0x5d, 0x81, 0x9e, 0x52,
	0x3a, 0x30, 0x2b, 0x6c, 0x11, 0x6a, 0x19, 0xe3, 0x7a, 0xeb, 0xcb, 0xcf, 0xe9, 0x2d, 0x59, 0x7d,
	0xeb, 0x96, 0xac, 0x95, 0xb7, 0xe4, 0xb9, 0x43, 0x78, 0x3e, 0x86, 0xd9, 0xdf, 0x17, 0x41, 0xec,
	0xa5, 0xfe, 0x7f, 0x19, 0x84, 0x5c, 0xd5, 0xb1, 0x9b, 0x25, 0xde, 0x89, 0x7e, 0x3a, 0xc8, 0x55,
	0x1d, 0x1f, 0x20, 0x2d, 0x0f, 0x69, 0xea, 0xeb, 0x3d, 0xae, 0xe1, 0x89, 0x1a, 0xff, 0x45, 0xa0,
	0x8d, 0x72, 0xa0, 0x4f, 0xcc, 0xf3, 0x41, 0x83, 0xd5, 0xd9, 0x28, 0xaf, 0x41, 0xd3, 0xf7, 0xf2,
	0x40, 0xc2, 0x8a, 0x82, 0x8e, 0x86, 0x24, 0xf7, 0x03, 0xfb, 0xbb, 0x1a, 0x74, 0x4a, 0xcf, 0xaf,
	0x59, 0x00, 0xf4, 0x08, 0x07, 0x5a, 0x4e, 0x3e, 0xcb, 0x68, 0x6a, 0x20, 0xa2, 0xaa, 0x26, 0x4f,
	0x9d, 0x7c, 0x96, 0xd1, 0x54, 0xe3, 0xc4, 0x3a, 0xfc, 0x5f, 0x4b, 0xfb, 0x09, 0xe3, 0xd4, 0x88,
	0xd7, 0x8a, 0xf9, 0x1f, 0x45, 0x62, 0x47, 0x9e, 0x4c, 0xe4, 0xf5, 0xfc, 0x4f, 0xc9, 0x2b, 0x04,
	0x5a, 0x52, 0x47, 0x65, 0xf9, 0x29, 0x38, 0x9c, 0x3b, 0x0d, 0x87, 0xfb, 0x93, 0xc1, 0x56, 0x3b,
	0xfc, 0xe1, 0xec, 0xb7, 0xa7, 0x9a, 0xea, 0xbd, 0x54, 0xe4, 0x27, 0xa7, 0x47, 0x7b, 0x7f, 0x32,
	0x88, 0xcd, 0xcb, 0x98, 0x52, 0x77, 0x30, 0x65, 0xca, 0x4c, 0xe1, 0x32, 0xcc, 0x21, 0x42, 0x21,
	0x5c, 0x75, 0x1d, 0x45, 0x90, 0x1b, 0xd0, 0x3a, 0xf4, 0x92, 0x64, 0xe0, 0xf9, 0x31, 0x22, 0x54,
	0xcb, 0x29, 0x68, 0x3b, 0x81, 0xa5, 0x33, 0x01, 0x92, 0xa7, 0x67, 0x5e, 0x87, 0x97, 0x59, 0xfa,
	0xa5, 0xae, 0xbc, 0x0a, 0x0d, 0x95, 0x9d, 0x9e, 0x38, 0x4d, 0xd9, 0xa1, 0xf1, 0x56, 0xca, 0xe1,
	0xdf, 0x7b, 0x23, 0x50, 0xe7, 0x5e, 0x62, 0x7c, 0xe1, 0xb7, 0xfd, 0x77, 0x1d, 0x40, 0xb5, 0xac,
	0x7c, 0x27, 0xcf, 0xea, 0xba, 0x6b, 0xd0, 0xcc, 0x62, 0x7c, 0x6b, 0x9b, 0x60, 0xb3, 0x18, 0x75,
	0x6e, 0x42, 0x3b, 0xa0, 0x7e, 0xec, 0xf2, 0xe8, 0x0d, 0xd5, 0xe3, 0xd5, 0x92, 0x8c, 0x7e, 0xf4,
	0x86, 0x92, 0x6d, 0xa8, 0xcb, 0x6f, 0xab, 0x8e, 0x37, 0xb6, 0x36, 0x1b, 0xc9, 0x26, 0xb8, 0xa4,
	0x2f, 0x0c, 0x75, 0x71, 0x19, 0x86, 0x47, 0x87, 0x87, 0x09, 0x75, 0xb9, 0xa0, 0x99, 0x6e, 0xb2,
	0x8e, 0xe6, 0xf5, 0x05, 0xcd, 0x64, 0x13, 0x9a, 0x95, 0x13, 0xe0, 0x48, 0xb6, 0x9c, 0x09, 0x43,
	0xbe, 0x9e, 0x8d, 0x81, 0x53, 0x3b, 0x6d, 0x41, 0xf3, 0x8b, 0x3d, 0xf5, 0x21, 0x2c, 0x87, 0x4c,
	0x3a, 0x42, 0xc8, 0x3c, 0xbd, 0xd7, 0x88, 0x3c, 0x53, 0x68, 0x5a, 0x68, 0xbc, 0x04, 0x28, 0x9e,
	0xfb, 0xdc, 0x6a, 0x63, 0x9e, 0xef, 0xcd, 0xce, 0xd3, 0x40, 0xa9, 0xce, 0xb2, 0x6d, 0xfe, 0x0e,
	0xb8, 0x34, 0x56, 0x60, 0x8e, 0x59, 0x85, 0x17, 0x18, 0x33, 0x90, 0x68, 0x8c, 0x19, 0x88, 0xe2,
	0xf2, 0x29, 0x62, 0x06, 0xa6, 0x73, 0x99, 0xa7, 0xc8, 0xf9, 0x1b, 0xeb, 0x2e, 0x74, 0xa2, 0x34,
	0x2a, 0x5e, 0x22, 0xcb, 0x58, 0x08, 0x90, 0x2c, 0x0d, 0x00, 0x0f, 0xa0, 0xa7, 0x04, 0xe4, 0xff,
	0x1e, 0x36, 0xd8, 0x15, 0xec, 0x8f, 0x2e, 0xca, 0x78, 0x3c, 0xec, 0x7b, 0x89, 0xd8, 0x5e, 0xfe,
	0xe1, 0xcf, 0x3b, 0x95, 0xcf, 0x7b, 0xc7, 0xe6, 0xdf, 0x5e, 0x9c, 0x64, 0x94, 0x0f, 0x1a, 0xf8,
	0x3f, 0xfe, 0xd1, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2a, 0x3d, 0xe9, 0xcd, 0xff, 0x0f, 0x00,
	0x00,
}

func (this *GenesisState) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GenesisState)
	if !ok {
		that2, ok := that.(GenesisState)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.NextEpochId != that1.NextEpochId {
		return false
	}
	if !this.Epoch.Equal(that1.Epoch) {
		return false
	}
	if !this.Dkg.Equal(that1.Dkg) {
		return false
	}
	if !this.Params.Equal(&that1.Params) {
		return false
	}
	if !this.Beacon.Equal(that1.Beacon) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.SlashBpsDkg != that1.SlashBpsDkg {
		return false
	}
	if this.SlashBpsHandDealer != that1.SlashBpsHandDealer {
		return false
	}
	if this.JailSecondsDkg != that1.JailSecondsDkg {
		return false
	}
	if this.JailSecondsHandDealer != that1.JailSecondsHandDealer {
		return false
	}
	if this.DkgVersion != that1.DkgVersion {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *DealerMember) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DealerMember)
	if !ok {
		that2, ok := that.(DealerMember)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Validator != that1.Validator {
		return false
	}
	if this.Index != that1.Index {
		return false
	}
	if !bytes.Equal(this.PubShare, that1.PubShare) {
		return false
	}
	if !bytes.Equal(this.ConsPubkey, that1.ConsPubkey) {
		return false
	}
	if this.Power != that1.Power {
		return false
	}
	if !bytes.Equal(this.EphemeralPubkey, that1.EphemeralPubkey) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *DealerEpoch) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DealerEpoch)
	if !ok {
		that2, ok := that.(DealerEpoch)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.EpochId != that1.EpochId {
		return false
	}
	if this.Threshold != that1.Threshold {
		return false
	}
	if !bytes.Equal(this.PkEpoch, that1.PkEpoch) {
		return false
	}
	if !bytes.Equal(this.TranscriptRoot, that1.TranscriptRoot) {
		return false
	}
	if this.StartHeight != that1.StartHeight {
		return false
	}
	if len(this.Slashed) != len(that1.Slashed) {
		return false
	}
	for i := range this.Slashed {
		if this.Slashed[i] != that1.Slashed[i] {
			return false
		}
	}
	if len(this.Members) != len(that1.Members) {
		return false
	}
	for i := range this.Members {
		if !this.Members[i].Equal(&that1.Members[i]) {
			return false
		}
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *DealerDKGCommit) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DealerDKGCommit)
	if !ok {
		that2, ok := that.(DealerDKGCommit)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Dealer != that1.Dealer {
		return false
	}
	if len(this.Commitments) != len(that1.Commitments) {
		return false
	}
	for i := range this.Commitments {
		if !bytes.Equal(this.Commitments[i], that1.Commitments[i]) {
			return false
		}
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *DealerDKGEncryptedShare) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DealerDKGEncryptedShare)
	if !ok {
		that2, ok := that.(DealerDKGEncryptedShare)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Dealer != that1.Dealer {
		return false
	}
	if this.RecipientIndex != that1.RecipientIndex {
		return false
	}
	if !bytes.Equal(this.U, that1.U) {
		return false
	}
	if !bytes.Equal(this.V, that1.V) {
		return false
	}
	if !bytes.Equal(this.Proof, that1.Proof) {
		return false
	}
	if !bytes.Equal(this.ScalarCt, that1.ScalarCt) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *DealerDKGComplaint) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DealerDKGComplaint)
	if !ok {
		that2, ok := that.(DealerDKGComplaint)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.EpochId != that1.EpochId {
		return false
	}
	if this.Complainer != that1.Complainer {
		return false
	}
	if this.Dealer != that1.Dealer {
		return false
	}
	if this.Kind != that1.Kind {
		return false
	}
	if !bytes.Equal(this.ShareMsg, that1.ShareMsg) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *DealerDKGShareReveal) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DealerDKGShareReveal)
	if !ok {
		that2, ok := that.(DealerDKGShareReveal)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.EpochId != that1.EpochId {
		return false
	}
	if this.Dealer != that1.Dealer {
		return false
	}
	if this.To != that1.To {
		return false
	}
	if !bytes.Equal(this.Share, that1.Share) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *DealerDKG) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DealerDKG)
	if !ok {
		that2, ok := that.(DealerDKG)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.EpochId != that1.EpochId {
		return false
	}
	if this.Threshold != that1.Threshold {
		return false
	}
	if len(this.Members) != len(that1.Members) {
		return false
	}
	for i := range this.Members {
		if !this.Members[i].Equal(&that1.Members[i]) {
			return false
		}
	}
	if this.StartHeight != that1.StartHeight {
		return false
	}
	if this.CommitDeadline != that1.CommitDeadline {
		return false
	}
	if this.ComplaintDeadline != that1.ComplaintDeadline {
		return false
	}
	if this.RevealDeadline != that1.RevealDeadline {
		return false
	}
	if this.FinalizeDeadline != that1.FinalizeDeadline {
		return false
	}
	if !bytes.Equal(this.RandEpoch, that1.RandEpoch) {
		return false
	}
	if len(this.Commits) != len(that1.Commits) {
		return false
	}
	for i := range this.Commits {
		if !this.Commits[i].Equal(&that1.Commits[i]) {
			return false
		}
	}
	if len(this.Complaints) != len(that1.Complaints) {
		return false
	}
	for i := range this.Complaints {
		if !this.Complaints[i].Equal(&that1.Complaints[i]) {
			return false
		}
	}
	if len(this.Reveals) != len(that1.Reveals) {
		return false
	}
	for i := range this.Reveals {
		if !this.Reveals[i].Equal(&that1.Reveals[i]) {
			return false
		}
	}
	if len(this.Slashed) != len(that1.Slashed) {
		return false
	}
	for i := range this.Slashed {
		if this.Slashed[i] != that1.Slashed[i] {
			return false
		}
	}
	if len(this.EncryptedShares) != len(that1.EncryptedShares) {
		return false
	}
	for i := range this.EncryptedShares {
		if !this.EncryptedShares[i].Equal(&that1.EncryptedShares[i]) {
			return false
		}
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *DealerCiphertext) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DealerCiphertext)
	if !ok {
		that2, ok := that.(DealerCiphertext)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.C1, that1.C1) {
		return false
	}
	if !bytes.Equal(this.C2, that1.C2) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *DealerPubShare) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DealerPubShare)
	if !ok {
		that2, ok := that.(DealerPubShare)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Pos != that1.Pos {
		return false
	}
	if this.Validator != that1.Validator {
		return false
	}
	if this.Index != that1.Index {
		return false
	}
	if !bytes.Equal(this.Share, that1.Share) {
		return false
	}
	if !bytes.Equal(this.Proof, that1.Proof) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *DealerEncShare) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DealerEncShare)
	if !ok {
		that2, ok := that.(DealerEncShare)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Pos != that1.Pos {
		return false
	}
	if this.Validator != that1.Validator {
		return false
	}
	if this.Index != that1.Index {
		return false
	}
	if !bytes.Equal(this.PkPlayer, that1.PkPlayer) {
		return false
	}
	if !bytes.Equal(this.EncShare, that1.EncShare) {
		return false
	}
	if !bytes.Equal(this.Proof, that1.Proof) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *DealerReveal) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DealerReveal)
	if !ok {
		that2, ok := that.(DealerReveal)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Pos != that1.Pos {
		return false
	}
	if this.CardId != that1.CardId {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *BeaconState) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*BeaconState)
	if !ok {
		that2, ok := that.(BeaconState)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.EpochId != that1.EpochId {
		return false
	}
	if this.CommitOpenHeight != that1.CommitOpenHeight {
		return false
	}
	if this.CommitCloseHeight != that1.CommitCloseHeight {
		return false
	}
	if this.RevealCloseHeight != that1.RevealCloseHeight {
		return false
	}
	if this.Threshold != that1.Threshold {
		return false
	}
	if len(this.Commits) != len(that1.Commits) {
		return false
	}
	for i := range this.Commits {
		if !this.Commits[i].Equal(&that1.Commits[i]) {
			return false
		}
	}
	if len(this.Reveals) != len(that1.Reveals) {
		return false
	}
	for i := range this.Reveals {
		if !this.Reveals[i].Equal(&that1.Reveals[i]) {
			return false
		}
	}
	if !bytes.Equal(this.Final, that1.Final) {
		return false
	}
	if this.Fallback != that1.Fallback {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *BeaconCommitEntry) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*BeaconCommitEntry)
	if !ok {
		that2, ok := that.(BeaconCommitEntry)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Validator != that1.Validator {
		return false
	}
	if !bytes.Equal(this.Commit, that1.Commit) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *BeaconRevealEntry) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*BeaconRevealEntry)
	if !ok {
		that2, ok := that.(BeaconRevealEntry)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Validator != that1.Validator {
		return false
	}
	if !bytes.Equal(this.Salt, that1.Salt) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *DealerHand) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DealerHand)
	if !ok {
		that2, ok := that.(DealerHand)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.EpochId != that1.EpochId {
		return false
	}
	if !bytes.Equal(this.PkHand, that1.PkHand) {
		return false
	}
	if this.DeckSize != that1.DeckSize {
		return false
	}
	if len(this.Deck) != len(that1.Deck) {
		return false
	}
	for i := range this.Deck {
		if !this.Deck[i].Equal(&that1.Deck[i]) {
			return false
		}
	}
	if this.ShuffleStep != that1.ShuffleStep {
		return false
	}
	if this.Finalized != that1.Finalized {
		return false
	}
	if this.ShuffleDeadline != that1.ShuffleDeadline {
		return false
	}
	if this.HoleSharesDeadline != that1.HoleSharesDeadline {
		return false
	}
	if len(this.PubShares) != len(that1.PubShares) {
		return false
	}
	for i := range this.PubShares {
		if !this.PubShares[i].Equal(&that1.PubShares[i]) {
			return false
		}
	}
	if len(this.EncShares) != len(that1.EncShares) {
		return false
	}
	for i := range this.EncShares {
		if !this.EncShares[i].Equal(&that1.EncShares[i]) {
			return false
		}
	}
	if len(this.Reveals) != len(that1.Reveals) {
		return false
	}
	for i := range this.Reveals {
		if !this.Reveals[i].Equal(&that1.Reveals[i]) {
			return false
		}
	}
	if this.InitHeight != that1.InitHeight {
		return false
	}
	if !bytes.Equal(this.InitHashSalt, that1.InitHashSalt) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
