// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: onchainpoker/dealer/v1/dealer.proto

package types

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GenesisState struct {
	NextEpochId          uint64       `protobuf:"varint,1,opt,name=next_epoch_id,json=nextEpochId,proto3" json:"next_epoch_id,omitempty"`
	Epoch                *DealerEpoch `protobuf:"bytes,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Dkg                  *DealerDKG   `protobuf:"bytes,3,opt,name=dkg,proto3" json:"dkg,omitempty"`
	Params               Params       `protobuf:"bytes,4,opt,name=params,proto3" json:"params"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_34672eba2f8d03b5, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenesisState.Unmarshal(m, b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return xxx_messageInfo_GenesisState.Size(m)
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetNextEpochId() uint64 {
	if m != nil {
		return m.NextEpochId
	}
	return 0
}

func (m *GenesisState) GetEpoch() *DealerEpoch {
	if m != nil {
		return m.Epoch
	}
	return nil
}

func (m *GenesisState) GetDkg() *DealerDKG {
	if m != nil {
		return m.Dkg
	}
	return nil
}

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// Params defines the x/dealer module parameters.
//
// NOTE: Dealer faults are intended to map to real PoS stake risk:
// slashing and (optional) jailing of the underlying validator.
type Params struct {
	// Slash fraction (in basis points, 1 bps = 0.01%) for objective DKG faults.
	SlashBpsDkg uint32 `protobuf:"varint,1,opt,name=slash_bps_dkg,json=slashBpsDkg,proto3" json:"slash_bps_dkg,omitempty"`
	// Slash fraction (in basis points, 1 bps = 0.01%) for objective per-hand dealer faults.
	SlashBpsHandDealer uint32 `protobuf:"varint,2,opt,name=slash_bps_hand_dealer,json=slashBpsHandDealer,proto3" json:"slash_bps_hand_dealer,omitempty"`
	// Jail duration (in seconds) for objective DKG faults.
	JailSecondsDkg uint64 `protobuf:"varint,3,opt,name=jail_seconds_dkg,json=jailSecondsDkg,proto3" json:"jail_seconds_dkg,omitempty"`
	// Jail duration (in seconds) for objective per-hand dealer faults.
	JailSecondsHandDealer uint64   `protobuf:"varint,4,opt,name=jail_seconds_hand_dealer,json=jailSecondsHandDealer,proto3" json:"jail_seconds_hand_dealer,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_34672eba2f8d03b5, []int{1}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Params.Unmarshal(m, b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Params.Marshal(b, m, deterministic)
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return xxx_messageInfo_Params.Size(m)
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetSlashBpsDkg() uint32 {
	if m != nil {
		return m.SlashBpsDkg
	}
	return 0
}

func (m *Params) GetSlashBpsHandDealer() uint32 {
	if m != nil {
		return m.SlashBpsHandDealer
	}
	return 0
}

func (m *Params) GetJailSecondsDkg() uint64 {
	if m != nil {
		return m.JailSecondsDkg
	}
	return 0
}

func (m *Params) GetJailSecondsHandDealer() uint64 {
	if m != nil {
		return m.JailSecondsHandDealer
	}
	return 0
}

type DealerMember struct {
	// Validator operator address (valoper).
	Validator string `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	// Shamir x-coordinate (non-zero).
	Index uint32 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	// 32-byte ristretto point (Y_i), set at epoch finalize.
	PubShare []byte `protobuf:"bytes,3,opt,name=pub_share,json=pubShare,proto3" json:"pub_share,omitempty"`
	// 32-byte ed25519 consensus pubkey snapshot (for DKG share-msg signatures).
	ConsPubkey []byte `protobuf:"bytes,4,opt,name=cons_pubkey,json=consPubkey,proto3" json:"cons_pubkey,omitempty"`
	// Consensus power at committee selection time (used for slashing distribution height/power).
	Power                int64    `protobuf:"varint,5,opt,name=power,proto3" json:"power,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DealerMember) Reset()         { *m = DealerMember{} }
func (m *DealerMember) String() string { return proto.CompactTextString(m) }
func (*DealerMember) ProtoMessage()    {}
func (*DealerMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_34672eba2f8d03b5, []int{2}
}
func (m *DealerMember) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealerMember.Unmarshal(m, b)
}
func (m *DealerMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealerMember.Marshal(b, m, deterministic)
}
func (m *DealerMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealerMember.Merge(m, src)
}
func (m *DealerMember) XXX_Size() int {
	return xxx_messageInfo_DealerMember.Size(m)
}
func (m *DealerMember) XXX_DiscardUnknown() {
	xxx_messageInfo_DealerMember.DiscardUnknown(m)
}

var xxx_messageInfo_DealerMember proto.InternalMessageInfo

func (m *DealerMember) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

func (m *DealerMember) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *DealerMember) GetPubShare() []byte {
	if m != nil {
		return m.PubShare
	}
	return nil
}

func (m *DealerMember) GetConsPubkey() []byte {
	if m != nil {
		return m.ConsPubkey
	}
	return nil
}

func (m *DealerMember) GetPower() int64 {
	if m != nil {
		return m.Power
	}
	return 0
}

type DealerEpoch struct {
	EpochId   uint64 `protobuf:"varint,1,opt,name=epoch_id,json=epochId,proto3" json:"epoch_id,omitempty"`
	Threshold uint32 `protobuf:"varint,2,opt,name=threshold,proto3" json:"threshold,omitempty"`
	// 32-byte ristretto point.
	PkEpoch []byte `protobuf:"bytes,3,opt,name=pk_epoch,json=pkEpoch,proto3" json:"pk_epoch,omitempty"`
	// sha256 (v0 placeholder) over the accepted transcript view.
	TranscriptRoot []byte `protobuf:"bytes,4,opt,name=transcript_root,json=transcriptRoot,proto3" json:"transcript_root,omitempty"`
	// Distribution/obligation height captured at committee selection time (typically the DKG start height).
	// Used for slashing so validators cannot evade by unbonding immediately after being selected.
	StartHeight int64 `protobuf:"varint,7,opt,name=start_height,json=startHeight,proto3" json:"start_height,omitempty"`
	// Canonical ordering: lexicographically ascending by validator.
	Slashed              []string       `protobuf:"bytes,5,rep,name=slashed,proto3" json:"slashed,omitempty"`
	Members              []DealerMember `protobuf:"bytes,6,rep,name=members,proto3" json:"members"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DealerEpoch) Reset()         { *m = DealerEpoch{} }
func (m *DealerEpoch) String() string { return proto.CompactTextString(m) }
func (*DealerEpoch) ProtoMessage()    {}
func (*DealerEpoch) Descriptor() ([]byte, []int) {
	return fileDescriptor_34672eba2f8d03b5, []int{3}
}
func (m *DealerEpoch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealerEpoch.Unmarshal(m, b)
}
func (m *DealerEpoch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealerEpoch.Marshal(b, m, deterministic)
}
func (m *DealerEpoch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealerEpoch.Merge(m, src)
}
func (m *DealerEpoch) XXX_Size() int {
	return xxx_messageInfo_DealerEpoch.Size(m)
}
func (m *DealerEpoch) XXX_DiscardUnknown() {
	xxx_messageInfo_DealerEpoch.DiscardUnknown(m)
}

var xxx_messageInfo_DealerEpoch proto.InternalMessageInfo

func (m *DealerEpoch) GetEpochId() uint64 {
	if m != nil {
		return m.EpochId
	}
	return 0
}

func (m *DealerEpoch) GetThreshold() uint32 {
	if m != nil {
		return m.Threshold
	}
	return 0
}

func (m *DealerEpoch) GetPkEpoch() []byte {
	if m != nil {
		return m.PkEpoch
	}
	return nil
}

func (m *DealerEpoch) GetTranscriptRoot() []byte {
	if m != nil {
		return m.TranscriptRoot
	}
	return nil
}

func (m *DealerEpoch) GetStartHeight() int64 {
	if m != nil {
		return m.StartHeight
	}
	return 0
}

func (m *DealerEpoch) GetSlashed() []string {
	if m != nil {
		return m.Slashed
	}
	return nil
}

func (m *DealerEpoch) GetMembers() []DealerMember {
	if m != nil {
		return m.Members
	}
	return nil
}

type DealerDKGCommit struct {
	Dealer               string   `protobuf:"bytes,1,opt,name=dealer,proto3" json:"dealer,omitempty"`
	Commitments          [][]byte `protobuf:"bytes,2,rep,name=commitments,proto3" json:"commitments,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DealerDKGCommit) Reset()         { *m = DealerDKGCommit{} }
func (m *DealerDKGCommit) String() string { return proto.CompactTextString(m) }
func (*DealerDKGCommit) ProtoMessage()    {}
func (*DealerDKGCommit) Descriptor() ([]byte, []int) {
	return fileDescriptor_34672eba2f8d03b5, []int{4}
}
func (m *DealerDKGCommit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealerDKGCommit.Unmarshal(m, b)
}
func (m *DealerDKGCommit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealerDKGCommit.Marshal(b, m, deterministic)
}
func (m *DealerDKGCommit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealerDKGCommit.Merge(m, src)
}
func (m *DealerDKGCommit) XXX_Size() int {
	return xxx_messageInfo_DealerDKGCommit.Size(m)
}
func (m *DealerDKGCommit) XXX_DiscardUnknown() {
	xxx_messageInfo_DealerDKGCommit.DiscardUnknown(m)
}

var xxx_messageInfo_DealerDKGCommit proto.InternalMessageInfo

func (m *DealerDKGCommit) GetDealer() string {
	if m != nil {
		return m.Dealer
	}
	return ""
}

func (m *DealerDKGCommit) GetCommitments() [][]byte {
	if m != nil {
		return m.Commitments
	}
	return nil
}

type DealerDKGComplaint struct {
	EpochId              uint64   `protobuf:"varint,1,opt,name=epoch_id,json=epochId,proto3" json:"epoch_id,omitempty"`
	Complainer           string   `protobuf:"bytes,2,opt,name=complainer,proto3" json:"complainer,omitempty"`
	Dealer               string   `protobuf:"bytes,3,opt,name=dealer,proto3" json:"dealer,omitempty"`
	Kind                 string   `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	ShareMsg             []byte   `protobuf:"bytes,5,opt,name=share_msg,json=shareMsg,proto3" json:"share_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DealerDKGComplaint) Reset()         { *m = DealerDKGComplaint{} }
func (m *DealerDKGComplaint) String() string { return proto.CompactTextString(m) }
func (*DealerDKGComplaint) ProtoMessage()    {}
func (*DealerDKGComplaint) Descriptor() ([]byte, []int) {
	return fileDescriptor_34672eba2f8d03b5, []int{5}
}
func (m *DealerDKGComplaint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealerDKGComplaint.Unmarshal(m, b)
}
func (m *DealerDKGComplaint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealerDKGComplaint.Marshal(b, m, deterministic)
}
func (m *DealerDKGComplaint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealerDKGComplaint.Merge(m, src)
}
func (m *DealerDKGComplaint) XXX_Size() int {
	return xxx_messageInfo_DealerDKGComplaint.Size(m)
}
func (m *DealerDKGComplaint) XXX_DiscardUnknown() {
	xxx_messageInfo_DealerDKGComplaint.DiscardUnknown(m)
}

var xxx_messageInfo_DealerDKGComplaint proto.InternalMessageInfo

func (m *DealerDKGComplaint) GetEpochId() uint64 {
	if m != nil {
		return m.EpochId
	}
	return 0
}

func (m *DealerDKGComplaint) GetComplainer() string {
	if m != nil {
		return m.Complainer
	}
	return ""
}

func (m *DealerDKGComplaint) GetDealer() string {
	if m != nil {
		return m.Dealer
	}
	return ""
}

func (m *DealerDKGComplaint) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *DealerDKGComplaint) GetShareMsg() []byte {
	if m != nil {
		return m.ShareMsg
	}
	return nil
}

type DealerDKGShareReveal struct {
	EpochId              uint64   `protobuf:"varint,1,opt,name=epoch_id,json=epochId,proto3" json:"epoch_id,omitempty"`
	Dealer               string   `protobuf:"bytes,2,opt,name=dealer,proto3" json:"dealer,omitempty"`
	To                   string   `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Share                []byte   `protobuf:"bytes,4,opt,name=share,proto3" json:"share,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DealerDKGShareReveal) Reset()         { *m = DealerDKGShareReveal{} }
func (m *DealerDKGShareReveal) String() string { return proto.CompactTextString(m) }
func (*DealerDKGShareReveal) ProtoMessage()    {}
func (*DealerDKGShareReveal) Descriptor() ([]byte, []int) {
	return fileDescriptor_34672eba2f8d03b5, []int{6}
}
func (m *DealerDKGShareReveal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealerDKGShareReveal.Unmarshal(m, b)
}
func (m *DealerDKGShareReveal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealerDKGShareReveal.Marshal(b, m, deterministic)
}
func (m *DealerDKGShareReveal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealerDKGShareReveal.Merge(m, src)
}
func (m *DealerDKGShareReveal) XXX_Size() int {
	return xxx_messageInfo_DealerDKGShareReveal.Size(m)
}
func (m *DealerDKGShareReveal) XXX_DiscardUnknown() {
	xxx_messageInfo_DealerDKGShareReveal.DiscardUnknown(m)
}

var xxx_messageInfo_DealerDKGShareReveal proto.InternalMessageInfo

func (m *DealerDKGShareReveal) GetEpochId() uint64 {
	if m != nil {
		return m.EpochId
	}
	return 0
}

func (m *DealerDKGShareReveal) GetDealer() string {
	if m != nil {
		return m.Dealer
	}
	return ""
}

func (m *DealerDKGShareReveal) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *DealerDKGShareReveal) GetShare() []byte {
	if m != nil {
		return m.Share
	}
	return nil
}

type DealerDKG struct {
	EpochId              uint64                 `protobuf:"varint,1,opt,name=epoch_id,json=epochId,proto3" json:"epoch_id,omitempty"`
	Threshold            uint32                 `protobuf:"varint,2,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Members              []DealerMember         `protobuf:"bytes,3,rep,name=members,proto3" json:"members"`
	StartHeight          int64                  `protobuf:"varint,4,opt,name=start_height,json=startHeight,proto3" json:"start_height,omitempty"`
	CommitDeadline       int64                  `protobuf:"varint,5,opt,name=commit_deadline,json=commitDeadline,proto3" json:"commit_deadline,omitempty"`
	ComplaintDeadline    int64                  `protobuf:"varint,6,opt,name=complaint_deadline,json=complaintDeadline,proto3" json:"complaint_deadline,omitempty"`
	RevealDeadline       int64                  `protobuf:"varint,7,opt,name=reveal_deadline,json=revealDeadline,proto3" json:"reveal_deadline,omitempty"`
	FinalizeDeadline     int64                  `protobuf:"varint,8,opt,name=finalize_deadline,json=finalizeDeadline,proto3" json:"finalize_deadline,omitempty"`
	RandEpoch            []byte                 `protobuf:"bytes,9,opt,name=rand_epoch,json=randEpoch,proto3" json:"rand_epoch,omitempty"`
	Commits              []DealerDKGCommit      `protobuf:"bytes,10,rep,name=commits,proto3" json:"commits"`
	Complaints           []DealerDKGComplaint   `protobuf:"bytes,11,rep,name=complaints,proto3" json:"complaints"`
	Reveals              []DealerDKGShareReveal `protobuf:"bytes,12,rep,name=reveals,proto3" json:"reveals"`
	Slashed              []string               `protobuf:"bytes,13,rep,name=slashed,proto3" json:"slashed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *DealerDKG) Reset()         { *m = DealerDKG{} }
func (m *DealerDKG) String() string { return proto.CompactTextString(m) }
func (*DealerDKG) ProtoMessage()    {}
func (*DealerDKG) Descriptor() ([]byte, []int) {
	return fileDescriptor_34672eba2f8d03b5, []int{7}
}
func (m *DealerDKG) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealerDKG.Unmarshal(m, b)
}
func (m *DealerDKG) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealerDKG.Marshal(b, m, deterministic)
}
func (m *DealerDKG) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealerDKG.Merge(m, src)
}
func (m *DealerDKG) XXX_Size() int {
	return xxx_messageInfo_DealerDKG.Size(m)
}
func (m *DealerDKG) XXX_DiscardUnknown() {
	xxx_messageInfo_DealerDKG.DiscardUnknown(m)
}

var xxx_messageInfo_DealerDKG proto.InternalMessageInfo

func (m *DealerDKG) GetEpochId() uint64 {
	if m != nil {
		return m.EpochId
	}
	return 0
}

func (m *DealerDKG) GetThreshold() uint32 {
	if m != nil {
		return m.Threshold
	}
	return 0
}

func (m *DealerDKG) GetMembers() []DealerMember {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *DealerDKG) GetStartHeight() int64 {
	if m != nil {
		return m.StartHeight
	}
	return 0
}

func (m *DealerDKG) GetCommitDeadline() int64 {
	if m != nil {
		return m.CommitDeadline
	}
	return 0
}

func (m *DealerDKG) GetComplaintDeadline() int64 {
	if m != nil {
		return m.ComplaintDeadline
	}
	return 0
}

func (m *DealerDKG) GetRevealDeadline() int64 {
	if m != nil {
		return m.RevealDeadline
	}
	return 0
}

func (m *DealerDKG) GetFinalizeDeadline() int64 {
	if m != nil {
		return m.FinalizeDeadline
	}
	return 0
}

func (m *DealerDKG) GetRandEpoch() []byte {
	if m != nil {
		return m.RandEpoch
	}
	return nil
}

func (m *DealerDKG) GetCommits() []DealerDKGCommit {
	if m != nil {
		return m.Commits
	}
	return nil
}

func (m *DealerDKG) GetComplaints() []DealerDKGComplaint {
	if m != nil {
		return m.Complaints
	}
	return nil
}

func (m *DealerDKG) GetReveals() []DealerDKGShareReveal {
	if m != nil {
		return m.Reveals
	}
	return nil
}

func (m *DealerDKG) GetSlashed() []string {
	if m != nil {
		return m.Slashed
	}
	return nil
}

type DealerCiphertext struct {
	C1                   []byte   `protobuf:"bytes,1,opt,name=c1,proto3" json:"c1,omitempty"`
	C2                   []byte   `protobuf:"bytes,2,opt,name=c2,proto3" json:"c2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DealerCiphertext) Reset()         { *m = DealerCiphertext{} }
func (m *DealerCiphertext) String() string { return proto.CompactTextString(m) }
func (*DealerCiphertext) ProtoMessage()    {}
func (*DealerCiphertext) Descriptor() ([]byte, []int) {
	return fileDescriptor_34672eba2f8d03b5, []int{8}
}
func (m *DealerCiphertext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealerCiphertext.Unmarshal(m, b)
}
func (m *DealerCiphertext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealerCiphertext.Marshal(b, m, deterministic)
}
func (m *DealerCiphertext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealerCiphertext.Merge(m, src)
}
func (m *DealerCiphertext) XXX_Size() int {
	return xxx_messageInfo_DealerCiphertext.Size(m)
}
func (m *DealerCiphertext) XXX_DiscardUnknown() {
	xxx_messageInfo_DealerCiphertext.DiscardUnknown(m)
}

var xxx_messageInfo_DealerCiphertext proto.InternalMessageInfo

func (m *DealerCiphertext) GetC1() []byte {
	if m != nil {
		return m.C1
	}
	return nil
}

func (m *DealerCiphertext) GetC2() []byte {
	if m != nil {
		return m.C2
	}
	return nil
}

type DealerPubShare struct {
	Pos                  uint32   `protobuf:"varint,1,opt,name=pos,proto3" json:"pos,omitempty"`
	Validator            string   `protobuf:"bytes,2,opt,name=validator,proto3" json:"validator,omitempty"`
	Index                uint32   `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	Share                []byte   `protobuf:"bytes,4,opt,name=share,proto3" json:"share,omitempty"`
	Proof                []byte   `protobuf:"bytes,5,opt,name=proof,proto3" json:"proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DealerPubShare) Reset()         { *m = DealerPubShare{} }
func (m *DealerPubShare) String() string { return proto.CompactTextString(m) }
func (*DealerPubShare) ProtoMessage()    {}
func (*DealerPubShare) Descriptor() ([]byte, []int) {
	return fileDescriptor_34672eba2f8d03b5, []int{9}
}
func (m *DealerPubShare) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealerPubShare.Unmarshal(m, b)
}
func (m *DealerPubShare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealerPubShare.Marshal(b, m, deterministic)
}
func (m *DealerPubShare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealerPubShare.Merge(m, src)
}
func (m *DealerPubShare) XXX_Size() int {
	return xxx_messageInfo_DealerPubShare.Size(m)
}
func (m *DealerPubShare) XXX_DiscardUnknown() {
	xxx_messageInfo_DealerPubShare.DiscardUnknown(m)
}

var xxx_messageInfo_DealerPubShare proto.InternalMessageInfo

func (m *DealerPubShare) GetPos() uint32 {
	if m != nil {
		return m.Pos
	}
	return 0
}

func (m *DealerPubShare) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

func (m *DealerPubShare) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *DealerPubShare) GetShare() []byte {
	if m != nil {
		return m.Share
	}
	return nil
}

func (m *DealerPubShare) GetProof() []byte {
	if m != nil {
		return m.Proof
	}
	return nil
}

type DealerEncShare struct {
	Pos                  uint32   `protobuf:"varint,1,opt,name=pos,proto3" json:"pos,omitempty"`
	Validator            string   `protobuf:"bytes,2,opt,name=validator,proto3" json:"validator,omitempty"`
	Index                uint32   `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	PkPlayer             []byte   `protobuf:"bytes,4,opt,name=pk_player,json=pkPlayer,proto3" json:"pk_player,omitempty"`
	EncShare             []byte   `protobuf:"bytes,5,opt,name=enc_share,json=encShare,proto3" json:"enc_share,omitempty"`
	Proof                []byte   `protobuf:"bytes,6,opt,name=proof,proto3" json:"proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DealerEncShare) Reset()         { *m = DealerEncShare{} }
func (m *DealerEncShare) String() string { return proto.CompactTextString(m) }
func (*DealerEncShare) ProtoMessage()    {}
func (*DealerEncShare) Descriptor() ([]byte, []int) {
	return fileDescriptor_34672eba2f8d03b5, []int{10}
}
func (m *DealerEncShare) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealerEncShare.Unmarshal(m, b)
}
func (m *DealerEncShare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealerEncShare.Marshal(b, m, deterministic)
}
func (m *DealerEncShare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealerEncShare.Merge(m, src)
}
func (m *DealerEncShare) XXX_Size() int {
	return xxx_messageInfo_DealerEncShare.Size(m)
}
func (m *DealerEncShare) XXX_DiscardUnknown() {
	xxx_messageInfo_DealerEncShare.DiscardUnknown(m)
}

var xxx_messageInfo_DealerEncShare proto.InternalMessageInfo

func (m *DealerEncShare) GetPos() uint32 {
	if m != nil {
		return m.Pos
	}
	return 0
}

func (m *DealerEncShare) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

func (m *DealerEncShare) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *DealerEncShare) GetPkPlayer() []byte {
	if m != nil {
		return m.PkPlayer
	}
	return nil
}

func (m *DealerEncShare) GetEncShare() []byte {
	if m != nil {
		return m.EncShare
	}
	return nil
}

func (m *DealerEncShare) GetProof() []byte {
	if m != nil {
		return m.Proof
	}
	return nil
}

type DealerReveal struct {
	Pos                  uint32   `protobuf:"varint,1,opt,name=pos,proto3" json:"pos,omitempty"`
	CardId               uint32   `protobuf:"varint,2,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DealerReveal) Reset()         { *m = DealerReveal{} }
func (m *DealerReveal) String() string { return proto.CompactTextString(m) }
func (*DealerReveal) ProtoMessage()    {}
func (*DealerReveal) Descriptor() ([]byte, []int) {
	return fileDescriptor_34672eba2f8d03b5, []int{11}
}
func (m *DealerReveal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealerReveal.Unmarshal(m, b)
}
func (m *DealerReveal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealerReveal.Marshal(b, m, deterministic)
}
func (m *DealerReveal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealerReveal.Merge(m, src)
}
func (m *DealerReveal) XXX_Size() int {
	return xxx_messageInfo_DealerReveal.Size(m)
}
func (m *DealerReveal) XXX_DiscardUnknown() {
	xxx_messageInfo_DealerReveal.DiscardUnknown(m)
}

var xxx_messageInfo_DealerReveal proto.InternalMessageInfo

func (m *DealerReveal) GetPos() uint32 {
	if m != nil {
		return m.Pos
	}
	return 0
}

func (m *DealerReveal) GetCardId() uint32 {
	if m != nil {
		return m.CardId
	}
	return 0
}

type DealerHand struct {
	EpochId              uint64             `protobuf:"varint,1,opt,name=epoch_id,json=epochId,proto3" json:"epoch_id,omitempty"`
	PkHand               []byte             `protobuf:"bytes,2,opt,name=pk_hand,json=pkHand,proto3" json:"pk_hand,omitempty"`
	DeckSize             uint32             `protobuf:"varint,3,opt,name=deck_size,json=deckSize,proto3" json:"deck_size,omitempty"`
	Deck                 []DealerCiphertext `protobuf:"bytes,4,rep,name=deck,proto3" json:"deck"`
	ShuffleStep          uint32             `protobuf:"varint,5,opt,name=shuffle_step,json=shuffleStep,proto3" json:"shuffle_step,omitempty"`
	Finalized            bool               `protobuf:"varint,6,opt,name=finalized,proto3" json:"finalized,omitempty"`
	ShuffleDeadline      int64              `protobuf:"varint,7,opt,name=shuffle_deadline,json=shuffleDeadline,proto3" json:"shuffle_deadline,omitempty"`
	HoleSharesDeadline   int64              `protobuf:"varint,8,opt,name=hole_shares_deadline,json=holeSharesDeadline,proto3" json:"hole_shares_deadline,omitempty"`
	PubShares            []DealerPubShare   `protobuf:"bytes,9,rep,name=pub_shares,json=pubShares,proto3" json:"pub_shares"`
	EncShares            []DealerEncShare   `protobuf:"bytes,10,rep,name=enc_shares,json=encShares,proto3" json:"enc_shares"`
	Reveals              []DealerReveal     `protobuf:"bytes,11,rep,name=reveals,proto3" json:"reveals"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *DealerHand) Reset()         { *m = DealerHand{} }
func (m *DealerHand) String() string { return proto.CompactTextString(m) }
func (*DealerHand) ProtoMessage()    {}
func (*DealerHand) Descriptor() ([]byte, []int) {
	return fileDescriptor_34672eba2f8d03b5, []int{12}
}
func (m *DealerHand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealerHand.Unmarshal(m, b)
}
func (m *DealerHand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealerHand.Marshal(b, m, deterministic)
}
func (m *DealerHand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealerHand.Merge(m, src)
}
func (m *DealerHand) XXX_Size() int {
	return xxx_messageInfo_DealerHand.Size(m)
}
func (m *DealerHand) XXX_DiscardUnknown() {
	xxx_messageInfo_DealerHand.DiscardUnknown(m)
}

var xxx_messageInfo_DealerHand proto.InternalMessageInfo

func (m *DealerHand) GetEpochId() uint64 {
	if m != nil {
		return m.EpochId
	}
	return 0
}

func (m *DealerHand) GetPkHand() []byte {
	if m != nil {
		return m.PkHand
	}
	return nil
}

func (m *DealerHand) GetDeckSize() uint32 {
	if m != nil {
		return m.DeckSize
	}
	return 0
}

func (m *DealerHand) GetDeck() []DealerCiphertext {
	if m != nil {
		return m.Deck
	}
	return nil
}

func (m *DealerHand) GetShuffleStep() uint32 {
	if m != nil {
		return m.ShuffleStep
	}
	return 0
}

func (m *DealerHand) GetFinalized() bool {
	if m != nil {
		return m.Finalized
	}
	return false
}

func (m *DealerHand) GetShuffleDeadline() int64 {
	if m != nil {
		return m.ShuffleDeadline
	}
	return 0
}

func (m *DealerHand) GetHoleSharesDeadline() int64 {
	if m != nil {
		return m.HoleSharesDeadline
	}
	return 0
}

func (m *DealerHand) GetPubShares() []DealerPubShare {
	if m != nil {
		return m.PubShares
	}
	return nil
}

func (m *DealerHand) GetEncShares() []DealerEncShare {
	if m != nil {
		return m.EncShares
	}
	return nil
}

func (m *DealerHand) GetReveals() []DealerReveal {
	if m != nil {
		return m.Reveals
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "onchainpoker.dealer.v1.GenesisState")
	proto.RegisterType((*Params)(nil), "onchainpoker.dealer.v1.Params")
	proto.RegisterType((*DealerMember)(nil), "onchainpoker.dealer.v1.DealerMember")
	proto.RegisterType((*DealerEpoch)(nil), "onchainpoker.dealer.v1.DealerEpoch")
	proto.RegisterType((*DealerDKGCommit)(nil), "onchainpoker.dealer.v1.DealerDKGCommit")
	proto.RegisterType((*DealerDKGComplaint)(nil), "onchainpoker.dealer.v1.DealerDKGComplaint")
	proto.RegisterType((*DealerDKGShareReveal)(nil), "onchainpoker.dealer.v1.DealerDKGShareReveal")
	proto.RegisterType((*DealerDKG)(nil), "onchainpoker.dealer.v1.DealerDKG")
	proto.RegisterType((*DealerCiphertext)(nil), "onchainpoker.dealer.v1.DealerCiphertext")
	proto.RegisterType((*DealerPubShare)(nil), "onchainpoker.dealer.v1.DealerPubShare")
	proto.RegisterType((*DealerEncShare)(nil), "onchainpoker.dealer.v1.DealerEncShare")
	proto.RegisterType((*DealerReveal)(nil), "onchainpoker.dealer.v1.DealerReveal")
	proto.RegisterType((*DealerHand)(nil), "onchainpoker.dealer.v1.DealerHand")
}

func init() {
	proto.RegisterFile("onchainpoker/dealer/v1/dealer.proto", fileDescriptor_34672eba2f8d03b5)
}

var fileDescriptor_34672eba2f8d03b5 = []byte{
	// 1138 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0xae, 0x44, 0x59, 0x12, 0x47, 0xb2, 0xec, 0x2c, 0x9c, 0x84, 0x6d, 0x52, 0x47, 0x61, 0x8a,
	0x5a, 0xfd, 0xb3, 0x6b, 0xf7, 0x50, 0x04, 0x28, 0x50, 0xc0, 0x71, 0xe0, 0x04, 0x6e, 0x00, 0x83,
	0xbe, 0xf5, 0x42, 0x50, 0xe4, 0x5a, 0x64, 0x49, 0x71, 0x17, 0xdc, 0xb5, 0x6b, 0xfb, 0xd8, 0x7b,
	0xaf, 0x45, 0x6f, 0xbd, 0x15, 0x7d, 0x8e, 0x9e, 0xfa, 0x14, 0x3d, 0xf4, 0xdc, 0x57, 0x28, 0x50,
	0xec, 0xec, 0xf2, 0xc7, 0x3f, 0x91, 0x83, 0x20, 0xb7, 0x9d, 0x6f, 0x67, 0x66, 0x67, 0x67, 0xbe,
	0x99, 0x5d, 0x78, 0xc2, 0xf2, 0x30, 0x0e, 0x92, 0x9c, 0xb3, 0x94, 0x16, 0x5b, 0x11, 0x0d, 0x32,
	0x5a, 0x6c, 0x9d, 0x6e, 0x9b, 0xd5, 0x26, 0x2f, 0x98, 0x64, 0xe4, 0x5e, 0x53, 0x69, 0xd3, 0x6c,
	0x9d, 0x6e, 0x7f, 0xb0, 0x36, 0x63, 0x33, 0x86, 0x2a, 0x5b, 0x6a, 0xa5, 0xb5, 0xdd, 0x7f, 0x5b,
	0x30, 0xdc, 0xa7, 0x39, 0x15, 0x89, 0x38, 0x92, 0x81, 0xa4, 0xc4, 0x85, 0xe5, 0x9c, 0x9e, 0x49,
	0x9f, 0x72, 0x16, 0xc6, 0x7e, 0x12, 0x39, 0xad, 0x71, 0x6b, 0xd2, 0xf1, 0x06, 0x0a, 0x7c, 0xae,
	0xb0, 0x97, 0x11, 0xf9, 0x16, 0x96, 0x70, 0xdb, 0x69, 0x8f, 0x5b, 0x93, 0xc1, 0xce, 0x93, 0xcd,
	0x9b, 0x8f, 0xdc, 0xdc, 0xc3, 0x15, 0x5a, 0xed, 0x76, 0xfe, 0xfa, 0xfb, 0x51, 0xcb, 0xd3, 0x76,
	0xe4, 0x29, 0x58, 0x51, 0x3a, 0x73, 0x2c, 0x34, 0x7f, 0xbc, 0xd8, 0x7c, 0xef, 0x60, 0xdf, 0x18,
	0x2b, 0x1b, 0xf2, 0x0d, 0x74, 0x79, 0x50, 0x04, 0x73, 0xe1, 0x74, 0xd0, 0x7a, 0xfd, 0x75, 0xd6,
	0x87, 0xa8, 0x85, 0xa6, 0xef, 0x79, 0xc6, 0xc6, 0xfd, 0xb3, 0x05, 0x5d, 0xbd, 0xa1, 0x2e, 0x2a,
	0xb2, 0x40, 0xc4, 0xfe, 0x94, 0x0b, 0x5f, 0x45, 0xa3, 0x2e, 0xba, 0xec, 0x0d, 0x10, 0xdc, 0xe5,
	0x62, 0x2f, 0x9d, 0x91, 0x6d, 0xb8, 0x5b, 0xeb, 0xc4, 0x41, 0x1e, 0xf9, 0xda, 0x3f, 0x5e, 0x7c,
	0xd9, 0x23, 0xa5, 0xee, 0x8b, 0x20, 0x8f, 0x74, 0xb4, 0x64, 0x02, 0xab, 0x3f, 0x04, 0x49, 0xe6,
	0x0b, 0x1a, 0xb2, 0x3c, 0xd2, 0x9e, 0x2d, 0x4c, 0xe1, 0x48, 0xe1, 0x47, 0x1a, 0x56, 0xce, 0xbf,
	0x06, 0xe7, 0x92, 0x66, 0xd3, 0x7f, 0x07, 0x2d, 0xee, 0x36, 0x2c, 0xea, 0x23, 0xdc, 0x5f, 0x5a,
	0x30, 0xd4, 0xcb, 0x57, 0x74, 0x3e, 0xa5, 0x05, 0x79, 0x08, 0xf6, 0x69, 0x90, 0x25, 0x51, 0x20,
	0x59, 0x81, 0xd7, 0xb0, 0xbd, 0x1a, 0x20, 0x6b, 0xb0, 0x94, 0xe4, 0x11, 0x3d, 0x33, 0x41, 0x6b,
	0x81, 0x3c, 0x00, 0x9b, 0x9f, 0x4c, 0x7d, 0x11, 0x07, 0x05, 0xc5, 0x00, 0x87, 0x5e, 0x9f, 0x9f,
	0x4c, 0x8f, 0x94, 0x4c, 0x1e, 0xc1, 0x20, 0x64, 0xb9, 0xf0, 0xf9, 0xc9, 0x34, 0xa5, 0xe7, 0x18,
	0xcd, 0xd0, 0x03, 0x05, 0x1d, 0x22, 0xa2, 0x7c, 0x72, 0xf6, 0x23, 0x2d, 0x9c, 0xa5, 0x71, 0x6b,
	0x62, 0x79, 0x5a, 0x70, 0x7f, 0x6e, 0xc3, 0xa0, 0x51, 0x73, 0xf2, 0x3e, 0xf4, 0xaf, 0xd0, 0xa8,
	0x47, 0x0d, 0x85, 0x1e, 0x82, 0x2d, 0xe3, 0x82, 0x8a, 0x98, 0x65, 0x91, 0x09, 0xac, 0x06, 0x94,
	0x21, 0x4f, 0x35, 0x05, 0x4d, 0x6c, 0x3d, 0x9e, 0x6a, 0x9f, 0x1b, 0xb0, 0x22, 0x8b, 0x20, 0x17,
	0x61, 0x91, 0x70, 0xe9, 0x17, 0x8c, 0x49, 0x13, 0xde, 0xa8, 0x86, 0x3d, 0xc6, 0x24, 0x79, 0x0c,
	0x43, 0x21, 0x83, 0x42, 0xfa, 0x31, 0x4d, 0x66, 0xb1, 0x74, 0x7a, 0x18, 0xe9, 0x00, 0xb1, 0x17,
	0x08, 0x11, 0x07, 0x7a, 0x58, 0x41, 0x1a, 0x39, 0x4b, 0x63, 0x6b, 0x62, 0x7b, 0xa5, 0x48, 0xf6,
	0xa0, 0x37, 0xc7, 0xdc, 0x0a, 0xa7, 0x3b, 0xb6, 0x26, 0x83, 0x9d, 0x8f, 0x16, 0x93, 0x54, 0x17,
	0xc2, 0x90, 0xad, 0x34, 0x75, 0x0f, 0x60, 0xa5, 0xe2, 0xf0, 0x33, 0x36, 0x9f, 0x27, 0x92, 0xdc,
	0x83, 0xae, 0x29, 0xb1, 0xae, 0x93, 0x91, 0xc8, 0x58, 0x65, 0x5c, 0x69, 0xcc, 0x69, 0x2e, 0x85,
	0xd3, 0x1e, 0x5b, 0x93, 0xa1, 0xd7, 0x84, 0xdc, 0x5f, 0x5b, 0x40, 0x9a, 0xde, 0x78, 0x16, 0x24,
	0xb9, 0x5c, 0x94, 0xe3, 0x75, 0x80, 0xd0, 0xe8, 0x19, 0xca, 0xda, 0x5e, 0x03, 0x69, 0xc4, 0x62,
	0x5d, 0x8a, 0x85, 0x40, 0x27, 0x4d, 0xf2, 0x08, 0xf3, 0x6a, 0x7b, 0xb8, 0x56, 0x74, 0x41, 0xaa,
	0xf8, 0x73, 0x31, 0xc3, 0xa2, 0x0f, 0xbd, 0x3e, 0x02, 0xaf, 0xc4, 0xcc, 0x65, 0xb0, 0x56, 0x45,
	0x86, 0x04, 0xf2, 0xe8, 0x29, 0x0d, 0xb2, 0x45, 0xb1, 0xd5, 0x67, 0xb7, 0x2f, 0x9d, 0x3d, 0x82,
	0xb6, 0x64, 0x26, 0x9e, 0xb6, 0x64, 0x8a, 0x68, 0x9a, 0xa2, 0xba, 0xc8, 0x5a, 0x70, 0xff, 0xeb,
	0x80, 0x5d, 0x9d, 0xf8, 0xf6, 0x34, 0x6b, 0x54, 0xd9, 0x7a, 0xeb, 0x2a, 0x5f, 0x23, 0x5a, 0xe7,
	0x3a, 0xd1, 0x36, 0x60, 0x45, 0x97, 0x52, 0xf5, 0x77, 0x94, 0x25, 0x39, 0x35, 0x8d, 0x33, 0xd2,
	0xf0, 0x9e, 0x41, 0xc9, 0x17, 0x40, 0xca, 0x02, 0x35, 0x74, 0xbb, 0xa8, 0x7b, 0xa7, 0xda, 0xa9,
	0xd4, 0x37, 0x60, 0xa5, 0xc0, 0x54, 0xd7, 0xba, 0x9a, 0xe6, 0x23, 0x0d, 0x57, 0x8a, 0x9f, 0xc1,
	0x9d, 0xe3, 0x24, 0x0f, 0xb2, 0xe4, 0x82, 0xd6, 0xaa, 0x7d, 0x54, 0x5d, 0x2d, 0x37, 0x2a, 0xe5,
	0x0f, 0x01, 0x0a, 0x35, 0x8b, 0x74, 0xff, 0xd9, 0x98, 0x78, 0x5b, 0x21, 0xba, 0x03, 0xf7, 0xa1,
	0xa7, 0xa3, 0x16, 0x0e, 0x60, 0xd6, 0x36, 0x6e, 0x1d, 0xe0, 0x9a, 0xfc, 0x65, 0xe2, 0x8c, 0x35,
	0x39, 0xac, 0xf9, 0x29, 0x85, 0x33, 0x40, 0x5f, 0x9f, 0xbe, 0x89, 0x2f, 0x6d, 0x62, 0xdc, 0x35,
	0x7c, 0x90, 0xef, 0xa0, 0xa7, 0x2f, 0x2e, 0x9c, 0x21, 0xba, 0xfb, 0xfc, 0x56, 0x77, 0x0d, 0xbe,
	0x96, 0xf1, 0x19, 0x17, 0xcd, 0xf1, 0xb0, 0x7c, 0x69, 0x3c, 0xb8, 0x3b, 0xb0, 0xaa, 0x1d, 0x3c,
	0x4b, 0x78, 0x4c, 0x0b, 0x49, 0xcf, 0xa4, 0x62, 0x6e, 0xb8, 0x8d, 0xfc, 0x1b, 0x7a, 0xed, 0x70,
	0x1b, 0xe5, 0x1d, 0xe4, 0x9c, 0x92, 0x77, 0xdc, 0x9f, 0x5a, 0x30, 0xd2, 0x46, 0x87, 0xe5, 0x98,
	0x5d, 0x05, 0x8b, 0x33, 0x61, 0x1e, 0x1e, 0xb5, 0xbc, 0x3c, 0xc9, 0xdb, 0xaf, 0x9d, 0xe4, 0x56,
	0x73, 0x92, 0xdf, 0xd8, 0x22, 0x38, 0xa1, 0x0b, 0xc6, 0x8e, 0x4d, 0xb3, 0x6a, 0xc1, 0xfd, 0xbd,
	0x0a, 0xe2, 0x79, 0x1e, 0xbe, 0xcb, 0x20, 0xd4, 0x73, 0x92, 0xfa, 0x3c, 0x0b, 0xce, 0xcd, 0xeb,
	0xa5, 0x9e, 0x93, 0xf4, 0x10, 0x65, 0xb5, 0x49, 0xf3, 0xd0, 0xbc, 0x35, 0x66, 0x78, 0xd0, 0xf2,
	0xfc, 0x2a, 0xd0, 0x6e, 0x33, 0xd0, 0xa7, 0xe5, 0x13, 0x67, 0x46, 0xc9, 0xf5, 0x28, 0xef, 0x43,
	0x2f, 0x0c, 0x8a, 0x48, 0x35, 0xbd, 0x6e, 0xec, 0xae, 0x12, 0x5f, 0x46, 0xee, 0x6f, 0x1d, 0x00,
	0x6d, 0xab, 0xde, 0xcc, 0x45, 0xd3, 0xe1, 0x3e, 0xf4, 0x78, 0x8a, 0xef, 0xae, 0xa9, 0x53, 0x97,
	0xa7, 0x68, 0xf3, 0x00, 0xec, 0x88, 0x86, 0xa9, 0x2f, 0x92, 0x0b, 0x6a, 0xee, 0xd9, 0x57, 0xc0,
	0x51, 0x72, 0x41, 0xc9, 0x2e, 0x74, 0xd4, 0xda, 0xe9, 0x20, 0xc3, 0x26, 0x8b, 0x19, 0x56, 0x13,
	0xc4, 0xb0, 0x0b, 0x6d, 0x71, 0x66, 0xc4, 0x27, 0xc7, 0xc7, 0x19, 0xf5, 0x85, 0xa4, 0x1c, 0x93,
	0xa2, 0xfe, 0x1e, 0x1a, 0x3b, 0x92, 0x94, 0xab, 0x2a, 0x94, 0x9d, 0x19, 0x61, 0x6e, 0xfa, 0x5e,
	0x0d, 0x90, 0x4f, 0x60, 0xb5, 0x74, 0x70, 0xa5, 0xf5, 0x57, 0x0c, 0x5e, 0xb5, 0xf3, 0x97, 0xb0,
	0x16, 0x33, 0x75, 0x90, 0x4a, 0xb7, 0xb8, 0xda, 0xfe, 0x44, 0xed, 0x61, 0x25, 0x44, 0x65, 0x71,
	0x00, 0x50, 0xfd, 0x0d, 0x84, 0x63, 0xe3, 0x3d, 0x3f, 0x5e, 0x7c, 0xcf, 0x92, 0xd3, 0xe6, 0x96,
	0x76, 0xf9, 0x95, 0x10, 0xca, 0x59, 0x55, 0xfc, 0x72, 0x62, 0xdc, 0xe2, 0xac, 0xe4, 0x66, 0xe9,
	0xac, 0xe4, 0x8a, 0x50, 0x13, 0xbb, 0x6c, 0xf0, 0xc1, 0x9b, 0x4c, 0xec, 0x1b, 0x1b, 0x7b, 0x77,
	0xed, 0x8f, 0x7f, 0xd6, 0x5b, 0xdf, 0x8f, 0xce, 0xca, 0x2f, 0xb4, 0x3c, 0xe7, 0x54, 0x4c, 0xbb,
	0xf8, 0x23, 0xfe, 0xea, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfd, 0xb0, 0x83, 0x7c, 0x66, 0x0b,
	0x00, 0x00,
}

func (this *GenesisState) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GenesisState)
	if !ok {
		that2, ok := that.(GenesisState)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.NextEpochId != that1.NextEpochId {
		return false
	}
	if !this.Epoch.Equal(that1.Epoch) {
		return false
	}
	if !this.Dkg.Equal(that1.Dkg) {
		return false
	}
	if !this.Params.Equal(&that1.Params) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.SlashBpsDkg != that1.SlashBpsDkg {
		return false
	}
	if this.SlashBpsHandDealer != that1.SlashBpsHandDealer {
		return false
	}
	if this.JailSecondsDkg != that1.JailSecondsDkg {
		return false
	}
	if this.JailSecondsHandDealer != that1.JailSecondsHandDealer {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *DealerMember) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DealerMember)
	if !ok {
		that2, ok := that.(DealerMember)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Validator != that1.Validator {
		return false
	}
	if this.Index != that1.Index {
		return false
	}
	if !bytes.Equal(this.PubShare, that1.PubShare) {
		return false
	}
	if !bytes.Equal(this.ConsPubkey, that1.ConsPubkey) {
		return false
	}
	if this.Power != that1.Power {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *DealerEpoch) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DealerEpoch)
	if !ok {
		that2, ok := that.(DealerEpoch)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.EpochId != that1.EpochId {
		return false
	}
	if this.Threshold != that1.Threshold {
		return false
	}
	if !bytes.Equal(this.PkEpoch, that1.PkEpoch) {
		return false
	}
	if !bytes.Equal(this.TranscriptRoot, that1.TranscriptRoot) {
		return false
	}
	if this.StartHeight != that1.StartHeight {
		return false
	}
	if len(this.Slashed) != len(that1.Slashed) {
		return false
	}
	for i := range this.Slashed {
		if this.Slashed[i] != that1.Slashed[i] {
			return false
		}
	}
	if len(this.Members) != len(that1.Members) {
		return false
	}
	for i := range this.Members {
		if !this.Members[i].Equal(&that1.Members[i]) {
			return false
		}
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *DealerDKGCommit) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DealerDKGCommit)
	if !ok {
		that2, ok := that.(DealerDKGCommit)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Dealer != that1.Dealer {
		return false
	}
	if len(this.Commitments) != len(that1.Commitments) {
		return false
	}
	for i := range this.Commitments {
		if !bytes.Equal(this.Commitments[i], that1.Commitments[i]) {
			return false
		}
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *DealerDKGComplaint) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DealerDKGComplaint)
	if !ok {
		that2, ok := that.(DealerDKGComplaint)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.EpochId != that1.EpochId {
		return false
	}
	if this.Complainer != that1.Complainer {
		return false
	}
	if this.Dealer != that1.Dealer {
		return false
	}
	if this.Kind != that1.Kind {
		return false
	}
	if !bytes.Equal(this.ShareMsg, that1.ShareMsg) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *DealerDKGShareReveal) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DealerDKGShareReveal)
	if !ok {
		that2, ok := that.(DealerDKGShareReveal)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.EpochId != that1.EpochId {
		return false
	}
	if this.Dealer != that1.Dealer {
		return false
	}
	if this.To != that1.To {
		return false
	}
	if !bytes.Equal(this.Share, that1.Share) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *DealerDKG) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DealerDKG)
	if !ok {
		that2, ok := that.(DealerDKG)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.EpochId != that1.EpochId {
		return false
	}
	if this.Threshold != that1.Threshold {
		return false
	}
	if len(this.Members) != len(that1.Members) {
		return false
	}
	for i := range this.Members {
		if !this.Members[i].Equal(&that1.Members[i]) {
			return false
		}
	}
	if this.StartHeight != that1.StartHeight {
		return false
	}
	if this.CommitDeadline != that1.CommitDeadline {
		return false
	}
	if this.ComplaintDeadline != that1.ComplaintDeadline {
		return false
	}
	if this.RevealDeadline != that1.RevealDeadline {
		return false
	}
	if this.FinalizeDeadline != that1.FinalizeDeadline {
		return false
	}
	if !bytes.Equal(this.RandEpoch, that1.RandEpoch) {
		return false
	}
	if len(this.Commits) != len(that1.Commits) {
		return false
	}
	for i := range this.Commits {
		if !this.Commits[i].Equal(&that1.Commits[i]) {
			return false
		}
	}
	if len(this.Complaints) != len(that1.Complaints) {
		return false
	}
	for i := range this.Complaints {
		if !this.Complaints[i].Equal(&that1.Complaints[i]) {
			return false
		}
	}
	if len(this.Reveals) != len(that1.Reveals) {
		return false
	}
	for i := range this.Reveals {
		if !this.Reveals[i].Equal(&that1.Reveals[i]) {
			return false
		}
	}
	if len(this.Slashed) != len(that1.Slashed) {
		return false
	}
	for i := range this.Slashed {
		if this.Slashed[i] != that1.Slashed[i] {
			return false
		}
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *DealerCiphertext) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DealerCiphertext)
	if !ok {
		that2, ok := that.(DealerCiphertext)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.C1, that1.C1) {
		return false
	}
	if !bytes.Equal(this.C2, that1.C2) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *DealerPubShare) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DealerPubShare)
	if !ok {
		that2, ok := that.(DealerPubShare)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Pos != that1.Pos {
		return false
	}
	if this.Validator != that1.Validator {
		return false
	}
	if this.Index != that1.Index {
		return false
	}
	if !bytes.Equal(this.Share, that1.Share) {
		return false
	}
	if !bytes.Equal(this.Proof, that1.Proof) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *DealerEncShare) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DealerEncShare)
	if !ok {
		that2, ok := that.(DealerEncShare)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Pos != that1.Pos {
		return false
	}
	if this.Validator != that1.Validator {
		return false
	}
	if this.Index != that1.Index {
		return false
	}
	if !bytes.Equal(this.PkPlayer, that1.PkPlayer) {
		return false
	}
	if !bytes.Equal(this.EncShare, that1.EncShare) {
		return false
	}
	if !bytes.Equal(this.Proof, that1.Proof) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *DealerReveal) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DealerReveal)
	if !ok {
		that2, ok := that.(DealerReveal)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Pos != that1.Pos {
		return false
	}
	if this.CardId != that1.CardId {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *DealerHand) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DealerHand)
	if !ok {
		that2, ok := that.(DealerHand)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.EpochId != that1.EpochId {
		return false
	}
	if !bytes.Equal(this.PkHand, that1.PkHand) {
		return false
	}
	if this.DeckSize != that1.DeckSize {
		return false
	}
	if len(this.Deck) != len(that1.Deck) {
		return false
	}
	for i := range this.Deck {
		if !this.Deck[i].Equal(&that1.Deck[i]) {
			return false
		}
	}
	if this.ShuffleStep != that1.ShuffleStep {
		return false
	}
	if this.Finalized != that1.Finalized {
		return false
	}
	if this.ShuffleDeadline != that1.ShuffleDeadline {
		return false
	}
	if this.HoleSharesDeadline != that1.HoleSharesDeadline {
		return false
	}
	if len(this.PubShares) != len(that1.PubShares) {
		return false
	}
	for i := range this.PubShares {
		if !this.PubShares[i].Equal(&that1.PubShares[i]) {
			return false
		}
	}
	if len(this.EncShares) != len(that1.EncShares) {
		return false
	}
	for i := range this.EncShares {
		if !this.EncShares[i].Equal(&that1.EncShares[i]) {
			return false
		}
	}
	if len(this.Reveals) != len(that1.Reveals) {
		return false
	}
	for i := range this.Reveals {
		if !this.Reveals[i].Equal(&that1.Reveals[i]) {
			return false
		}
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
