// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: onchainpoker/dealer/v1/query.proto

package types

import (
	bytes "bytes"
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryParamsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4c3d119c3fb9701, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryParamsRequest.Unmarshal(m, b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return xxx_messageInfo_QueryParamsRequest.Size(m)
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

type QueryParamsResponse struct {
	Params               Params   `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4c3d119c3fb9701, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryParamsResponse.Unmarshal(m, b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return xxx_messageInfo_QueryParamsResponse.Size(m)
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryEpochRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryEpochRequest) Reset()         { *m = QueryEpochRequest{} }
func (m *QueryEpochRequest) String() string { return proto.CompactTextString(m) }
func (*QueryEpochRequest) ProtoMessage()    {}
func (*QueryEpochRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4c3d119c3fb9701, []int{2}
}
func (m *QueryEpochRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryEpochRequest.Unmarshal(m, b)
}
func (m *QueryEpochRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryEpochRequest.Marshal(b, m, deterministic)
}
func (m *QueryEpochRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEpochRequest.Merge(m, src)
}
func (m *QueryEpochRequest) XXX_Size() int {
	return xxx_messageInfo_QueryEpochRequest.Size(m)
}
func (m *QueryEpochRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEpochRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEpochRequest proto.InternalMessageInfo

type QueryEpochResponse struct {
	Epoch                *DealerEpoch `protobuf:"bytes,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *QueryEpochResponse) Reset()         { *m = QueryEpochResponse{} }
func (m *QueryEpochResponse) String() string { return proto.CompactTextString(m) }
func (*QueryEpochResponse) ProtoMessage()    {}
func (*QueryEpochResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4c3d119c3fb9701, []int{3}
}
func (m *QueryEpochResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryEpochResponse.Unmarshal(m, b)
}
func (m *QueryEpochResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryEpochResponse.Marshal(b, m, deterministic)
}
func (m *QueryEpochResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEpochResponse.Merge(m, src)
}
func (m *QueryEpochResponse) XXX_Size() int {
	return xxx_messageInfo_QueryEpochResponse.Size(m)
}
func (m *QueryEpochResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEpochResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEpochResponse proto.InternalMessageInfo

func (m *QueryEpochResponse) GetEpoch() *DealerEpoch {
	if m != nil {
		return m.Epoch
	}
	return nil
}

type QueryDkgRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryDkgRequest) Reset()         { *m = QueryDkgRequest{} }
func (m *QueryDkgRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDkgRequest) ProtoMessage()    {}
func (*QueryDkgRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4c3d119c3fb9701, []int{4}
}
func (m *QueryDkgRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryDkgRequest.Unmarshal(m, b)
}
func (m *QueryDkgRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryDkgRequest.Marshal(b, m, deterministic)
}
func (m *QueryDkgRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDkgRequest.Merge(m, src)
}
func (m *QueryDkgRequest) XXX_Size() int {
	return xxx_messageInfo_QueryDkgRequest.Size(m)
}
func (m *QueryDkgRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDkgRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDkgRequest proto.InternalMessageInfo

type QueryDkgResponse struct {
	Dkg                  *DealerDKG `protobuf:"bytes,1,opt,name=dkg,proto3" json:"dkg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *QueryDkgResponse) Reset()         { *m = QueryDkgResponse{} }
func (m *QueryDkgResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDkgResponse) ProtoMessage()    {}
func (*QueryDkgResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4c3d119c3fb9701, []int{5}
}
func (m *QueryDkgResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryDkgResponse.Unmarshal(m, b)
}
func (m *QueryDkgResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryDkgResponse.Marshal(b, m, deterministic)
}
func (m *QueryDkgResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDkgResponse.Merge(m, src)
}
func (m *QueryDkgResponse) XXX_Size() int {
	return xxx_messageInfo_QueryDkgResponse.Size(m)
}
func (m *QueryDkgResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDkgResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDkgResponse proto.InternalMessageInfo

func (m *QueryDkgResponse) GetDkg() *DealerDKG {
	if m != nil {
		return m.Dkg
	}
	return nil
}

type QueryHandRequest struct {
	TableId              uint64   `protobuf:"varint,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	HandId               uint64   `protobuf:"varint,2,opt,name=hand_id,json=handId,proto3" json:"hand_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryHandRequest) Reset()         { *m = QueryHandRequest{} }
func (m *QueryHandRequest) String() string { return proto.CompactTextString(m) }
func (*QueryHandRequest) ProtoMessage()    {}
func (*QueryHandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4c3d119c3fb9701, []int{6}
}
func (m *QueryHandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryHandRequest.Unmarshal(m, b)
}
func (m *QueryHandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryHandRequest.Marshal(b, m, deterministic)
}
func (m *QueryHandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryHandRequest.Merge(m, src)
}
func (m *QueryHandRequest) XXX_Size() int {
	return xxx_messageInfo_QueryHandRequest.Size(m)
}
func (m *QueryHandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryHandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryHandRequest proto.InternalMessageInfo

func (m *QueryHandRequest) GetTableId() uint64 {
	if m != nil {
		return m.TableId
	}
	return 0
}

func (m *QueryHandRequest) GetHandId() uint64 {
	if m != nil {
		return m.HandId
	}
	return 0
}

type QueryHandResponse struct {
	Hand                 *DealerHand `protobuf:"bytes,1,opt,name=hand,proto3" json:"hand,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *QueryHandResponse) Reset()         { *m = QueryHandResponse{} }
func (m *QueryHandResponse) String() string { return proto.CompactTextString(m) }
func (*QueryHandResponse) ProtoMessage()    {}
func (*QueryHandResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4c3d119c3fb9701, []int{7}
}
func (m *QueryHandResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryHandResponse.Unmarshal(m, b)
}
func (m *QueryHandResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryHandResponse.Marshal(b, m, deterministic)
}
func (m *QueryHandResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryHandResponse.Merge(m, src)
}
func (m *QueryHandResponse) XXX_Size() int {
	return xxx_messageInfo_QueryHandResponse.Size(m)
}
func (m *QueryHandResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryHandResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryHandResponse proto.InternalMessageInfo

func (m *QueryHandResponse) GetHand() *DealerHand {
	if m != nil {
		return m.Hand
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "onchainpoker.dealer.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "onchainpoker.dealer.v1.QueryParamsResponse")
	proto.RegisterType((*QueryEpochRequest)(nil), "onchainpoker.dealer.v1.QueryEpochRequest")
	proto.RegisterType((*QueryEpochResponse)(nil), "onchainpoker.dealer.v1.QueryEpochResponse")
	proto.RegisterType((*QueryDkgRequest)(nil), "onchainpoker.dealer.v1.QueryDkgRequest")
	proto.RegisterType((*QueryDkgResponse)(nil), "onchainpoker.dealer.v1.QueryDkgResponse")
	proto.RegisterType((*QueryHandRequest)(nil), "onchainpoker.dealer.v1.QueryHandRequest")
	proto.RegisterType((*QueryHandResponse)(nil), "onchainpoker.dealer.v1.QueryHandResponse")
}

func init() {
	proto.RegisterFile("onchainpoker/dealer/v1/query.proto", fileDescriptor_e4c3d119c3fb9701)
}

var fileDescriptor_e4c3d119c3fb9701 = []byte{
	// 508 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x4b, 0x6f, 0xd3, 0x40,
	0x10, 0xc6, 0xad, 0x93, 0xa2, 0x45, 0x02, 0x3a, 0x8d, 0x78, 0xb8, 0x34, 0x2d, 0x1b, 0x01, 0x6d,
	0x91, 0xbc, 0x6a, 0x39, 0x55, 0x20, 0x21, 0xaa, 0xf0, 0xa8, 0x10, 0x12, 0x0d, 0xe2, 0xc2, 0x05,
	0x6d, 0xe3, 0x95, 0x13, 0x39, 0xf5, 0xba, 0x5e, 0xb7, 0xa2, 0xaa, 0x72, 0x41, 0xe2, 0xc0, 0x99,
	0x3b, 0x67, 0xfe, 0x03, 0x7f, 0x80, 0x3b, 0x77, 0x0e, 0x88, 0x1f, 0x82, 0x76, 0x76, 0x4c, 0xc3,
	0xc3, 0x26, 0x37, 0x7b, 0xe6, 0x7b, 0xc5, 0xf3, 0x29, 0x8c, 0xeb, 0xb4, 0x3f, 0x90, 0xc3, 0x34,
	0xd3, 0x89, 0xca, 0x45, 0xa4, 0xe4, 0x48, 0xe5, 0xe2, 0x68, 0x43, 0x1c, 0x1c, 0xaa, 0xfc, 0x38,
	0xcc, 0x72, 0x5d, 0x68, 0xb8, 0x34, 0x89, 0x09, 0x1d, 0x26, 0x3c, 0xda, 0x08, 0x5a, 0xb1, 0x8e,
	0x35, 0x42, 0x84, 0x7d, 0x72, 0xe8, 0x60, 0xb1, 0xaf, 0xcd, 0xbe, 0x36, 0x4e, 0xe1, 0x0f, 0xa9,
	0xe0, 0x5a, 0xac, 0x75, 0x3c, 0x52, 0x42, 0x66, 0x43, 0x21, 0xd3, 0x54, 0x17, 0xb2, 0x18, 0xea,
	0xd4, 0xd0, 0xb6, 0x53, 0x11, 0x86, 0x2c, 0x11, 0xc4, 0x5b, 0x0c, 0x76, 0xad, 0xe2, 0x73, 0x99,
	0xcb, 0x7d, 0xd3, 0x53, 0x07, 0x87, 0xca, 0x14, 0xfc, 0x05, 0x5b, 0xf8, 0x6d, 0x6a, 0x32, 0x9d,
	0x1a, 0x05, 0xf7, 0x58, 0x33, 0xc3, 0xc9, 0x15, 0x6f, 0xc5, 0x5b, 0x3d, 0xb7, 0xd9, 0x0e, 0xff,
	0xfd, 0x5b, 0x42, 0xc7, 0xdb, 0xf6, 0xbf, 0x7c, 0x5b, 0x3e, 0xd3, 0x23, 0x0e, 0x5f, 0x60, 0xf3,
	0x28, 0xfa, 0x30, 0xd3, 0xfd, 0x41, 0xe9, 0xf4, 0x92, 0xfc, 0x69, 0x48, 0x46, 0xf7, 0x59, 0x43,
	0xd9, 0x01, 0xf9, 0x74, 0xaa, 0x7c, 0xba, 0xf8, 0x84, 0x5c, 0x34, 0xf3, 0x7a, 0x8e, 0xc7, 0xe7,
	0xd9, 0x05, 0x94, 0xed, 0x26, 0x71, 0xe9, 0xf4, 0x8c, 0x5d, 0x3c, 0x1d, 0x91, 0xcf, 0x16, 0x9b,
	0x8d, 0x92, 0x98, 0x5c, 0xae, 0xd7, 0xbb, 0x74, 0x9f, 0x3e, 0x26, 0x0f, 0xcb, 0xe1, 0x8f, 0x48,
	0xee, 0x89, 0x4c, 0x23, 0xb2, 0x80, 0xab, 0xec, 0x6c, 0x21, 0xf7, 0x46, 0xea, 0xf5, 0x30, 0x42,
	0x4d, 0xbf, 0x37, 0x87, 0xef, 0x3b, 0x11, 0x5c, 0x66, 0x73, 0x03, 0x99, 0x46, 0x76, 0x33, 0x83,
	0x9b, 0xa6, 0x7d, 0xdd, 0x89, 0xf8, 0x2e, 0x7d, 0x15, 0xa7, 0xf3, 0xeb, 0x43, 0xfb, 0x76, 0x4d,
	0xc1, 0x78, 0x7d, 0x30, 0xcb, 0xa4, 0x64, 0xc8, 0xda, 0xfc, 0xec, 0xb3, 0x06, 0x6a, 0xc2, 0x7b,
	0x8f, 0x35, 0xdd, 0x2d, 0x60, 0xbd, 0x4a, 0xe4, 0xef, 0xf3, 0x07, 0xb7, 0xa7, 0xc2, 0xba, 0xac,
	0xfc, 0xe6, 0xdb, 0xaf, 0x3f, 0x3e, 0xcc, 0xac, 0x40, 0x5b, 0x54, 0xf4, 0xcd, 0x9d, 0x1f, 0xde,
	0x79, 0xac, 0x81, 0x97, 0x82, 0xb5, 0x5a, 0xf9, 0xc9, 0x7a, 0x04, 0xeb, 0xd3, 0x40, 0x29, 0xc8,
	0x0d, 0x0c, 0xb2, 0x0c, 0x4b, 0x55, 0x41, 0xb0, 0x1a, 0x30, 0x66, 0xb3, 0xdd, 0x24, 0x86, 0x5b,
	0xb5, 0xca, 0xa7, 0xbd, 0x09, 0x56, 0xff, 0x0f, 0xa4, 0x00, 0x1d, 0x0c, 0xb0, 0x04, 0x8b, 0x55,
	0x01, 0xa2, 0x24, 0x86, 0x8f, 0x1e, 0xf3, 0xed, 0xc5, 0xa0, 0x5e, 0x77, 0xa2, 0x56, 0xc1, 0xda,
	0x14, 0x48, 0x8a, 0xf0, 0x00, 0x23, 0xdc, 0x85, 0xad, 0xaa, 0x08, 0xd8, 0x47, 0x23, 0x4e, 0xca,
	0x9e, 0x8e, 0x85, 0xad, 0x8c, 0x11, 0x27, 0xd4, 0xce, 0xf1, 0x76, 0xeb, 0xd3, 0xf7, 0xb6, 0xf7,
	0xea, 0xfc, 0x9b, 0x92, 0x54, 0x1c, 0x67, 0xca, 0xec, 0x35, 0xf1, 0xef, 0xe2, 0xce, 0xcf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x7c, 0x38, 0x6e, 0x98, 0xe2, 0x04, 0x00, 0x00,
}

func (this *QueryParamsRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*QueryParamsRequest)
	if !ok {
		that2, ok := that.(QueryParamsRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *QueryParamsResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*QueryParamsResponse)
	if !ok {
		that2, ok := that.(QueryParamsResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Params.Equal(&that1.Params) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *QueryEpochRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*QueryEpochRequest)
	if !ok {
		that2, ok := that.(QueryEpochRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *QueryEpochResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*QueryEpochResponse)
	if !ok {
		that2, ok := that.(QueryEpochResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Epoch.Equal(that1.Epoch) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *QueryDkgRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*QueryDkgRequest)
	if !ok {
		that2, ok := that.(QueryDkgRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *QueryDkgResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*QueryDkgResponse)
	if !ok {
		that2, ok := that.(QueryDkgResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Dkg.Equal(that1.Dkg) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *QueryHandRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*QueryHandRequest)
	if !ok {
		that2, ok := that.(QueryHandRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.TableId != that1.TableId {
		return false
	}
	if this.HandId != that1.HandId {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *QueryHandResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*QueryHandResponse)
	if !ok {
		that2, ok := that.(QueryHandResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Hand.Equal(that1.Hand) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	Epoch(ctx context.Context, in *QueryEpochRequest, opts ...grpc.CallOption) (*QueryEpochResponse, error)
	Dkg(ctx context.Context, in *QueryDkgRequest, opts ...grpc.CallOption) (*QueryDkgResponse, error)
	Hand(ctx context.Context, in *QueryHandRequest, opts ...grpc.CallOption) (*QueryHandResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/onchainpoker.dealer.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Epoch(ctx context.Context, in *QueryEpochRequest, opts ...grpc.CallOption) (*QueryEpochResponse, error) {
	out := new(QueryEpochResponse)
	err := c.cc.Invoke(ctx, "/onchainpoker.dealer.v1.Query/Epoch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Dkg(ctx context.Context, in *QueryDkgRequest, opts ...grpc.CallOption) (*QueryDkgResponse, error) {
	out := new(QueryDkgResponse)
	err := c.cc.Invoke(ctx, "/onchainpoker.dealer.v1.Query/Dkg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Hand(ctx context.Context, in *QueryHandRequest, opts ...grpc.CallOption) (*QueryHandResponse, error) {
	out := new(QueryHandResponse)
	err := c.cc.Invoke(ctx, "/onchainpoker.dealer.v1.Query/Hand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	Epoch(context.Context, *QueryEpochRequest) (*QueryEpochResponse, error)
	Dkg(context.Context, *QueryDkgRequest) (*QueryDkgResponse, error)
	Hand(context.Context, *QueryHandRequest) (*QueryHandResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) Epoch(ctx context.Context, req *QueryEpochRequest) (*QueryEpochResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Epoch not implemented")
}
func (*UnimplementedQueryServer) Dkg(ctx context.Context, req *QueryDkgRequest) (*QueryDkgResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Dkg not implemented")
}
func (*UnimplementedQueryServer) Hand(ctx context.Context, req *QueryHandRequest) (*QueryHandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hand not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onchainpoker.dealer.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Epoch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEpochRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Epoch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onchainpoker.dealer.v1.Query/Epoch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Epoch(ctx, req.(*QueryEpochRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Dkg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDkgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Dkg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onchainpoker.dealer.v1.Query/Dkg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Dkg(ctx, req.(*QueryDkgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Hand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryHandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Hand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onchainpoker.dealer.v1.Query/Hand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Hand(ctx, req.(*QueryHandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "onchainpoker.dealer.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Epoch",
			Handler:    _Query_Epoch_Handler,
		},
		{
			MethodName: "Dkg",
			Handler:    _Query_Dkg_Handler,
		},
		{
			MethodName: "Hand",
			Handler:    _Query_Hand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "onchainpoker/dealer/v1/query.proto",
}
